
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="DTO\GenericResponses\**" />
    <Content Remove="DTO\GenericResponses\**" />
    <EmbeddedResource Remove="DTO\GenericResponses\**" />
    <None Remove="DTO\GenericResponses\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Implementation\EmpAttendanceService_AttendanceCountApproval.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="efpt.config.json.user" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="ClosedXML" Version="0.104.2" />
    <PackageReference Include="Emgu.CV" Version="4.10.0.5680" />
    <PackageReference Include="Emgu.CV.runtime.windows" Version="4.10.0.5680" />
    <PackageReference Include="EPPlus" Version="8.0.5" />
    <PackageReference Include="ExcelDataReader" Version="3.8.0" />
    <PackageReference Include="ExcelDataReader.DataSet" Version="3.8.0" />
    <PackageReference Include="FastMember" Version="1.5.0" />
    <PackageReference Include="MailKit" Version="4.13.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.14" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.3">
	<PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.3" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Newtonsoft.Json.Bson" Version="1.0.3" />
    <PackageReference Include="NLog" Version="6.0.3" />
    <PackageReference Include="NLog.Web.AspNetCore" Version="6.0.3" />
    <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.6.1" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="TrainedFaces\" />
    <Folder Include="wwwroot\" />
  </ItemGroup>

</Project>
