// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class AbscondHistory
{
    public int AbscondHistoryId { get; set; }

    public int EmployeeId { get; set; }

    public string ECode { get; set; }

    public string EmployeeName { get; set; }

    public DateTime AbscondDate { get; set; }

    public string Remarks { get; set; }

    public DateTime? CreatedAt { get; set; }

    public string CreatedBy { get; set; }
}