// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class activeemp_data_temp
{
    public string Vcode { get; set; }

    public string St_code { get; set; }
}