// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class ApplicabilityMaster
{
    public int Id { get; set; }

    public string E_CODE { get; set; }

    public bool? PF_APPLICABLE { get; set; }

    public bool? EPS_APPLICABLE { get; set; }

    public bool? PTAX_APPLICABLE { get; set; }

    public bool? ESIC_APPLICABLE { get; set; }

    public bool? EXTRA_DAY_APPLICABLE { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsDeleted { get; set; }

    public DateTime? CreatedOn { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }
}