// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class ArticleMaster
{
    public long ArticleId { get; set; }

    public DateTime? ART_CR_DATE { get; set; }

    public string SEG { get; set; }

    public string DIV { get; set; }

    public string SUB_DIV { get; set; }

    public string MAJ_CAT_NM { get; set; }

    public string MC_DESC { get; set; }

    public string MC_ST { get; set; }

    public string MC_CODE { get; set; }

    public string GEN_ART { get; set; }

    public string ARTICLE_DESCRIPTION_LONG { get; set; }

    public string ARTICLE_DESCRIPTION { get; set; }

    public string HSN_CODE { get; set; }

    public string VND_CD { get; set; }

    public string VND_NM { get; set; }

    public string VND_DZN_NO { get; set; }

    public string MRP { get; set; }

    public string NOA { get; set; }

    public string RNG_SEG { get; set; }

    public string MAIN_MVGR { get; set; }

    public string MACRO_MVGR { get; set; }

    public string YARN { get; set; }

    public string FAB_WEAVE { get; set; }

    public string FAB2 { get; set; }

    public string FAB_WEAVE_2 { get; set; }

    public string FAB_STYLE { get; set; }

    public string FAB_SUB_STYLE { get; set; }

    public string SHADE { get; set; }

    public string LYCRA { get; set; }

    public string GSM { get; set; }

    public string COUNT { get; set; }

    public string OUNZ { get; set; }

    public string FAB_WEIGHT { get; set; }

    public string COLLAR { get; set; }

    public string NECK_BAND_STYLE { get; set; }

    public string COLLAR_SIZE { get; set; }

    public string PLACKET_CHANGING { get; set; }

    public string BLT_MAIN_STYLE { get; set; }

    public string SUB_STYLE_BLT { get; set; }

    public string BLT_SIZE { get; set; }

    public string SLEEVES_MAIN_STYLE { get; set; }

    public string BTFOLD { get; set; }

    public string SET { get; set; }

    public string NECK_BAND { get; set; }

    public string FO_BTN_STYLE { get; set; }

    public string POCKET { get; set; }

    public string FIT { get; set; }

    public string PATTERN { get; set; }

    public string LENGTH { get; set; }

    public string MAIN_STYLE { get; set; }

    public string DC_SUB_STYLE { get; set; }

    public string DC_EDGE_LOOP { get; set; }

    public string BTN_MAIN_MVGR { get; set; }

    public string SUB_STYLE_BTN_CLR { get; set; }

    public string ZIP { get; set; }

    public string ZIP_COL { get; set; }

    public string ADD_ACC { get; set; }

    public string ACC_COL { get; set; }

    public string PRINT_TYPE { get; set; }

    public string PRINT_PLACEMENT { get; set; }

    public string PRINT_STYLE { get; set; }

    public string PATCHES { get; set; }

    public string PATCH_TYPE { get; set; }

    public string EMBROIDERY { get; set; }

    public string EMB_TYPE { get; set; }

    public string PLACEMENT { get; set; }

    public string ADD_ACC1 { get; set; }

    public string WASH { get; set; }

    public string WASH_COLOR { get; set; }

    public string BUYING_TYPE { get; set; }

    public string PD { get; set; }

    public string BRAND_VENDOR { get; set; }

    public string MDM_REMARKS { get; set; }

    public DateTime? DATE { get; set; }

    public string COLOR1 { get; set; }

    public string SIZE { get; set; }

    public string SEASON { get; set; }

    public string SOURCE { get; set; }

    public string CREATED_BY { get; set; }

    public DateTime? CREATED_DATE { get; set; }

    public bool? IS_DELETED { get; set; }

    public bool? IS_ACTIVE { get; set; }

    public bool? IS_APPROVED { get; set; }
}