// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class ArticleMasteDetailType
    {
        public DateTime? ART_CR_DATE { get; set; }
        [StringLength(15)]
        public string SEG { get; set; }
        [StringLength(50)]
        public string DIV { get; set; }
        [StringLength(50)]
        public string SUB_DIV { get; set; }
        [StringLength(50)]
        public string MAJ_CAT_NM { get; set; }
        [StringLength(50)]
        public string MC_DESC { get; set; }
        [StringLength(50)]
        public string MC_ST { get; set; }
        [StringLength(50)]
        public string MC_CODE { get; set; }
        [StringLength(12)]
        public string GEN_ART { get; set; }
        [StringLength(250)]
        public string ARTICLE_DESCRIPTION_LONG { get; set; }
        [StringLength(250)]
        public string ARTICLE_DESCRIPTION { get; set; }
        [StringLength(20)]
        public string HSN_CODE { get; set; }
        [StringLength(20)]
        public string VND_CD { get; set; }
        [StringLength(100)]
        public string VND_NM { get; set; }
        [StringLength(30)]
        public string VND_DZN_NO { get; set; }
        [StringLength(10)]
        public string MRP { get; set; }
        public string NOA { get; set; }
        public string RNG_SEG { get; set; }
        [StringLength(20)]
        public string MAIN_MVGR { get; set; }
        [StringLength(50)]
        public string MACRO_MVGR { get; set; }
        public string YARN { get; set; }
        [StringLength(30)]
        public string FAB_WEAVE { get; set; }
        [StringLength(50)]
        public string FAB2 { get; set; }
        [StringLength(50)]
        public string FAB_WEAVE_2 { get; set; }
        [StringLength(50)]
        public string FAB_STYLE { get; set; }
        [StringLength(50)]
        public string FAB_SUB_STYLE { get; set; }
        [StringLength(50)]
        public string SHADE { get; set; }
        [StringLength(50)]
        public string LYCRA { get; set; }
        [StringLength(50)]
        public string GSM { get; set; }
        [StringLength(50)]
        public string COUNT { get; set; }
        [StringLength(50)]
        public string OUNZ { get; set; }
        [StringLength(50)]
        public string FAB_WEIGHT { get; set; }
        [StringLength(30)]
        public string COLLAR { get; set; }
        [StringLength(50)]
        public string NECK_BAND_STYLE { get; set; }
        [StringLength(50)]
        public string COLLAR_SIZE { get; set; }
        [StringLength(50)]
        public string PLACKET_CHANGING { get; set; }
        [StringLength(50)]
        public string BLT_MAIN_STYLE { get; set; }
        [StringLength(50)]
        public string SUB_STYLE_BLT { get; set; }
        [StringLength(50)]
        public string BLT_SIZE { get; set; }
        [StringLength(50)]
        public string SLEEVES_MAIN_STYLE { get; set; }
        [StringLength(50)]
        public string BTFOLD { get; set; }
        [StringLength(50)]
        public string SET { get; set; }
        [StringLength(50)]
        public string NECK_BAND { get; set; }
        [StringLength(50)]
        public string FO_BTN_STYLE { get; set; }
        [StringLength(50)]
        public string POCKET { get; set; }
        [StringLength(50)]
        public string FIT { get; set; }
        [StringLength(50)]
        public string PATTERN { get; set; }
        [StringLength(50)]
        public string LENGTH { get; set; }
        [StringLength(50)]
        public string MAIN_STYLE { get; set; }
        [StringLength(50)]
        public string DC_SUB_STYLE { get; set; }
        [StringLength(50)]
        public string DC_EDGE_LOOP { get; set; }
        [StringLength(50)]
        public string BTN_MAIN_MVGR { get; set; }
        [StringLength(50)]
        public string SUB_STYLE_BTN_CLR { get; set; }
        [StringLength(50)]
        public string ZIP { get; set; }
        [StringLength(50)]
        public string ZIP_COL { get; set; }
        [StringLength(50)]
        public string ADD_ACC { get; set; }
        [StringLength(50)]
        public string ACC_COL { get; set; }
        [StringLength(50)]
        public string PRINT_TYPE { get; set; }
        [StringLength(50)]
        public string PRINT_PLACEMENT { get; set; }
        [StringLength(50)]
        public string PRINT_STYLE { get; set; }
        [StringLength(50)]
        public string PATCHES { get; set; }
        [StringLength(50)]
        public string PATCH_TYPE { get; set; }
        [StringLength(50)]
        public string EMBROIDERY { get; set; }
        [StringLength(50)]
        public string EMB_TYPE { get; set; }
        [StringLength(50)]
        public string PLACEMENT { get; set; }
        [StringLength(50)]
        public string ADD_ACC1 { get; set; }
        [StringLength(50)]
        public string WASH { get; set; }
        [StringLength(50)]
        public string WASH_COLOR { get; set; }
        [StringLength(50)]
        public string BUYING_TYPE { get; set; }
        [StringLength(50)]
        public string PD { get; set; }
        [StringLength(50)]
        public string BRAND_VENDOR { get; set; }
        [StringLength(250)]
        public string MDM_REMARKS { get; set; }
        public DateTime? DATE { get; set; }
        [StringLength(50)]
        public string COLOR1 { get; set; }
        [StringLength(50)]
        public string SIZE { get; set; }
        [StringLength(50)]
        public string SEASON { get; set; }
        [StringLength(50)]
        public string SOURCE { get; set; }
    }
}
