// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class AssignLocationHistory
{
    public int? AssignedLocation { get; set; }

    public string AssignedReason { get; set; }

    public bool? IsActive { get; set; }

    public DateTime AssignedOnDate { get; set; }

    public DateTime? ReleasedOnDate { get; set; }

    public int AssignLocationHistoryId { get; set; }

    public int? TransferApprovalStatus { get; set; }

    public int? IsReportingHeadApproval { get; set; }

    public int? IsHRApproval { get; set; }

    public long? CandidateId { get; set; }

    public long? EmployeeId { get; set; }

    public bool? PermanentTransfer { get; set; }

    public bool? TemporaryTransfer { get; set; }

    public int? designationid { get; set; }

    public int? departmentid { get; set; }

    public bool? IsDeleted { get; set; }

    public DateTime? CreatedOn { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public virtual tblDepartment department { get; set; }

    public virtual tblDesignation designation { get; set; }
}