// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class ATTENDANCE_PUNCH_DETAIL
{
    public int? EmpAttendanceId { get; set; }

    public int? EmployeeId { get; set; }

    public string EmployeeName { get; set; }

    public string ECode { get; set; }

    public DateTime? AttendanceDate { get; set; }

    public string Machine_Type { get; set; }

    public string DesignationName { get; set; }

    public string LocationName { get; set; }

    public string STCode { get; set; }

    public string DepartmentName { get; set; }

    public string ShiftName { get; set; }

    public TimeSpan? ShiftStartTime { get; set; }

    public TimeSpan? ShiftEndTime { get; set; }

    public int? IsHoliday { get; set; }

    public string HolidayName { get; set; }

    public TimeSpan? PunchIn { get; set; }

    public TimeSpan? PunchOut { get; set; }

    public TimeSpan? Punch1 { get; set; }

    public TimeSpan? Punch2 { get; set; }

    public TimeSpan? Punch3 { get; set; }

    public TimeSpan? Punch4 { get; set; }

    public TimeSpan? Punch5 { get; set; }

    public TimeSpan? Punch6 { get; set; }

    public TimeSpan? Punch7 { get; set; }

    public TimeSpan? Punch8 { get; set; }

    public TimeSpan? Punch9 { get; set; }

    public TimeSpan? Punch10 { get; set; }

    public TimeSpan? Punch11 { get; set; }

    public TimeSpan? Punch12 { get; set; }

    public int? ValidPunchCount { get; set; }

    public TimeSpan? RegularizePunchIn { get; set; }

    public TimeSpan? RegularizePuncOut { get; set; }

    public int? IsRegularize { get; set; }

    public int? IsOnLeave { get; set; }

    public string TotalWorkingMinutes { get; set; }

    public double? LateMinutes { get; set; }

    public string EarlyMinutes { get; set; }

    public string Status { get; set; }

    public double? TotalWorkingDays { get; set; }

    public string TotalMonthlyWorkingHours { get; set; }
}