// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class AttendanceRecord
{
    public int Id { get; set; }

    public long EmployeeId { get; set; }

    public DateTime PunchTimeUtc { get; set; }

    public int PunchType { get; set; }

    public decimal Latitude { get; set; }

    public decimal Longitude { get; set; }

    public bool WithinGeofence { get; set; }

    public string DeviceInfo { get; set; }

    public string ClientIp { get; set; }

    public int StatusId { get; set; }

    public string LastUpdatedBy { get; set; }

    public DateTime? LastUpdatedOn { get; set; }

    public string Remarks { get; set; }

    public string Address { get; set; }

    public string ProofPath { get; set; }

    public virtual tblEmployee Employee { get; set; }

    public virtual tblStatus Status { get; set; }
}