// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class AttendanceLatePolicy
{
    public int PolicyId { get; set; }

    public int? LocationId { get; set; }

    public bool? IsFlexibleShift { get; set; }

    public DateTime EffectiveFromDate { get; set; }

    public int LateGraceMinutes { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedOn { get; set; }
}