// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class AttendanceCache
{
    public long Id { get; set; }

    public string ZoneName { get; set; }

    public string RegionName { get; set; }

    public string ClusterName { get; set; }

    public string STCode { get; set; }

    public string LocationName { get; set; }

    public string Ecode { get; set; }

    public string FullName { get; set; }

    public string Gender { get; set; }

    public DateTime? DOB { get; set; }

    public decimal? AgeInYears { get; set; }

    public int? DepartmentId { get; set; }

    public int? DesignationId { get; set; }

    public string DepartmentName { get; set; }

    public string DesignationName { get; set; }

    public DateTime? DOJ { get; set; }

    public string ResignationTypeName { get; set; }

    public DateTime? DateOfLeft { get; set; }

    public string BANK_NAME { get; set; }

    public string A_C_NO { get; set; }

    public string BANK_IFSC_CODE { get; set; }

    public string PERMANENT_ADDRESS { get; set; }

    public string PERMANENT_ADDRESS_PIN_CODE { get; set; }

    public string PRESENT_ADDRESS { get; set; }

    public string PRESENT_ADDRESS_PIN_CODE { get; set; }

    public string MOBILE { get; set; }

    public string EMAIL_ADDRESS { get; set; }

    public string AADHAR_NO { get; set; }

    public string PAN_NO { get; set; }

    public string HIGHEST_QUALIFICATION { get; set; }

    public string FATHER_S_NAME { get; set; }

    public string MOTHER_S_NAME { get; set; }

    public string MARITIAL_STATUS { get; set; }

    public string ReportHeadEcode { get; set; }

    public string ReportHeadFullName { get; set; }

    public string ReportHeadDesignation { get; set; }

    public string COMPANY_NAME_1 { get; set; }

    public string From_I { get; set; }

    public string To_I { get; set; }

    public decimal? YEARS_1 { get; set; }

    public string COMPANY_NAME_2 { get; set; }

    public string From_II { get; set; }

    public string To_II { get; set; }

    public decimal? YEARS_2 { get; set; }

    public string COMPANY_NAME_3 { get; set; }

    public string From_III { get; set; }

    public string To_III { get; set; }

    public decimal? YEARS_3 { get; set; }

    public decimal? TTL_EXPERIENCE { get; set; }

    public bool? LocStatus { get; set; }

    public string EmployeeStatus { get; set; }

    public long? EmployeeId { get; set; }

    public long? CandidateId { get; set; }

    public string LocBasedECode { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsDeleted { get; set; }

    public DateTime? DateOfJoining { get; set; }

    public bool? IsStore { get; set; }

    public DateTime? CreatedOn { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public int? PresentDays { get; set; }

    public int? HalfDays { get; set; }

    public int? AbsentDays { get; set; }

    public int? LeaveDays { get; set; }

    public int? RegularisationDays { get; set; }

    public decimal? TotalWorkingDays { get; set; }

    public int? TotalCalendarRows { get; set; }

    public int? NonWorkingRows { get; set; }

    public int? MisPunchDays { get; set; }

    public string TotalMonthlyWorkingHours { get; set; }

    public long? AttendanceCountApprovalId { get; set; }

    public string ApprovalMonthYear { get; set; }

    public int? ApprovalAttendanceCount { get; set; }

    public string EmployeeRemarks { get; set; }

    public string ApprovalStatus { get; set; }

    public string ApprovalStatusDescription { get; set; }

    public bool? IsCMApproved { get; set; }

    public string CMApprovedBy { get; set; }

    public DateTime? CMApprovedOn { get; set; }

    public string CMRemarks { get; set; }

    public bool? IsRMApproved { get; set; }

    public string RMApprovedBy { get; set; }

    public DateTime? RMApprovedOn { get; set; }

    public string RMRemarks { get; set; }

    public int? AttachmentCount { get; set; }

    public string AttachmentFilePaths { get; set; }

    public string Month_Year { get; set; }
}