// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class AuditLog
{
    public int AuditLogId { get; set; }

    public string TableName { get; set; }

    public string PrimaryKeyValue { get; set; }

    public string ColumnName { get; set; }

    public string OldValue { get; set; }

    public string NewValue { get; set; }

    public string ChangedBy { get; set; }

    public DateTime? ChangedDate { get; set; }

    public string ChangeType { get; set; }
}