// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class BGTSEATMaster_bACKUP
{
    public int Id { get; set; }

    public string LOC_CODE { get; set; }

    public string DEPT_SNO { get; set; }

    public string DEPARTMENT { get; set; }

    public string DESG_SNO { get; set; }

    public string DESIGNATION { get; set; }

    public string SEAT_MASTER_NO { get; set; }

    public decimal? SALARY_BGT { get; set; }

    public string ORG_CHART { get; set; }

    public string REPORTING_MANAGER { get; set; }

    public bool? ACTIVE { get; set; }
}