// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class BGTSEATAssignment
{
    public int Id { get; set; }

    public string LOC_CODE { get; set; }

    public string SEAT_MAS { get; set; }

    public string E_CODE { get; set; }
}