// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class BonusAndGratutityOpening
{
    public int ID { get; set; }

    public string ECode { get; set; }

    public string Month { get; set; }

    public decimal? Gratuity { get; set; }

    public decimal? Bonus { get; set; }

    public decimal? ActualGratuity { get; set; }

    public decimal? ActualBonus { get; set; }

    public decimal? ClosingGratuity { get; set; }
}