// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class BudgetedWeekOffPolicyMaster
{
    public string LocationCode { get; set; }

    public string LocationName { get; set; }

    public int? DesignationId { get; set; }

    public string DesignationName { get; set; }

    public string SatCount { get; set; }

    public int Id { get; set; }
}