// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class BudgetWeekoffMaster_07112025
{
    public DateTime? IF_Joining_Date { get; set; }

    public string LocationCode { get; set; }

    public string LocationName { get; set; }

    public int? DesignationId { get; set; }

    public string DesignationName { get; set; }

    public string SatCount { get; set; }

    public int? AllowedSaturdays { get; set; }

    public int? AllowedSundays { get; set; }

    public int? TotalWeekOffs { get; set; }

    public int Id { get; set; }
}