// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class BulkEmployeeMasternewnew
{
    public string Ecode { get; set; }

    public string FULLNAME { get; set; }

    public string Location { get; set; }

    public string GENDER { get; set; }

    public string DOB { get; set; }

    public string Department { get; set; }

    public string Designation { get; set; }

    public string DOJ { get; set; }

    public string Column8 { get; set; }

    public string Column9 { get; set; }
}