// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class BulkEmployeeMaster
{
    public string Ecode { get; set; }

    public string TITLE { get; set; }

    public string FULL_NAME { get; set; }

    public string FATHER_S_NAME { get; set; }

    public string MOTHER_S_NAME { get; set; }

    public string PASPORT_SIZE_PHOTO { get; set; }

    public string DOB { get; set; }

    public string GENDER { get; set; }

    public string PAN_NO { get; set; }

    public string AADHAR_NO { get; set; }

    public string NAME_ON_ADHAR { get; set; }

    public string PLACE_OF_BIRTH { get; set; }

    public string PRESENT_ADDRESS { get; set; }

    public string PRESENT_ADDRESS_PIN_CODE { get; set; }

    public string PERMANENT_ADDRESS { get; set; }

    public string MARITIAL_STATUS { get; set; }

    public string MOBILE { get; set; }

    public string EMAIL_ADDRESS { get; set; }

    public string NATIONALITY { get; set; }

    public string RELIGION { get; set; }

    public string BANK_NAME { get; set; }

    public string A_C_NO { get; set; }

    public string BANK_IFSC_CODE { get; set; }

    public string REFERENCE1__OF_LAST_3_COMPANY { get; set; }

    public string CONTACT1_OF_LAST_3_COMPANY { get; set; }

    public string REFERENCE2__OF_LAST_3_COMPANY1 { get; set; }

    public string CONTACT2_OF_LAST_3_COMPANY1 { get; set; }

    public string REFERENCE3__OF_LAST_3_COMPANY11 { get; set; }

    public string CONTACT3_OF_LAST_3_COMPANY11 { get; set; }

    public string REFERENCE4__OF_LAST_3_COMPANY11 { get; set; }

    public string CONTACT4_OF_LAST_3_COMPANY11 { get; set; }

    public string REFERENCE5__OF_LAST_3_COMPANY111 { get; set; }

    public string CONTACT5_OF_LAST_3_COMPANY111 { get; set; }

    public string FAMILY_MEMBER_Name { get; set; }

    public string FAMILY_MEMBER_Relation { get; set; }

    public string FAMILY_MEMBER_DOB { get; set; }

    public string COMPANY_1 { get; set; }

    public string COMPANY_2 { get; set; }

    public string COMPANY_3 { get; set; }

    public string WORK_LOCATION { get; set; }

    public string POSITION_HELD_IN_PREVIOUS_COMPANY { get; set; }

    public string From { get; set; }

    public string To { get; set; }

    public string In_Hand_Salary { get; set; }

    public string LAST_CTC_ANNUAL_ { get; set; }

    public string HIGHEST_QUALIFICATION { get; set; }

    public string Column46 { get; set; }

    public string Column47 { get; set; }

    public string Ecode_1 { get; set; }

    public string Designation { get; set; }

    public string Department { get; set; }

    public string Location { get; set; }

    public string DOJ { get; set; }

    public string DateOfResignation { get; set; }

    public string DateOfLeft { get; set; }

    public string isresgined { get; set; }

    public string FirstName { get; set; }

    public string MiddleName { get; set; }

    public string LastName { get; set; }

    public string ReportingHeadEcode { get; set; }

    public string MOBILE2 { get; set; }
}