// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class BulkRegionMaster
{
    public string STCode { get; set; }

    public string RegionName { get; set; }

    public string StateName { get; set; }
}