// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class CandidateStatusHistory
{
    public int HistoryId { get; set; }

    public long? CandidateId { get; set; }

    public int? StatusId { get; set; }

    public string HRName { get; set; }

    public DateTime? CallDate { get; set; }

    public TimeSpan? CallStartTime { get; set; }

    public TimeSpan? CallEndTime { get; set; }

    public string CallResponse { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Candidate Candidate { get; set; }

    public virtual CandidateStatus Status { get; set; }
}