// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class candidate_tracker
{
    public string source { get; set; }

    public string dept { get; set; }

    public string loc { get; set; }

    public string desg { get; set; }

    public string current_status { get; set; }

    public string candidate_name { get; set; }

    public string current_company { get; set; }

    public string highest_qualification { get; set; }

    public string current_ctc { get; set; }

    public string contact_no { get; set; }

    public string interview1_act_dt { get; set; }

    public string interviewer1_nm { get; set; }

    public string interviewer1_status { get; set; }

    public string interview2_act_dt { get; set; }

    public string interviewer2_nm { get; set; }

    public string interviewer2_status { get; set; }

    public string interview_final_remark { get; set; }
}