// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class CandidateProcessStatus
{
    public int StatusId { get; set; }

    public string StatusName { get; set; }
}