// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class CandidateStatus_History
{
    public int HistoryId { get; set; }

    public int ApplicantId { get; set; }

    public int? OldStatusId { get; set; }

    public string OldStatusName { get; set; }

    public int? NewStatusId { get; set; }

    public string NewStatusName { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }
}