// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class Candidate_2025_08_05_nik
{
    public string TITLE { get; set; }

    public string FIRST_NAME { get; set; }

    public string MIDDLE_NAME { get; set; }

    public string LAST_NAME { get; set; }

    public string HUSBAND_NAME { get; set; }

    public string FATHER_NAME { get; set; }

    public string MOTHER_NAME { get; set; }

    public string DESIGNATION { get; set; }

    public string LOCATION { get; set; }

    public DateTime? DOB { get; set; }

    public string GENDER { get; set; }

    public string DEPARTMENT { get; set; }

    public DateTime? JOINING_DATE { get; set; }

    public decimal? GROSS_SALARY { get; set; }

    public string UAN_NO { get; set; }

    public string PAN_NO { get; set; }

    public string AADHAR_NO { get; set; }

    public string NAME_ON_AADHAR { get; set; }

    public string udf1 { get; set; }

    public string PLACE_OF_BIRTH { get; set; }

    public string PRESENT_ADDRESS { get; set; }

    public string PRESENT_ADDRESS_PIN_CODE { get; set; }

    public string PERMANENT_ADDRESS { get; set; }

    public string _PERMANENT_ADDRESS_PIN_CODE { get; set; }

    public string EMP_CODE { get; set; }

    public string APPLICANT_CODE { get; set; }

    public string WEEKLY_OFF { get; set; }

    public string MARITIAL_STATUS { get; set; }

    public string MOBILE { get; set; }

    public string EMAIL_ADDRESS { get; set; }

    public bool? ISRELATIVEINCOMPANY { get; set; }

    public string NATIONALITY { get; set; }

    public string RELIGION { get; set; }

    public string BANK_NAME { get; set; }

    public string A_C_NO { get; set; }

    public string BANK_IFSC_CODE { get; set; }

    public string REFERENCE1__OF_LAST_3_COMPANY { get; set; }

    public string CONTACT1_OF_LAST_3_COMPANY { get; set; }

    public string REFERENCE2__OF_LAST_3_COMPANY { get; set; }

    public string CONTACT2_OF_LAST_3_COMPANY { get; set; }

    public string REFERENCE3__OF_LAST_3_COMPANY { get; set; }

    public string CONTACT3_OF_LAST_3_COMPANY { get; set; }

    public string REFERENCE4__OF_LAST_3_COMPANY { get; set; }

    public string CONTACT4_OF_LAST_3_COMPANY { get; set; }

    public string REFERENCE5__OF_LAST_3_COMPANY { get; set; }

    public string CONTACT5_OF_LAST_3_COMPANY { get; set; }

    public string FAMILY_MEMBER_Name { get; set; }

    public string FAMILY_MEMBER_Relation { get; set; }

    public DateTime? FAMILY_MEMBER_DOB { get; set; }

    public string COMPANY_1 { get; set; }

    public string COMPANY_2 { get; set; }

    public string COMPANY_3 { get; set; }

    public string WORK_LOCATION { get; set; }

    public string POSITION_HELD_IN_PREVIOUS_COMPANY { get; set; }

    public string From { get; set; }

    public string To { get; set; }

    public string In_Hand_Salary { get; set; }

    public string LAST_CTC_ANNUAL_ { get; set; }

    public string HIGHEST_QUALIFICATION { get; set; }

    public string BENEFICIARY_ADDRESS { get; set; }

    public string PREV__EST_NO_ { get; set; }

    public string REFERENCE { get; set; }

    public DateTime? CreatedOn { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public string DeletedBy { get; set; }

    public DateTime? DeletedOn { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsDeleted { get; set; }

    public bool? IsSalarySlipUploaded { get; set; }

    public bool? IsBankStatementUploaded { get; set; }

    public bool? IsPrevOfferLetterUploaded { get; set; }

    public bool? IsPassportPhotoUploaded { get; set; }

    public bool? IsPanAttachmentUploaded { get; set; }

    public bool? IsAadharAttachmentUploaded { get; set; }

    public bool? IsBankPassbookAttachmentUpoaded { get; set; }

    public bool? IsEducationAttachmentUploaded { get; set; }

    public int? StatusId { get; set; }

    public string ApplicantId { get; set; }

    public decimal? BasicSalary { get; set; }

    public decimal? HRA { get; set; }

    public decimal? CCA { get; set; }

    public decimal? SpecialAllowance { get; set; }

    public decimal? DA { get; set; }

    public decimal? ExtraAllowance { get; set; }

    public decimal? monthlyGrossCTC { get; set; }

    public decimal? annuallyNetCTC { get; set; }

    public bool? IsResumeUploaded { get; set; }

    public decimal? TotalExperience { get; set; }

    public decimal? SalaryExpectation { get; set; }

    public string AdditionalInfoApplicant { get; set; }

    public bool? Agreement { get; set; }

    public bool? IsApplicant { get; set; }

    public bool? IsApplicantApproved { get; set; }

    public bool? PFApplicable { get; set; }

    public bool? BonusApplicable { get; set; }

    public bool? ESICApplicable { get; set; }

    public int? CompanyId { get; set; }

    public bool? IsEvaluationAttachmentUploaded { get; set; }

    public bool? IsOfferLetterAttachmentUploaded { get; set; }

    public bool? IsInterviewVideoUploaded { get; set; }

    public string ReportHeadEcode { get; set; }

    public bool? DeclarationConfirmed { get; set; }

    public string Place { get; set; }

    public DateTime? DateOfFilling { get; set; }

    public bool? IsOtherAttachmentUploaded { get; set; }

    public string SkillType { get; set; }

    public string DifferentlyAbledRemarks { get; set; }

    public string DifferentlyAbledReason { get; set; }

    public bool? DifferentlyAbled { get; set; }
}