// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class ContractorMasterDetail
{
    public long ContractId { get; set; }

    public string ContractorName { get; set; }

    public string ContractorCode { get; set; }

    public int? ContarctStatusId { get; set; }

    public int? ServiceCategoryId { get; set; }

    public string ServiceCategory { get; set; }

    public string NatureOfWork { get; set; }

    public DateTime? ContractStartDate { get; set; }

    public DateTime? ContractEndDate { get; set; }

    public string ContractStatus { get; set; }

    public string RegisteredAddress { get; set; }

    public string SiteAddress { get; set; }

    public string ContactPersonName { get; set; }

    public string MobileNumber { get; set; }

    public string EmailID { get; set; }

    public string PAN { get; set; }

    public string GSTIN { get; set; }

    public string PFRegistrationNumber { get; set; }

    public string ESICRegistrationNumber { get; set; }

    public string LabourLicenseNumber { get; set; }

    public string BankName { get; set; }

    public string BranchName { get; set; }

    public string AccountHolderName { get; set; }

    public string AccountNumber { get; set; }

    public string IFSCCode { get; set; }

    public string AccountType { get; set; }

    public string PaymentMode { get; set; }

    public string BeneficiaryName { get; set; }

    public bool? GSTApplicability { get; set; }

    public bool? BankVerificationStatus { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public DateTime? CreatedOn { get; set; }

    public string CreatedBy { get; set; }

    public bool? IsActive { get; set; }

    public bool IsDeleted { get; set; }
}