// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class EcodeZoneRegionClusterMapping
{
    public string Ecode { get; set; }

    public string Zone { get; set; }

    public string Region { get; set; }

    public string Cluster { get; set; }

    public int Id { get; set; }
}