// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class EcodeWiseDeduction
{
    public string E_Code { get; set; }

    public int? Month { get; set; }

    public int? Year { get; set; }

    public decimal? P_Tax_Ded_ { get; set; }

    public decimal? Cash_Short_Ded_ { get; set; }

    public decimal? Diesel_Deduction_Ded_ { get; set; }

    public decimal? Penalty_Ded_ { get; set; }

    public decimal? Lwf_Ded_ { get; set; }

    public decimal? Employee_P_F__Cont_ { get; set; }

    public decimal? Employer_P_F__Cont_ { get; set; }

    public decimal? Employer_F_P_F__Cont_ { get; set; }

    public decimal? Employee_E_S_I__Cont_ { get; set; }

    public decimal? Employer_E_S_I__Cont_ { get; set; }

    public decimal? Loan_Installment { get; set; }

    public decimal? T_D_S__Ded_ { get; set; }

    public decimal? Monthly_Advance { get; set; }

    public decimal? Total_Deductions { get; set; }

    public DateTime? CreatedOn { get; set; }
}