// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class EcodesForWhichNoPFNoESIC
{
    public int Id { get; set; }

    public string Ecode { get; set; }

    public bool? IsPFShouldDeduct { get; set; }

    public bool? IsESICShouldDeduct { get; set; }
}