// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class emp_manager
{
    public string ST_CODE { get; set; }

    public string ST_NAME { get; set; }

    public string STAFF_NAME { get; set; }

    public string STAFF_E_CODE_ { get; set; }

    public string CURRENT_REPORTING_SHOWN { get; set; }

    public string REQUIRED_REPORTING_MANAGER_NAME { get; set; }

    public string REQUIRED_REPORTING_MANAGER_E_CODE { get; set; }
}