// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class Emp_Attendance_Format_Detail
{
    public string Ecode { get; set; }

    public string Location_Code { get; set; }

    public string Location_Name { get; set; }

    public string Employee_Name { get; set; }

    public string Designation { get; set; }

    public string Department { get; set; }

    public string Month_Year { get; set; }

    public decimal? Ttl_Bgt_Days { get; set; }

    public decimal? ActualTtl_Days { get; set; }

    public decimal? ActualWeekly { get; set; }

    public decimal? PresentWeeklyOff { get; set; }

    public decimal? PaybleDays { get; set; }

    public decimal? ExtraDays { get; set; }

    public decimal? Absent { get; set; }

    public decimal? BasicSalary_Bud { get; set; }

    public decimal? HRA_Bud { get; set; }

    public decimal? CCA_Bud { get; set; }

    public decimal? SpecialAllowance_Bud { get; set; }

    public decimal? DA_Bud { get; set; }

    public decimal? Reimbursement_Bud { get; set; }

    public decimal? Fuel_Maintenance_Bud { get; set; }

    public decimal? Books_Periodicals_Bud { get; set; }

    public decimal? Professional_Attire_Bud { get; set; }

    public decimal? Driver_Wages_Bud { get; set; }

    public decimal? Mobile_Bill_Bud { get; set; }

    public decimal? Meal_Voucher_Bud { get; set; }

    public decimal? Monthly_Gross_CTC_Bud { get; set; }

    public decimal? BasicSalary_Actual { get; set; }

    public decimal? HRA_Actual { get; set; }

    public decimal? CCA_Actual { get; set; }

    public decimal? SpecialAllowance_Actual { get; set; }

    public decimal? DA_Actual { get; set; }

    public decimal? ExtraDayAllowance { get; set; }

    public decimal? Reimbursement_Actual { get; set; }

    public decimal? Fuel_Maintenance_Actual { get; set; }

    public decimal? Books_Periodicals_Actual { get; set; }

    public decimal? Professional_Attire_Actual { get; set; }

    public decimal? Driver_Wages_Actual { get; set; }

    public decimal? Mobile_Bill_Actual { get; set; }

    public decimal? Meal_Voucher_Actual { get; set; }

    public decimal? PF_Employee { get; set; }

    public decimal? PF_Employer { get; set; }

    public decimal? PF_Total { get; set; }

    public decimal? ESIC_Employee { get; set; }

    public decimal? ESIC_Employer { get; set; }

    public decimal? ESIC_Total { get; set; }

    public decimal? TDS { get; set; }

    public decimal? PTax { get; set; }

    public decimal? Loan { get; set; }

    public decimal? CashShort { get; set; }

    public decimal? DieselDeduction { get; set; }

    public decimal? Penalty { get; set; }

    public decimal? Lwf { get; set; }

    public decimal? Monthly_Gross_CTC_Actual { get; set; }

    public decimal? Monthly_Gross_CTC_Actual_After_Deduction { get; set; }

    public decimal? Payable_Days { get; set; }

    public decimal? Leave_Used { get; set; }

    public int? Opening_EL { get; set; }

    public decimal? EarnedLeaveAcquired { get; set; }

    public decimal? EarnedLeaveUsed { get; set; }

    public decimal? EarnedLeaveBalance { get; set; }

    public int? Opening_CL { get; set; }

    public decimal? CasualLeaveAcquired { get; set; }

    public decimal? CasualLeaveUsed { get; set; }

    public decimal? CasualLeaveBalance { get; set; }
}