// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class emp_leave_bal
{
    public string ECODE { get; set; }

    public double? EL { get; set; }

    public double? CL { get; set; }
}