// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class EmpJoiningReleavingDetail
{
    public int Id { get; set; }

    public string E_CODE { get; set; }

    public DateTime? JOINING_DATE { get; set; }

    public DateTime? RELEAVING_DATE { get; set; }

    public string JOINED_LOCATION { get; set; }

    public string JOINED_DEPARTMENT { get; set; }

    public string JOINED_DESIGNATION { get; set; }

    public string STORE_CODE { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsDeleted { get; set; }

    public DateTime? CreatedOn { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }
}