// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class EmployeePayrollUpload
{
    public int Id { get; set; }

    public string ECode { get; set; }

    public string LocCode { get; set; }

    public string Location { get; set; }

    public string EmpName { get; set; }

    public string Department { get; set; }

    public string Designation { get; set; }

    public string ExcelMonthYear { get; set; }

    public decimal? PayableDays { get; set; }

    public decimal? EmpPF { get; set; }

    public decimal? EmprPF { get; set; }

    public decimal? DepositedPF { get; set; }

    public string ChallanNumber { get; set; }

    public string ChallanPdfPath { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedOn { get; set; }

    public string LastUpdatedBy { get; set; }

    public DateTime? LastUpdatedOn { get; set; }

    public string MonthYear { get; set; }
}