// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class EmployeeResignationChecklistResponse
{
    public int EmployeeResignationChecklistResponseId { get; set; }

    public bool? ResignationChecklistResponse { get; set; }

    public int EmployeeResignationChecklistMasterId { get; set; }

    public string EmployeeId { get; set; }

    public string LastUpdatedBy { get; set; }

    public DateTime? LastUpdatedOn { get; set; }

    public DateTime? CreatedOn { get; set; }

    public string CreatedBy { get; set; }

    public string Attachment { get; set; }

    public virtual EmployeeResignationChecklistMaster EmployeeResignationChecklistMaster { get; set; }
}