// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class EmployeeShiftHistory
{
    public long HistoryId { get; set; }

    public long EmployeeId { get; set; }

    public int ShiftId { get; set; }

    public DateTime EffectiveFrom { get; set; }

    public DateTime? EffectiveTo { get; set; }

    public DateTime AssignedOn { get; set; }

    public string AssignedBy { get; set; }

    public string Remarks { get; set; }

    public DateTime? AppliedOn { get; set; }

    public virtual tblEmployee Employee { get; set; }

    public virtual tblShiftMaster Shift { get; set; }
}