// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class EmployeeResignationChecklistByECodeResult
    {
        public int EmployeeResignationChecklistMasterId { get; set; }
        [StringLength(50)]
        public string CheckListName { get; set; }
        [StringLength(500)]
        public string ResignationChecklist { get; set; }
        public bool? MasterIsActive { get; set; }
        public bool? IsAttachment { get; set; }
        public DateTime? MasterCreatedOn { get; set; }
        [StringLength(50)]
        public string MasterCreatedBy { get; set; }
        public int? EmployeeResignationChecklistResponseId { get; set; }
        [StringLength(20)]
        public string EmployeeId { get; set; }
        public bool? ResignationChecklistResponse { get; set; }
        [StringLength(250)]
        public string Attachment { get; set; }
        public DateTime? ResponseCreatedOn { get; set; }
        [StringLength(50)]
        public string ResponseCreatedBy { get; set; }
    }
}
