// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class EmployeeESICUploadHistory
{
    public int HistoryId { get; set; }

    public int? OriginalId { get; set; }

    public string ECode { get; set; }

    public string LocCode { get; set; }

    public string Location { get; set; }

    public string EmpName { get; set; }

    public string Department { get; set; }

    public string Designation { get; set; }

    public string MonthYear { get; set; }

    public decimal? PayableDays { get; set; }

    public decimal? EmpESIC { get; set; }

    public decimal? EmprESIC { get; set; }

    public decimal? DepositedESIC { get; set; }

    public string StoreCode { get; set; }

    public string ChallanNumber { get; set; }

    public string ChallanPdfPath { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedOn { get; set; }

    public string ArchivedBy { get; set; }

    public DateTime ArchivedOn { get; set; }
}