// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class EmpList
{
    public string Ecode { get; set; }

    public string EMAIL_ADDRESS { get; set; }

    public string FULL_NAME { get; set; }

    public bool? IsActive { get; set; }

    public string CompanyName { get; set; }

    public string DepartmentName { get; set; }

    public string DesignationName { get; set; }
}