// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class EmployeeResignationChecklistMaster
{
    public int EmployeeResignationChecklistMasterId { get; set; }

    public string ResignationChecklist { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsDeleted { get; set; }

    public string LastUpdatedBy { get; set; }

    public DateTime? LastUpdatedOn { get; set; }

    public DateTime? CreatedOn { get; set; }

    public string CreatedBy { get; set; }

    public string CheckListName { get; set; }

    public bool? IsAttachment { get; set; }

    public virtual ICollection<EmployeeResignationChecklistResponse> EmployeeResignationChecklistResponses { get; set; } = new List<EmployeeResignationChecklistResponse>();
}