// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class EmployeeDateGrid
{
    public int EmpAttendanceId { get; set; }

    public long EmployeeId { get; set; }

    public string EmployeeName { get; set; }

    public string ECode { get; set; }

    public DateTime? AttendanceDate { get; set; }

    public string Machine_Type { get; set; }

    public string DesignationName { get; set; }

    public string LocationName { get; set; }

    public string STCode { get; set; }

    public string DepartmentName { get; set; }

    public string Punch1 { get; set; }

    public string Punch2 { get; set; }

    public string Punch3 { get; set; }

    public string Punch4 { get; set; }

    public string Punch5 { get; set; }

    public string Punch6 { get; set; }

    public string Punch7 { get; set; }

    public string Punch8 { get; set; }

    public string Punch9 { get; set; }

    public string Punch10 { get; set; }

    public string Punch11 { get; set; }

    public string Punch12 { get; set; }

    public TimeSpan PunchIn { get; set; }

    public TimeSpan PunchOut { get; set; }

    public int ValidPunchCount { get; set; }

    public TimeSpan RegularizePunchIn { get; set; }

    public TimeSpan RegularizePuncOut { get; set; }

    public bool? IsRegularize { get; set; }

    public int IsOnLeave { get; set; }

    public string TotalWorkingMinutes { get; set; }

    public int? LateMinutes { get; set; }

    public int? EarlyMinutes { get; set; }

    public string Status { get; set; }

    public decimal? TotalWorkingDays { get; set; }

    public string TotalMonthlyWorkingHours { get; set; }
}