// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class EmpLeaveClosingBalance
{
    public string ECODE { get; set; }

    public string MONTH { get; set; }

    public decimal? EL_Closing { get; set; }

    public decimal? Cl_Closing { get; set; }

    public decimal? CompoOff_Closing { get; set; }
}