// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class EmpPF
{
    public string Ecode { get; set; }

    public decimal? PF { get; set; }

    public decimal? EPF { get; set; }
}