// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class EmpPersonalDetail
{
    public int Id { get; set; }

    public string E_CODE { get; set; }

    public string NAME { get; set; }

    public string GENDER { get; set; }

    public string FATHER_NAME { get; set; }

    public string MOBILE_NO { get; set; }

    public string ADDRESS_DETAIL { get; set; }

    public DateTime? D_O_B { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsDeleted { get; set; }

    public DateTime? CreatedOn { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }
}