// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class EmpPastExperienceDetail
{
    public int Id { get; set; }

    public string E_CODE { get; set; }

    public string COMP_S_NO { get; set; }

    public string COMP_NAME { get; set; }

    public string LOCATION { get; set; }

    public string DESIGNATION { get; set; }

    public DateTime? FROM_DATE { get; set; }

    public DateTime? TO_DATE { get; set; }

    public decimal? LAST_CTC { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsDeleted { get; set; }

    public DateTime? CreatedOn { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }
}