// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class EmpRevisedDeptDesgLocDetail
{
    public int Id { get; set; }

    public string E_CODE { get; set; }

    public string NEW_DEPARTMENT { get; set; }

    public string NEW_DESIGNATION { get; set; }

    public string POSTED_LOCATION { get; set; }

    public DateTime? POSTED_DT { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsDeleted { get; set; }

    public DateTime? CreatedOn { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }
}