// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class EmpStatutoryDetail
{
    public int Id { get; set; }

    public string E_CODE { get; set; }

    public string Name_of_Bank { get; set; }

    public string IFSC_Code { get; set; }

    public string AC_NO { get; set; }

    public string UAN_NO { get; set; }

    public string PF_NO { get; set; }

    public string ESI_NO { get; set; }

    public string PAN_NO { get; set; }

    public string AADHAR_NO { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsDeleted { get; set; }

    public DateTime? CreatedOn { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }
}