// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class EmpSalaryStructure
{
    public int Id { get; set; }

    public string E_CODE { get; set; }

    public decimal? BASIC_RATE { get; set; }

    public decimal? HRA_RATE { get; set; }

    public decimal? DA_RATE { get; set; }

    public decimal? CCA_RATE { get; set; }

    public decimal? SPL_ALLOWANCE_RATE { get; set; }

    public decimal? REIMB_RATE { get; set; }

    public decimal? Fuel_and_Maintainence { get; set; }

    public decimal? Books_and_Periodicals { get; set; }

    public decimal? ProfessionalAttire { get; set; }

    public decimal? DriverWages { get; set; }

    public decimal? MOBILE_BILL { get; set; }

    public decimal? MealVoucher { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsDeleted { get; set; }

    public DateTime? CreatedOn { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }
}