// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class EmpSalaryStatus
{
    public int ID { get; set; }

    public string ECode { get; set; }

    public string Month { get; set; }

    public string Status { get; set; }

    public DateTime? ActionDate { get; set; }

    public string Remarks { get; set; }

    public DateTime? CreatedOn { get; set; }
}