// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class EMPTOBEINACTIVE
{
    public int ID { get; set; }

    public string ECODE { get; set; }

    public string DOL { get; set; }

    public DateTime? CreatedOn { get; set; }
}