// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class EmpTDSTable
{
    public int Id { get; set; }

    public string E_CODE { get; set; }

    public string MTH { get; set; }

    public decimal? TDS { get; set; }

    public decimal? PTax { get; set; }

    public decimal? Loan { get; set; }

    public decimal? CashShort { get; set; }

    public decimal? DieselDeduction { get; set; }

    public decimal? Penality { get; set; }

    public decimal? Lwf { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsDeleted { get; set; }

    public DateTime? CreatedOn { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }
}