// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class EMPWITHEREPORTINGHEADCODE
{
    public string Ecode { get; set; }

    public string ReportHeadEcode { get; set; }
}