// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class ExperienceTableType
    {
        public int? TotalIndustryExperienceYears { get; set; }
        public int? TotalRetailExperienceYears { get; set; }
        public int? NoticePeriodDays { get; set; }
        [Column("CurrentCTC", TypeName = "decimal(18,2)")]
        public decimal? CurrentCTC { get; set; }
        [Column("ExpectedCTC", TypeName = "decimal(18,2)")]
        public decimal? ExpectedCTC { get; set; }
    }
}
