// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class FamilyTableType
    {
        [StringLength(200)]
        public string Name { get; set; }
        [StringLength(200)]
        public string Relation { get; set; }
        [StringLength(200)]
        public string Occupation { get; set; }
        [StringLength(200)]
        public string Dependent { get; set; }
    }
}
