// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class fn_GetRbacHierarchyByRoleResult
    {
        public int RoleId { get; set; }
        [StringLength(100)]
        public string RoleName { get; set; }
        public int ModuleId { get; set; }
        [StringLength(200)]
        public string ModuleName { get; set; }
        public bool? ModuleStatus { get; set; }
        public int? SubModuleId { get; set; }
        [StringLength(200)]
        public string SubModuleName { get; set; }
        public bool? SubModuleStatus { get; set; }
        public int? ActionId { get; set; }
        [StringLength(100)]
        public string ActionName { get; set; }
        public bool? ActionStatus { get; set; }
        public int? ActionFurtherPartId { get; set; }
        [StringLength(200)]
        public string ActionFurtherPartName { get; set; }
        public bool? FurtherPartStatus { get; set; }
    }
}
