// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class fn_GetMonthlyPunchesRange_newResult
    {
        public int? EmpAttendanceId { get; set; }
        public long EmployeeId { get; set; }
        [StringLength(201)]
        public string EmployeeName { get; set; }
        public string ECode { get; set; }
        public DateTime? AttendanceDate { get; set; }
        [StringLength(8000)]
        public string Machine_Type { get; set; }
        [StringLength(255)]
        public string DesignationName { get; set; }
        [StringLength(255)]
        public string LocationName { get; set; }
        [StringLength(10)]
        public string STCode { get; set; }
        [StringLength(255)]
        public string DepartmentName { get; set; }
        public TimeSpan Punch1 { get; set; }
        public TimeSpan Punch2 { get; set; }
        public TimeSpan Punch3 { get; set; }
        public TimeSpan Punch4 { get; set; }
        public TimeSpan Punch5 { get; set; }
        public TimeSpan Punch6 { get; set; }
        public TimeSpan Punch7 { get; set; }
        public TimeSpan Punch8 { get; set; }
        public TimeSpan Punch9 { get; set; }
        public TimeSpan Punch10 { get; set; }
        public TimeSpan Punch11 { get; set; }
        public TimeSpan Punch12 { get; set; }
        public TimeSpan? PunchIn { get; set; }
        public TimeSpan? PunchOut { get; set; }
        public TimeSpan? RegularizePunchIn { get; set; }
        public TimeSpan? RegularizePunchOut { get; set; }
        public bool? IsRegularize { get; set; }
        public bool? IsOnLeave { get; set; }
        public int? TotalWorkingMinutes { get; set; }
        [StringLength(15)]
        public string Status { get; set; }
    }
}
