// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class fn_GetMonthlyAttendanceResult
    {
        public long? EmpAttendanceId { get; set; }
        public long EmployeeId { get; set; }
        [StringLength(201)]
        public string EmployeeName { get; set; }
        public string ECode { get; set; }
        public DateTime AttendanceDate { get; set; }
        public TimeSpan PunchIn { get; set; }
        public TimeSpan PunchOut { get; set; }
        public bool IsRegularize { get; set; }
        public bool IsOnLeave { get; set; }
        public DateTime RegularizePunchIn { get; set; }
        public DateTime RegularizePunchOut { get; set; }
        public int? TotalWorkingMinutes { get; set; }
        [StringLength(15)]
        public string Status { get; set; }
    }
}
