// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class fn_GetMonthlyPunchesRange_productionnewnick_backup1Result
    {
        public int? EmpAttendanceId { get; set; }
        public long EmployeeId { get; set; }
        [StringLength(201)]
        public string EmployeeName { get; set; }
        [StringLength(20)]
        public string ECode { get; set; }
        public DateTime? AttendanceDate { get; set; }
        [StringLength(4000)]
        public string Machine_Type { get; set; }
        [StringLength(255)]
        public string DesignationName { get; set; }
        [StringLength(255)]
        public string LocationName { get; set; }
        [StringLength(10)]
        public string STCode { get; set; }
        [StringLength(255)]
        public string DepartmentName { get; set; }
        public int IsHoliday { get; set; }
        [StringLength(500)]
        public string HolidayName { get; set; }
        [StringLength(8)]
        public string Punch1 { get; set; }
        [StringLength(8)]
        public string Punch2 { get; set; }
        [StringLength(8)]
        public string Punch3 { get; set; }
        [StringLength(8)]
        public string Punch4 { get; set; }
        [StringLength(8)]
        public string Punch5 { get; set; }
        [StringLength(8)]
        public string Punch6 { get; set; }
        [StringLength(8)]
        public string Punch7 { get; set; }
        [StringLength(8)]
        public string Punch8 { get; set; }
        [StringLength(8)]
        public string Punch9 { get; set; }
        [StringLength(8)]
        public string Punch10 { get; set; }
        [StringLength(8)]
        public string Punch11 { get; set; }
        [StringLength(8)]
        public string Punch12 { get; set; }
        public TimeSpan PunchIn { get; set; }
        public TimeSpan PunchOut { get; set; }
        public int ValidPunchCount { get; set; }
        public TimeSpan RegularizePunchIn { get; set; }
        public TimeSpan RegularizePuncOut { get; set; }
        public bool IsRegularize { get; set; }
        public int IsOnLeave { get; set; }
        [StringLength(51)]
        public string TotalWorkingMinutes { get; set; }
        public int? LateMinutes { get; set; }
        public int? EarlyMinutes { get; set; }
        [StringLength(15)]
        public string Status { get; set; }
        public decimal? TotalWorkingDays { get; set; }
        [StringLength(51)]
        public string TotalMonthlyWorkingHours { get; set; }
    }
}
