// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class FNF_Deduction
{
    public long FNFId { get; set; }

    public long? EmployeeId { get; set; }

    public decimal? LoanBalance { get; set; }

    public decimal? AdvanceBalance { get; set; }

    public decimal? OtherDeduction1 { get; set; }

    public decimal? OtherDeduction2 { get; set; }

    public decimal? OtherDeduction3 { get; set; }

    public decimal? OtherDeduction4 { get; set; }

    public decimal? TotalPayable { get; set; }

    public decimal? TDS { get; set; }

    public decimal? NetPayable { get; set; }

    public decimal? DepositOn { get; set; }

    public virtual FNF_Header FNF { get; set; }
}