// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class FNF_Payment
{
    public long PaymentId { get; set; }

    public long FNFId { get; set; }

    public decimal? SendForPaymentAmount { get; set; }

    public string Remarks { get; set; }

    public string ChequeNo { get; set; }

    public DateTime? ChequeDate { get; set; }

    public string Status { get; set; }

    public decimal? AmountPaid { get; set; }

    public string PaymentVoucherNo { get; set; }

    public DateTime? CreatedOn { get; set; }

    public string CreatedBy { get; set; }

    public virtual FNF_Header FNF { get; set; }
}