// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class FNF_Header
{
    public long FNFId { get; set; }

    public long EmployeeId { get; set; }

    public DateTime? CreatedOn { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public string UpdatedBy { get; set; }

    public virtual FNF_Addition FNF_Addition { get; set; }

    public virtual FNF_Deduction FNF_Deduction { get; set; }

    public virtual ICollection<FNF_Payment> FNF_Payments { get; set; } = new List<FNF_Payment>();
}