// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class FNF_Addition
{
    public long FNFId { get; set; }

    public long? EmployeeId { get; set; }

    public DateTime? FNFDate { get; set; }

    public DateTime? DateOfLeaving { get; set; }

    public decimal? UnpaidSalaryAmount { get; set; }

    public decimal? Rate { get; set; }

    public int? Days { get; set; }

    public string SalaryMonth { get; set; }

    public decimal? Bonus { get; set; }

    public DateTime? BonusPeriodFrom { get; set; }

    public DateTime? BonusPeriodTill { get; set; }

    public decimal? Gratuity { get; set; }

    public string CalculatedAs { get; set; }

    public decimal? E_LeaveAmount { get; set; }

    public int? ELDays { get; set; }

    public decimal? NoticeSalary { get; set; }

    public decimal? OtherAddition1 { get; set; }

    public decimal? OtherAddition2 { get; set; }

    public decimal? OtherAddition3 { get; set; }

    public decimal? OtherAddition4 { get; set; }

    public virtual FNF_Header FNF { get; set; }
}