// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class GetApplicantByIdResult
    {
        public long ApplicantId { get; set; }
        public bool? IsApplicant { get; set; }
        [StringLength(2147483647)]
        public string FullName { get; set; }
        [StringLength(2147483647)]
        public string DesignationId { get; set; }
        [StringLength(2147483647)]
        public string LocationId { get; set; }
    }
}
