// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class GetAttendanceRecordsByEmployeeResult
    {
        public int Id { get; set; }
        public long EmployeeId { get; set; }
        public DateTime PunchTimeUtc { get; set; }
        public int PunchType { get; set; }
        [Column("Latitude", TypeName = "decimal(9,6)")]
        public decimal Latitude { get; set; }
        [Column("Longitude", TypeName = "decimal(9,6)")]
        public decimal Longitude { get; set; }
        public bool WithinGeofence { get; set; }
        [StringLength(100)]
        public string DeviceInfo { get; set; }
        [StringLength(45)]
        public string ClientIp { get; set; }
        public int StatusId { get; set; }
        [StringLength(50)]
        public string StatusName { get; set; }
        [StringLength(100)]
        public string LastUpdatedBy { get; set; }
        public DateTime? LastUpdatedOn { get; set; }
        [StringLength(1000)]
        public string Remarks { get; set; }
        [StringLength(1000)]
        public string Address { get; set; }
        [StringLength(1000)]
        public string ProofPath { get; set; }
    }
}
