// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class GETEMPBONUSLISTResult
    {
        [StringLength(20)]
        public string E_Code { get; set; }
        [StringLength(201)]
        public string FullName { get; set; }
        public DateTime? BonusDate { get; set; }
        [Column("Amount", TypeName = "decimal(18,2)")]
        public decimal Amount { get; set; }
        [StringLength(20)]
        public string Acc_Number { get; set; }
        [StringLength(50)]
        public string UTR { get; set; }
    }
}
