// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class GetEmployeeDetailsWithCards_Attendance_TestResult
    {
        public long Id { get; set; }
        [StringLength(50)]
        public string ZoneName { get; set; }
        [StringLength(50)]
        public string RegionName { get; set; }
        [StringLength(50)]
        public string ClusterName { get; set; }
        [StringLength(50)]
        public string STCode { get; set; }
        [StringLength(100)]
        public string LocationName { get; set; }
        [StringLength(50)]
        public string Ecode { get; set; }
        [StringLength(100)]
        public string FullName { get; set; }
        [StringLength(50)]
        public string Gender { get; set; }
        public DateTime? DOB { get; set; }
        [Column("AgeInYears", TypeName = "decimal(10,2)")]
        public decimal? AgeInYears { get; set; }
        public int? DepartmentId { get; set; }
        public int? DesignationId { get; set; }
        [StringLength(100)]
        public string DepartmentName { get; set; }
        [StringLength(100)]
        public string DesignationName { get; set; }
        public DateTime? DOJ { get; set; }
        [StringLength(200)]
        public string ResignationTypeName { get; set; }
        public DateTime? DateOfLeft { get; set; }
        [Column("BANK NAME")]
        [StringLength(200)]
        public string BANKNAME { get; set; }
        [Column("A/C NO")]
        [StringLength(50)]
        public string ACNO { get; set; }
        [Column("BANK IFSC CODE")]
        [StringLength(50)]
        public string BANKIFSCCODE { get; set; }
        [Column("PERMANENT ADDRESS")]
        [StringLength(500)]
        public string PERMANENTADDRESS { get; set; }
        [Column("PERMANENT ADDRESS PIN CODE")]
        [StringLength(20)]
        public string PERMANENTADDRESSPINCODE { get; set; }
        [Column("PRESENT ADDRESS")]
        [StringLength(500)]
        public string PRESENTADDRESS { get; set; }
        [Column("PRESENT ADDRESS PIN CODE")]
        [StringLength(20)]
        public string PRESENTADDRESSPINCODE { get; set; }
        [StringLength(50)]
        public string MOBILE { get; set; }
        [Column("EMAIL ADDRESS")]
        [StringLength(200)]
        public string EMAILADDRESS { get; set; }
        [Column("AADHAR NO")]
        [StringLength(50)]
        public string AADHARNO { get; set; }
        [Column("PAN NO")]
        [StringLength(50)]
        public string PANNO { get; set; }
        [Column("HIGHEST QUALIFICATION")]
        [StringLength(200)]
        public string HIGHESTQUALIFICATION { get; set; }
        [Column("FATHER'S NAME")]
        [StringLength(200)]
        public string FATHERSNAME { get; set; }
        [Column("MOTHER'S NAME")]
        [StringLength(200)]
        public string MOTHERSNAME { get; set; }
        [Column("MARITIAL STATUS")]
        [StringLength(50)]
        public string MARITIALSTATUS { get; set; }
        [StringLength(50)]
        public string ReportHeadEcode { get; set; }
        [StringLength(100)]
        public string ReportHeadFullName { get; set; }
        [StringLength(100)]
        public string ReportHeadDesignation { get; set; }
        [Column("COMPANY NAME-1")]
        [StringLength(300)]
        public string COMPANYNAME1 { get; set; }
        [Column("From-I")]
        [StringLength(10)]
        public string FromI { get; set; }
        [Column("To-I")]
        [StringLength(10)]
        public string ToI { get; set; }
        [Column("YEARS-1", TypeName = "decimal(10,2)")]
        public decimal? YEARS1 { get; set; }
        [Column("COMPANY NAME-2")]
        [StringLength(300)]
        public string COMPANYNAME2 { get; set; }
        [Column("From-II")]
        [StringLength(10)]
        public string FromII { get; set; }
        [Column("To-II")]
        [StringLength(10)]
        public string ToII { get; set; }
        [Column("YEARS-2", TypeName = "decimal(10,2)")]
        public decimal? YEARS2 { get; set; }
        [Column("COMPANY NAME-3")]
        [StringLength(300)]
        public string COMPANYNAME3 { get; set; }
        [Column("From-III")]
        [StringLength(10)]
        public string FromIII { get; set; }
        [Column("To-III")]
        [StringLength(10)]
        public string ToIII { get; set; }
        [Column("YEARS-3", TypeName = "decimal(10,2)")]
        public decimal? YEARS3 { get; set; }
        [Column("TTL EXPERIENCE", TypeName = "decimal(10,2)")]
        public decimal? TTLEXPERIENCE { get; set; }
        public bool? LocStatus { get; set; }
        [StringLength(100)]
        public string EmployeeStatus { get; set; }
        public long? EmployeeId { get; set; }
        public long? CandidateId { get; set; }
        [StringLength(100)]
        public string LocBasedECode { get; set; }
        public bool? IsActive { get; set; }
        public bool? IsDeleted { get; set; }
        public DateTime? DateOfJoining { get; set; }
        public bool? IsStore { get; set; }
        public DateTime? CreatedOn { get; set; }
        public DateTime? UpdatedOn { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [StringLength(50)]
        public string UpdatedBy { get; set; }
        public int? PresentDays { get; set; }
        public int? HalfDays { get; set; }
        public int? AbsentDays { get; set; }
        public int? LeaveDays { get; set; }
        public int? RegularisationDays { get; set; }
        [Column("TotalWorkingDays", TypeName = "decimal(10,2)")]
        public decimal? TotalWorkingDays { get; set; }
        public int? TotalCalendarRows { get; set; }
        public int? NonWorkingRows { get; set; }
        public int? MisPunchDays { get; set; }
        [StringLength(50)]
        public string TotalMonthlyWorkingHours { get; set; }
        public long? AttendanceCountApprovalId { get; set; }
        [StringLength(10)]
        public string ApprovalMonthYear { get; set; }
        public int? ApprovalAttendanceCount { get; set; }
        [StringLength(2147483647)]
        public string EmployeeRemarks { get; set; }
        [StringLength(50)]
        public string ApprovalStatus { get; set; }
        [StringLength(200)]
        public string ApprovalStatusDescription { get; set; }
        public bool? IsCMApproved { get; set; }
        [StringLength(50)]
        public string CMApprovedBy { get; set; }
        public DateTime? CMApprovedOn { get; set; }
        [StringLength(2147483647)]
        public string CMRemarks { get; set; }
        public bool? IsRMApproved { get; set; }
        [StringLength(50)]
        public string RMApprovedBy { get; set; }
        public DateTime? RMApprovedOn { get; set; }
        [StringLength(2147483647)]
        public string RMRemarks { get; set; }
        public int? AttachmentCount { get; set; }
        [StringLength(2147483647)]
        public string AttachmentFilePaths { get; set; }
        [Column("Month-Year")]
        [StringLength(100)]
        public string MonthYear { get; set; }
    }
}
