// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class GetEmployeeDetailsWithCardsResult
    {
        public long? EmployeeId { get; set; }
        public long? CandidateId { get; set; }
        [StringLength(100)]
        public string LocBasedECode { get; set; }
        [StringLength(100)]
        public string FullName { get; set; }
        [StringLength(100)]
        public string DepartmentName { get; set; }
        [StringLength(100)]
        public string DesignationName { get; set; }
        [StringLength(100)]
        public string LocationName { get; set; }
        [StringLength(50)]
        public string STCode { get; set; }
        [StringLength(50)]
        public string RegionName { get; set; }
        [StringLength(50)]
        public string ZoneName { get; set; }
        [StringLength(50)]
        public string ClusterName { get; set; }
        [StringLength(50)]
        public string Ecode { get; set; }
        [StringLength(50)]
        public string ReportHeadEcode { get; set; }
        public bool? IsActive { get; set; }
        public bool? IsDeleted { get; set; }
        public DateTime? DateOfJoining { get; set; }
        public bool? IsStore { get; set; }
        public DateTime? CreatedOn { get; set; }
        public DateTime? UpdatedOn { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [StringLength(50)]
        public string UpdatedBy { get; set; }
    }
}
