// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class GetHolidaysResult
    {
        public int Id { get; set; }
        public int? LocationType { get; set; }
        [StringLength(200)]
        public string LocationTypeName { get; set; }
        [StringLength(500)]
        public string LocationValue { get; set; }
        [StringLength(270)]
        public string LocationValueName { get; set; }
        [StringLength(500)]
        public string HolidayName { get; set; }
        public DateTime? HolidayDate { get; set; }
        public bool? IsActive { get; set; }
        public bool? IsDeleted { get; set; }
        public DateTime? CreatedOn { get; set; }
        [StringLength(100)]
        public string CreatedBy { get; set; }
        [StringLength(100)]
        public string UpdatedBy { get; set; }
        public DateTime? UpdatedOn { get; set; }
    }
}
