// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class GetLeaveRequestListResult
    {
        public long LeaveRequestId { get; set; }
        public long EmployeeId { get; set; }
        [StringLength(50)]
        public string EmployeeName { get; set; }
        [StringLength(20)]
        public string Ecode { get; set; }
        public int StatusId { get; set; }
        [StringLength(50)]
        public string StatusName { get; set; }
        public int LeaveTypeId { get; set; }
        [StringLength(100)]
        public string LeaveTypeName { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public long ReportingManagerId { get; set; }
        [StringLength(50)]
        public string ReportHeadName { get; set; }
        [StringLength(20)]
        public string ReportHeadEcode { get; set; }
        [StringLength(500)]
        public string Reason { get; set; }
        [StringLength(500)]
        public string Remarks { get; set; }
        public bool IsRevoked { get; set; }
        public DateTime? CreatedOn { get; set; }
        [StringLength(100)]
        public string CreatedBy { get; set; }
        public DateTime? UpdatedOn { get; set; }
        [StringLength(100)]
        public string LastUpdatedBy { get; set; }
        public bool FirstHalf { get; set; }
        public bool SecondHalf { get; set; }
        public bool FullDay { get; set; }
        [StringLength(255)]
        public string LocationName { get; set; }
        [StringLength(10)]
        public string STCode { get; set; }
        public int LocationId { get; set; }
        [StringLength(50)]
        public string RelieverName { get; set; }
        [StringLength(20)]
        public string RelieverEcode { get; set; }
    }
}
