// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class GetOfferletterOnMailResult
    {
        public long Id { get; set; }
        public long CId { get; set; }
        [StringLength(300)]
        public string FilePath { get; set; }
        [StringLength(30)]
        public string FileType { get; set; }
        [StringLength(50)]
        public string FileSize { get; set; }
        [StringLength(30)]
        public string CreatedBy { get; set; }
        [StringLength(30)]
        public string UpdatedBy { get; set; }
        [StringLength(30)]
        public string DeletedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public DateTime? UpdatedOn { get; set; }
        public DateTime? DeletedOn { get; set; }
        public bool? IsActive { get; set; }
        public bool? IsDeleted { get; set; }
    }
}
