// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class GetVendorListWithEmployeeCountResult
    {
        public long? VendorId { get; set; }
        [StringLength(200)]
        public string ContractorName { get; set; }
        [StringLength(50)]
        public string ContractorCode { get; set; }
        public DateTime? ContractStartDate { get; set; }
        public DateTime? ContractEndDate { get; set; }
        public int? EmployeeCount { get; set; }
    }
}
