// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class hhbh
{
    public string ecode { get; set; }

    public string ename { get; set; }

    public string Gender { get; set; }

    public string Location { get; set; }

    public string Desig { get; set; }

    public string Dept { get; set; }

    public string doj { get; set; }

    public string dol { get; set; }

    public string Column1 { get; set; }
}