// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class HR_DASHBOARD_DATum
{
    public int ID { get; set; }

    public string LOC_CD { get; set; }

    public string LOC_NM { get; set; }

    public string LOC_TYPE { get; set; }

    public int BGT_SEAT { get; set; }

    public int ACT_SEAT { get; set; }

    public int? GAP_SEAT { get; set; }

    public int? PR_TD { get; set; }

    public int? PR_MTD { get; set; }

    public int? AB_TD { get; set; }

    public int? AB_MTD { get; set; }

    public int? MP_TD { get; set; }

    public int? MP_MTD { get; set; }

    public int? VACANT_GEN_TD { get; set; }

    public int? VACANT_GEN_MTD { get; set; }

    public int? VACANT_GEN_TTL { get; set; }

    public int? APPLICANT_SCREEN_PEN_TD { get; set; }

    public int? APPLICANT_SCREEN_PEN_MTD { get; set; }

    public int? ON_HOLD_TD { get; set; }

    public int? ON_HOLD_MTD { get; set; }

    public int? REJ_NOT_INT_ID { get; set; }

    public int? REJ_NOT_INT_MID { get; set; }

    public int? SHORTLIST_TD { get; set; }

    public int? SHORTLIST_MTD { get; set; }

    public int INTERVIEW_SC_BGT_TD { get; set; }

    public int INTERVIEW_SC_ACT_TD { get; set; }

    public int? INTERVIEW_SC_GAP_TD { get; set; }

    public int INTERVIEW_SC_BGT_MTD { get; set; }

    public int INTERVIEW_SC_ACT_MTD { get; set; }

    public int? INTERVIEW_SC_GAP_MTD { get; set; }

    public int OFF_LET_BGT_TD { get; set; }

    public int OFF_LET_ACT_TD { get; set; }

    public int? OFF_LET_GAP_TD { get; set; }

    public int OFF_LET_BGT_MTD { get; set; }

    public int OFF_LET_ACT_MTD { get; set; }

    public int? OFF_LET_GAP_MTD { get; set; }

    public int ONBOARD_BGT_TD { get; set; }

    public int ONBOARD_ACT_TD { get; set; }

    public int? ONBOARD_GAP_TD { get; set; }

    public int ONBOARD_BGT_MTD { get; set; }

    public int ONBOARD_ACT_MTD { get; set; }

    public int? ONBOARD_GAP_MTD { get; set; }

    public int PF_R_BGT_TD { get; set; }

    public int PF_R_ACT_TD { get; set; }

    public int? PF_R_GAP_TD { get; set; }

    public int PF_R_BGT_MTD { get; set; }

    public int PF_R_ACT_MTD { get; set; }

    public int? PF_R_GAP_MTD { get; set; }

    public int ESIC_R_BGT_TD { get; set; }

    public int ESIC_R_ACT_TD { get; set; }

    public int? ESIC_R_GAP_TD { get; set; }

    public int ESIC_R_BGT_MTD { get; set; }

    public int ESIC_R_ACT_MTD { get; set; }

    public int? ESIC_R_GAP_MTD { get; set; }

    public int? RES_TD { get; set; }

    public int? RES_MTD { get; set; }

    public int RES_APP_BGT_TD { get; set; }

    public int RES_APP_ACT_TD { get; set; }

    public int? RES_APP_GAP_TD { get; set; }

    public int RES_APP_BGT_MTD { get; set; }

    public int RES_APP_ACT_MTD { get; set; }

    public int? RES_APP_GAP_MTD { get; set; }

    public int SEP_BGT_TD { get; set; }

    public int SEP_ACT_TD { get; set; }

    public int? SEP_GAP_TD { get; set; }

    public int SEP_BGT_MTD { get; set; }

    public int SEP_ACT_MTD { get; set; }

    public int? SEP_GAP_MTD { get; set; }

    public int? F_F_OPEN_PEND { get; set; }

    public int? F_F_TD { get; set; }

    public int? F_F_MTD { get; set; }

    public int? F_F_CLOSE_PEND { get; set; }

    public DateTime CREATE_DATE { get; set; }

    public DateTime? MODIFY_DATE { get; set; }
}