// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using HRMSAPI.Data;

namespace HRMSAPI.Data
{
    public partial class HRMSContext
    {

        [DbFunction("fn_CalculateGratuity", "dbo")]
        public static decimal? fn_CalculateGratuity(DateTime? DOJ, DateTime? DOL, string SalaryMonth, decimal? BasicSalary)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("fn_FormatIndianMoney", "dbo")]
        public static string fn_FormatIndianMoney(decimal? input)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("fn_GetEmployeeWeekOffs", "dbo")]
        public IQueryable<fn_GetEmployeeWeekOffsResult> fn_GetEmployeeWeekOffs(string Month)
        {
            return FromExpression(() => fn_GetEmployeeWeekOffs(Month));
        }

        [DbFunction("fn_GetEmployeeWeekOffsByEcode", "dbo")]
        public IQueryable<fn_GetEmployeeWeekOffsByEcodeResult> fn_GetEmployeeWeekOffsByEcode(string Month, string Ecode)
        {
            return FromExpression(() => fn_GetEmployeeWeekOffsByEcode(Month, Ecode));
        }

        [DbFunction("fn_GetMonthlyAttendance", "dbo")]
        public IQueryable<fn_GetMonthlyAttendanceResult> fn_GetMonthlyAttendance(int? Month, int? Year, string ECode)
        {
            return FromExpression(() => fn_GetMonthlyAttendance(Month, Year, ECode));
        }

        [DbFunction("fn_GetMonthlyAttendance_NEW", "dbo")]
        public IQueryable<fn_GetMonthlyAttendance_NEWResult> fn_GetMonthlyAttendance_NEW(int? Month, int? Year, string ECode)
        {
            return FromExpression(() => fn_GetMonthlyAttendance_NEW(Month, Year, ECode));
        }

        [DbFunction("fn_GetMonthlyPunches", "dbo")]
        public IQueryable<fn_GetMonthlyPunchesResult> fn_GetMonthlyPunches(int? Month, int? Year, string ECode)
        {
            return FromExpression(() => fn_GetMonthlyPunches(Month, Year, ECode));
        }

        [DbFunction("fn_GetMonthlyPunchesRange", "dbo")]
        public IQueryable<fn_GetMonthlyPunchesRangeResult> fn_GetMonthlyPunchesRange(DateTime? FromDate, DateTime? ToDate, string ECode)
        {
            return FromExpression(() => fn_GetMonthlyPunchesRange(FromDate, ToDate, ECode));
        }

        [DbFunction("fn_GetMonthlyPunchesRange_new", "dbo")]
        public IQueryable<fn_GetMonthlyPunchesRange_newResult> fn_GetMonthlyPunchesRange_new(DateTime? FromDate, DateTime? ToDate, string ECode)
        {
            return FromExpression(() => fn_GetMonthlyPunchesRange_new(FromDate, ToDate, ECode));
        }

        [DbFunction("fn_GetMonthlyPunchesRange_nik1", "dbo")]
        public IQueryable<fn_GetMonthlyPunchesRange_nik1Result> fn_GetMonthlyPunchesRange_nik1(DateTime? FromDate, DateTime? ToDate, string ECode)
        {
            return FromExpression(() => fn_GetMonthlyPunchesRange_nik1(FromDate, ToDate, ECode));
        }

        [DbFunction("fn_GetMonthlyPunchesRange_production", "dbo")]
        public IQueryable<fn_GetMonthlyPunchesRange_productionResult> fn_GetMonthlyPunchesRange_production(DateTime? FromDate, DateTime? ToDate, string ECode)
        {
            return FromExpression(() => fn_GetMonthlyPunchesRange_production(FromDate, ToDate, ECode));
        }

        [DbFunction("fn_GetMonthlyPunchesRange_productionnew", "dbo")]
        public IQueryable<fn_GetMonthlyPunchesRange_productionnewResult> fn_GetMonthlyPunchesRange_productionnew(DateTime? FromDate, DateTime? ToDate, string ECode)
        {
            return FromExpression(() => fn_GetMonthlyPunchesRange_productionnew(FromDate, ToDate, ECode));
        }

        [DbFunction("fn_GetMonthlyPunchesRange_productionnewnick_backup1", "dbo")]
        public IQueryable<fn_GetMonthlyPunchesRange_productionnewnick_backup1Result> fn_GetMonthlyPunchesRange_productionnewnick_backup1(DateTime? FromDate, DateTime? ToDate, string ECode)
        {
            return FromExpression(() => fn_GetMonthlyPunchesRange_productionnewnick_backup1(FromDate, ToDate, ECode));
        }

        [DbFunction("fn_GetMonthlyPunchesRange_productionnewnick_latest", "dbo")]
        public IQueryable<fn_GetMonthlyPunchesRange_productionnewnick_latestResult> fn_GetMonthlyPunchesRange_productionnewnick_latest(DateTime? FromDate, DateTime? ToDate, string ECode)
        {
            return FromExpression(() => fn_GetMonthlyPunchesRange_productionnewnick_latest(FromDate, ToDate, ECode));
        }

        [DbFunction("fn_GetMonthlyPunchesRange_productionnewnick_latest_backup", "dbo")]
        public IQueryable<fn_GetMonthlyPunchesRange_productionnewnick_latest_backupResult> fn_GetMonthlyPunchesRange_productionnewnick_latest_backup(DateTime? FromDate, DateTime? ToDate, string ECode)
        {
            return FromExpression(() => fn_GetMonthlyPunchesRange_productionnewnick_latest_backup(FromDate, ToDate, ECode));
        }

        [DbFunction("fn_GetMonthlyPunchesRange_productionnewnick_latest_shift", "dbo")]
        public IQueryable<fn_GetMonthlyPunchesRange_productionnewnick_latest_shiftResult> fn_GetMonthlyPunchesRange_productionnewnick_latest_shift(DateTime? FromDate, DateTime? ToDate, string ECode)
        {
            return FromExpression(() => fn_GetMonthlyPunchesRange_productionnewnick_latest_shift(FromDate, ToDate, ECode));
        }

        [DbFunction("fn_GetMonthlyPunchesRange_productionnewnick_latestnick", "dbo")]
        public IQueryable<fn_GetMonthlyPunchesRange_productionnewnick_latestnickResult> fn_GetMonthlyPunchesRange_productionnewnick_latestnick(DateTime? FromDate, DateTime? ToDate, string ECode)
        {
            return FromExpression(() => fn_GetMonthlyPunchesRange_productionnewnick_latestnick(FromDate, ToDate, ECode));
        }

        [DbFunction("fn_GetMonthlyPunchesRange_productionnewnick_live", "dbo")]
        public IQueryable<fn_GetMonthlyPunchesRange_productionnewnick_liveResult> fn_GetMonthlyPunchesRange_productionnewnick_live(DateTime? FromDate, DateTime? ToDate, string ECode)
        {
            return FromExpression(() => fn_GetMonthlyPunchesRange_productionnewnick_live(FromDate, ToDate, ECode));
        }

        [DbFunction("fn_GetMonthlyPunchesRange_productionnewnick_temp1", "dbo")]
        public IQueryable<fn_GetMonthlyPunchesRange_productionnewnick_temp1Result> fn_GetMonthlyPunchesRange_productionnewnick_temp1(DateTime? FromDate, DateTime? ToDate, string ECode)
        {
            return FromExpression(() => fn_GetMonthlyPunchesRange_productionnewnick_temp1(FromDate, ToDate, ECode));
        }

        [DbFunction("fn_GetMonthlyPunchesRange_productionnewnick_test_nik", "dbo")]
        public IQueryable<fn_GetMonthlyPunchesRange_productionnewnick_test_nikResult> fn_GetMonthlyPunchesRange_productionnewnick_test_nik(DateTime? FromDate, DateTime? ToDate, string ECode)
        {
            return FromExpression(() => fn_GetMonthlyPunchesRange_productionnewnick_test_nik(FromDate, ToDate, ECode));
        }

        [DbFunction("fn_GetMonthlyPunchesRange_productionnewnick_test_test", "dbo")]
        public IQueryable<fn_GetMonthlyPunchesRange_productionnewnick_test_testResult> fn_GetMonthlyPunchesRange_productionnewnick_test_test(DateTime? FromDate, DateTime? ToDate, string ECode)
        {
            return FromExpression(() => fn_GetMonthlyPunchesRange_productionnewnick_test_test(FromDate, ToDate, ECode));
        }

        [DbFunction("fn_GetMonthlyPunchesRange_productionnewnick_test1", "dbo")]
        public IQueryable<fn_GetMonthlyPunchesRange_productionnewnick_test1Result> fn_GetMonthlyPunchesRange_productionnewnick_test1(DateTime? FromDate, DateTime? ToDate, string ECode)
        {
            return FromExpression(() => fn_GetMonthlyPunchesRange_productionnewnick_test1(FromDate, ToDate, ECode));
        }

        [DbFunction("fn_GetMonthlyPunchesRange_productionnewnick1", "dbo")]
        public IQueryable<fn_GetMonthlyPunchesRange_productionnewnick1Result> fn_GetMonthlyPunchesRange_productionnewnick1(DateTime? FromDate, DateTime? ToDate, string ECode)
        {
            return FromExpression(() => fn_GetMonthlyPunchesRange_productionnewnick1(FromDate, ToDate, ECode));
        }

        [DbFunction("fn_GetMonthlyPunchesRange_productionnewnickishu", "dbo")]
        public IQueryable<fn_GetMonthlyPunchesRange_productionnewnickishuResult> fn_GetMonthlyPunchesRange_productionnewnickishu(DateTime? FromDate, DateTime? ToDate, string ECode)
        {
            return FromExpression(() => fn_GetMonthlyPunchesRange_productionnewnickishu(FromDate, ToDate, ECode));
        }

        [DbFunction("fn_GetMonthPortion", "dbo")]
        public static decimal? fn_GetMonthPortion(DateTime? DOJ, DateTime? DOL, string SalaryMonth)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("fn_GetRbacHierarchyByRole", "dbo")]
        public IQueryable<fn_GetRbacHierarchyByRoleResult> fn_GetRbacHierarchyByRole(int? RoleId)
        {
            return FromExpression(() => fn_GetRbacHierarchyByRole(RoleId));
        }

        [DbFunction("fn_IsVacancyShorter", "dbo")]
        public static bool? fn_IsVacancyShorter(int? LocId, int? DeptId, int? DesigId, decimal? Salary)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("fn_IsVacancyShorterForEmployee", "dbo")]
        public static bool? fn_IsVacancyShorterForEmployee(int? LocId, int? DeptId, int? DesigId, decimal? Salary)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("SatCountFromMonth", "dbo")]
        public static int? SatCountFromMonth(string MonthYear, DateTime? CycleStart, DateTime? CycleEnd)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("ufn_CalcLWPExtra", "dbo")]
        public IQueryable<ufn_CalcLWPExtraResult> ufn_CalcLWPExtra(int? AbsentDays, int? LeaveUsed, int? ExtraDays)
        {
            return FromExpression(() => ufn_CalcLWPExtra(AbsentDays, LeaveUsed, ExtraDays));
        }

        [DbFunction("ufn_DeptState", "dbo")]
        public IQueryable<ufn_DeptStateResult> ufn_DeptState(string ECode, string StCode)
        {
            return FromExpression(() => ufn_DeptState(ECode, StCode));
        }

        [DbFunction("ufn_DesigState", "dbo")]
        public IQueryable<ufn_DesigStateResult> ufn_DesigState(string ECode, string StCode, string DeptId)
        {
            return FromExpression(() => ufn_DesigState(ECode, StCode, DeptId));
        }

        [DbFunction("ufn_GetDesignations", "dbo")]
        public IQueryable<ufn_GetDesignationsResult> ufn_GetDesignations(int? DeptId)
        {
            return FromExpression(() => ufn_GetDesignations(DeptId));
        }

        [DbFunction("ufn_GetEmpAttendanceSnapshot", "dbo")]
        public IQueryable<ufn_GetEmpAttendanceSnapshotResult> ufn_GetEmpAttendanceSnapshot(string Ecode, string Month, int? BatchNo)
        {
            return FromExpression(() => ufn_GetEmpAttendanceSnapshot(Ecode, Month, BatchNo));
        }

        [DbFunction("ufn_GetEmpHolidayCounts_ForMonth", "dbo")]
        public IQueryable<ufn_GetEmpHolidayCounts_ForMonthResult> ufn_GetEmpHolidayCounts_ForMonth(string Ecode, string Month, DateTime? CycleStart, DateTime? CycleEnd)
        {
            return FromExpression(() => ufn_GetEmpHolidayCounts_ForMonth(Ecode, Month, CycleStart, CycleEnd));
        }

        [DbFunction("ufn_GetSaturdayCountToEOM", "dbo")]
        public static int? ufn_GetSaturdayCountToEOM(DateTime? StartDate)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("ufn_GetSaturdaysForMonth", "dbo")]
        public static int? ufn_GetSaturdaysForMonth(DateTime? DOJ, string Month)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("ufn_IsSalaryAboveMinWage", "dbo")]
        public static bool? ufn_IsSalaryAboveMinWage(string STCode, decimal? Salary)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("ufn_StoreState", "dbo")]
        public IQueryable<ufn_StoreStateResult> ufn_StoreState(string ECode)
        {
            return FromExpression(() => ufn_StoreState(ECode));
        }

        [DbFunction("WeekendCountFromMonth", "dbo")]
        public static int? WeekendCountFromMonth(string MonthYear, DateTime? CycleStart, DateTime? CycleEnd)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<fn_GetEmployeeWeekOffsResult>().HasNoKey();
            modelBuilder.Entity<fn_GetEmployeeWeekOffsByEcodeResult>().HasNoKey();
            modelBuilder.Entity<fn_GetMonthlyAttendanceResult>().HasNoKey();
            modelBuilder.Entity<fn_GetMonthlyAttendance_NEWResult>().HasNoKey();
            modelBuilder.Entity<fn_GetMonthlyPunchesResult>().HasNoKey();
            modelBuilder.Entity<fn_GetMonthlyPunchesRangeResult>().HasNoKey();
            modelBuilder.Entity<fn_GetMonthlyPunchesRange_newResult>().HasNoKey();
            modelBuilder.Entity<fn_GetMonthlyPunchesRange_nik1Result>().HasNoKey();
            modelBuilder.Entity<fn_GetMonthlyPunchesRange_productionResult>().HasNoKey();
            modelBuilder.Entity<fn_GetMonthlyPunchesRange_productionnewResult>().HasNoKey();
            modelBuilder.Entity<fn_GetMonthlyPunchesRange_productionnewnick_backup1Result>().HasNoKey();
            modelBuilder.Entity<fn_GetMonthlyPunchesRange_productionnewnick_latestResult>().HasNoKey();
            modelBuilder.Entity<fn_GetMonthlyPunchesRange_productionnewnick_latest_backupResult>().HasNoKey();
            modelBuilder.Entity<fn_GetMonthlyPunchesRange_productionnewnick_latest_shiftResult>().HasNoKey();
            modelBuilder.Entity<fn_GetMonthlyPunchesRange_productionnewnick_latestnickResult>().HasNoKey();
            modelBuilder.Entity<fn_GetMonthlyPunchesRange_productionnewnick_liveResult>().HasNoKey();
            modelBuilder.Entity<fn_GetMonthlyPunchesRange_productionnewnick_temp1Result>().HasNoKey();
            modelBuilder.Entity<fn_GetMonthlyPunchesRange_productionnewnick_test_nikResult>().HasNoKey();
            modelBuilder.Entity<fn_GetMonthlyPunchesRange_productionnewnick_test_testResult>().HasNoKey();
            modelBuilder.Entity<fn_GetMonthlyPunchesRange_productionnewnick_test1Result>().HasNoKey();
            modelBuilder.Entity<fn_GetMonthlyPunchesRange_productionnewnick1Result>().HasNoKey();
            modelBuilder.Entity<fn_GetMonthlyPunchesRange_productionnewnickishuResult>().HasNoKey();
            modelBuilder.Entity<fn_GetRbacHierarchyByRoleResult>().HasNoKey();
            modelBuilder.Entity<ufn_CalcLWPExtraResult>().HasNoKey();
            modelBuilder.Entity<ufn_DeptStateResult>().HasNoKey();
            modelBuilder.Entity<ufn_DesigStateResult>().HasNoKey();
            modelBuilder.Entity<ufn_GetDesignationsResult>().HasNoKey();
            modelBuilder.Entity<ufn_GetEmpAttendanceSnapshotResult>().HasNoKey();
            modelBuilder.Entity<ufn_GetEmpHolidayCounts_ForMonthResult>().HasNoKey();
            modelBuilder.Entity<ufn_StoreStateResult>().HasNoKey();
        }
    }
}
