// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class InsuranceEnrollment
{
    public string NameofInsured { get; set; }

    public string EmployeeId { get; set; }

    public string Relation { get; set; }

    public string Gender { get; set; }

    public DateTime? DateOfBirth { get; set; }

    public DateTime? DateOfJoin { get; set; }

    public decimal? GrossSalary { get; set; }

    public int ID { get; set; }

    public DateTime creadedon { get; set; }
}