// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class InterviewApprovalLog
{
    public int LogId { get; set; }

    public long InterviewerId { get; set; }

    public int ScheduleId { get; set; }

    public int RoundId { get; set; }

    public string ApprovedBy { get; set; }

    public DateTime ApprovalDate { get; set; }

    public string Feedback { get; set; }

    public string Status { get; set; }
}