// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class InterviewBackgroundProcess
{
    public int Id { get; set; }

    public long? CandidateId { get; set; }

    public string Status { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedOn { get; set; }

    public string Remarks { get; set; }

    public string LastUpdated { get; set; }

    public DateTime? LastUpdatedOn { get; set; }

    public virtual Candidate Candidate { get; set; }
}