// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class JD
{
    public int JDId { get; set; }

    public int DesignationId { get; set; }

    public string KeyResponsibility { get; set; }

    public string KeySkills { get; set; }

    public virtual tblDesignation Designation { get; set; }
}