// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class latest_emp_stcd_20250613
{
    public string Employee_Code { get; set; }

    public string Scode { get; set; }
}