// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class LeavingEmployee
{
    public string Ecode { get; set; }

    public DateTime? LeavingDate { get; set; }

    public DateTime? CreatedOn { get; set; }
}