// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class LocationDesignationWeeklyOffHolidayMaster
{
    public int LocationDesignationWeeklyOffHolidayMasterId { get; set; }

    public string Month { get; set; }

    public int? DesignationID { get; set; }

    public decimal? BudgetWeeklyOff { get; set; }

    public decimal? BudgetHoliday { get; set; }

    public int LocationCategoryId { get; set; }
}