// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class LocationAssignmentNode
{
    public int Id { get; set; }

    public string ECode { get; set; }

    public string NodeType { get; set; }

    public int RefId { get; set; }

    public int? ParentNodeId { get; set; }

    public bool IsChecked { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedOn { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime? UpdatedOn { get; set; }
}