// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class LocationMaster
{
    public string STCode { get; set; }

    public string LocationName { get; set; }

    public string ZoneName { get; set; }

    public string RegionName { get; set; }

    public string ClusterName { get; set; }

    public string StateName { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsDeleted { get; set; }

    public string OpeningDate { get; set; }

    public int LocationId { get; set; }
}