// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class LocationCategory
{
    public int LocationCategoryId { get; set; }

    public string LocationCategoryName { get; set; }

    public virtual ICollection<tblEmployeeAttendancePayrollCalculation> tblEmployeeAttendancePayrollCalculations { get; set; } = new List<tblEmployeeAttendancePayrollCalculation>();
}