// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class LoginHistory
{
    public int Id { get; set; }

    public string Username { get; set; }

    public string IpAddress { get; set; }

    public string UserAgent { get; set; }

    public bool? Success { get; set; }

    public string Message { get; set; }

    public DateTime? LoginTime { get; set; }

    public long? EmployeeId { get; set; }

    public string Role { get; set; }
}