// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class LWFPolicyMaster
{
    public string State { get; set; }

    public string Frequency { get; set; }

    public decimal? Employee { get; set; }

    public decimal? EmployeeMax { get; set; }

    public decimal? Employeer { get; set; }

    public decimal? EmployeerMax { get; set; }

    public int Id { get; set; }
}