// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class LWFPolicyMaster
{
    public string State { get; set; }

    public string Frequency { get; set; }

    public decimal? Employee { get; set; }

    public decimal? EmployeeMax { get; set; }

    public decimal? Employeer { get; set; }

    public decimal? EmployeerMax { get; set; }

    // "Flat" (rupee amount) or "Percent" (percentage of gross, capped by the Max
    // columns). Added 2026-08-26 so the LWF policy page can express Haryana's
    // 0.2%/0.4% rule instead of it being hardcoded in the payroll proc.
    public string CalcType { get; set; }

    public int Id { get; set; }
}