// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class MapNewDeptDesig
{
    public string Ecode { get; set; }

    public string DEPT { get; set; }

    public string DESG { get; set; }

    public DateTime? CreatedOn { get; set; }
}