// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class MarketingEmpChecklist
{
    public int id { get; set; }

    public string E_Code { get; set; }

    public bool? V2parivar { get; set; }

    public bool? Submitted { get; set; }

    public bool? R_removed { get; set; }

    public bool? Email_Inactive { get; set; }

    public bool? Assets_Received { get; set; }

    public bool? Attendance_updated { get; set; }

    public string createdBy { get; set; }

    public DateTime? createdOn { get; set; }

    public string updatedBy { get; set; }

    public DateTime? updatedOn { get; set; }

    public bool? isactive { get; set; }

    public bool? isdeleted { get; set; }
}