// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class monthlytempdec_25
{
    public int Id { get; set; }

    public string E_CODE { get; set; }

    public string MONTH { get; set; }

    public decimal? MACHINE { get; set; }

    public decimal? MANUAL { get; set; }

    public decimal? GF { get; set; }

    public decimal? TOTAL_PRESENT { get; set; }

    public decimal? NC_TOTAL_PRESENT { get; set; }

    public decimal? PRESENT_ON_WEEKLYOFF { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsDeleted { get; set; }

    public DateTime? CreatedOn { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public string STCode { get; set; }

    public string DesignationName { get; set; }
}