// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class MonthWeekwiseAttendance
{
    public int? Year { get; set; }

    public string MonthName { get; set; }

    public int? TotalAttendance { get; set; }

    public int? WeeklyOff { get; set; }

    public int? WeekRow { get; set; }

    public string OffPolicy { get; set; }

    public DateTime? WeekStart { get; set; }

    public DateTime? WeekEnd { get; set; }

    public DateTime? InsertedOn { get; set; }
}