// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class Net_Payble_Download
{
    public string Ecode { get; set; }

    public string Location_Code { get; set; }

    public string Location_Name { get; set; }

    public string Employee_Name { get; set; }

    public string designation { get; set; }

    public string department { get; set; }

    public string Month_Year { get; set; }

    public decimal? Bgt_Salary { get; set; }

    public decimal Gross_Earnings { get; set; }

    public decimal? Additions { get; set; }

    public decimal? Deductions { get; set; }

    public decimal? Reimbersment { get; set; }

    public decimal Net_Payble_After_Deduction_with_Addition_ { get; set; }

    public decimal? Net_Payble_Without_Reimbersment_ { get; set; }

    public string LocBasedECode { get; set; }

    public string GENDER { get; set; }

    public DateTime? JOINING_DATE { get; set; }

    public string MOBILE_NO_ { get; set; }

    public DateTime? LEAVING_DT { get; set; }

    public string STATUS { get; set; }

    public string BANK_NAME { get; set; }

    public string BANK_IFSC_CODE { get; set; }

    public string A_C_NO { get; set; }

    public string UAN_NO { get; set; }

    public string P_F__No_ { get; set; }

    public string ESICNO { get; set; }

    public string PAN_NO { get; set; }

    public string AADHAR_NO { get; set; }

    public bool? PFApplicable { get; set; }

    public bool? ESICApplicable { get; set; }

    public string F_P_F__Applicable_ { get; set; }

    public string O_T__Applicable_ { get; set; }

    public string P_Tax_Applicable_ { get; set; }

    public string Bonus_Applicable_ { get; set; }

    public string WK_OFF_PAY_APPLICABLE_ { get; set; }
}