// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class Net_Payble_Batch
{
    public string UniqueId { get; set; }

    public string Ecode { get; set; }

    public string Location_Code { get; set; }

    public string Location_Name { get; set; }

    public string Employee_Name { get; set; }

    public string designation { get; set; }

    public string department { get; set; }

    public string Month_Year { get; set; }

    public decimal? Bgt_Salary { get; set; }

    public decimal Gross_Earnings { get; set; }

    public decimal? Additions { get; set; }

    public decimal? Deductions { get; set; }

    public decimal? Reimbersment { get; set; }

    public decimal Net_Payble_After_Deduction_with_Addition_ { get; set; }

    public decimal? Net_Payble_Without_Reimbersment_ { get; set; }

    public DateTime RunAt { get; set; }

    public int? BatchNo { get; set; }
}