// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class NewDeptDesig
{
    public string Ecode { get; set; }

    public string Department { get; set; }

    public string UPDATED_DEPT { get; set; }

    public string Designation { get; set; }

    public string UPDATED_DESGN { get; set; }

    public DateTime? CreatedOn { get; set; }
}