// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class newemployeemastertemp1
{
    public string Employee_Code { get; set; }

    public string Name_of_Employee { get; set; }

    public string Posted_Location { get; set; }

    public string Joined_Location { get; set; }

    public string Sex { get; set; }

    public string D_O_B_ { get; set; }

    public string Department { get; set; }

    public string Designation { get; set; }

    public string Home_Town { get; set; }

    public string Sal_Structure { get; set; }

    public string D_O_J_ { get; set; }

    public string D_O_J_Group { get; set; }

    public string D_O_L_ { get; set; }

    public string Joining_Salary { get; set; }

    public string P_F__Applicable_ { get; set; }

    public string P_F__Code_ { get; set; }

    public string P_F__No_ { get; set; }

    public string Previous_P_F__No_ { get; set; }

    public string E_S_I__Applicable_ { get; set; }

    public string E_S_I__No_ { get; set; }

    public string Universal_A_c_Number { get; set; }

    public string Basic_Salary { get; set; }

    public string D_A_ { get; set; }

    public string H_R_A_ { get; set; }

    public string C_C_A_ { get; set; }

    public string Conveyance { get; set; }

    public string Medical_Allow { get; set; }

    public string Incentive { get; set; }

    public string Special_Allow { get; set; }

    public string Extra_Allow { get; set; }

    public string Leave_Encashment { get; set; }

    public string Lta { get; set; }

    public string Bonus_Ex_Gratia { get; set; }

    public string Cca { get; set; }

    public string Advance { get; set; }

    public string Fooding_Allow { get; set; }

    public string Ptax { get; set; }

    public string Lwf { get; set; }

    public string Tds { get; set; }

    public string Esi { get; set; }

    public string Recovery { get; set; }

    public string Penalty { get; set; }

    public string Medical { get; set; }

    public string Fuel___Maintenance { get; set; }

    public string Books___Periodicals { get; set; }

    public string Professional_Attire { get; set; }

    public string Driver_Wages { get; set; }

    public string Mobile { get; set; }

    public string Meal_Voucher { get; set; }

    public string Gross_Salary { get; set; }

    public string Employeer_PF { get; set; }

    public string Employeer_ESI { get; set; }

    public string AC_NO_2 { get; set; }

    public string AC_NO_21 { get; set; }

    public string GRATITY { get; set; }

    public string MONTHLY_CTC_ { get; set; }

    public string T_D_S_ { get; set; }

    public string Payment_Mode { get; set; }

    public string A_c_No_ { get; set; }

    public string Name_of_Bank { get; set; }

    public string IFSC_Code { get; set; }

    public string Permanent_Addess { get; set; }

    public string Present_Address { get; set; }

    public string Mob_No_ { get; set; }

    public string Phone_No_ { get; set; }

    public string Email_Id { get; set; }

    public string Aadhar_No_ { get; set; }

    public string PAN_No_ { get; set; }

    public string Passport_No_ { get; set; }

    public string Qualification { get; set; }

    public string Father_s_Name { get; set; }

    public string FATHER_DOB { get; set; }

    public string Mothers_Name { get; set; }

    public string Relation { get; set; }

    public string MOTHER_DOB { get; set; }

    public string Marital_Status { get; set; }

    public string SPOUSE_DOB { get; set; }

    public string CHILD_NAME { get; set; }

    public string Relation_1 { get; set; }

    public string CHILD_DOB { get; set; }

    public string CHILD_NAME_1 { get; set; }

    public string Relation_2 { get; set; }

    public string CHILD_DOB_1 { get; set; }

    public string LIC_No_ { get; set; }

    public string P_A_policy_no_ { get; set; }

    public string Mediclaim_No_ { get; set; }

    public string Fooding_Details { get; set; }

    public string Accomodation_Details { get; set; }

    public string Desig__Band { get; set; }

    public string Annual_Gross { get; set; }

    public string Annual_CTC { get; set; }

    public string Hold_Salary__ { get; set; }

    public string Hold_Reason_Remark { get; set; }

    public string Reimbursement_A_c_No_ { get; set; }

    public string Reimbursement_Bank { get; set; }

    public string Resignation_Date { get; set; }

    public string Notice_Days { get; set; }

    public string Date_of_Confirmation { get; set; }

    public string Gross_Salary_1 { get; set; }

    public string Company { get; set; }

    public string Branch { get; set; }

    public string Employee_Status { get; set; }

    public string Transfer_Reason { get; set; }

    public string Transfer_Date { get; set; }

    public string trfremark { get; set; }

    public string senior { get; set; }

    public string junior { get; set; }

    public string icustomer { get; set; }

    public string hod { get; set; }

    public string rmanager { get; set; }

    public string jbname { get; set; }

    public string jobprofile { get; set; }

    public string subdesig { get; set; }

    public string sdsgrade { get; set; }

    public string states { get; set; }
}