// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class NewEmpUpdare
{
    public int ID { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }

    public string ECode { get; set; }

    public DateTime? CreatedOn { get; set; }
}