// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class OfferLetterEmailStatus
{
    public int Id { get; set; }

    public int? ApplicantId { get; set; }

    public string Email { get; set; }

    public bool? IsSent { get; set; }

    public string ErrorMessage { get; set; }

    public DateTime? SentOn { get; set; }
}