// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class PAN_INDIA_OTHER_RM_APPROVED_CASES_csvsheet
{
    public string ZONE { get; set; }

    public string REGION { get; set; }

    public string STcode { get; set; }

    public string St_NAME { get; set; }

    public string E_CODE { get; set; }

    public string employee_NAME { get; set; }

    public string department { get; set; }

    public string DATE { get; set; }

    public string Punch_In { get; set; }

    public string Punch_Out { get; set; }

    public string EMP__RAISED_REQUEST { get; set; }

    public string manager_Approve { get; set; }

    public string audit_lp__Approve { get; set; }

    public string Column14 { get; set; }
}