// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class PaybleDays_Download
{
    public string Ecode { get; set; }

    public string STCode { get; set; }

    public string LocationName { get; set; }

    public string FULL_NAME { get; set; }

    public string DepartmentName { get; set; }

    public string DesignationName { get; set; }

    public string Month { get; set; }

    public decimal? TotalDaysInMonth { get; set; }

    public decimal? Attendance { get; set; }

    public decimal? Actual_Weekly_Off { get; set; }

    public decimal? weeklyoffpresent { get; set; }

    public decimal? leave_availed { get; set; }

    public decimal? Payble_Days { get; set; }

    public decimal? EXTRA_DAYS { get; set; }

    public decimal? Absent { get; set; }

    public string LocBasedECode { get; set; }

    public string GENDER { get; set; }

    public DateTime? JOINING_DATE { get; set; }

    public string MOBILE_NO_ { get; set; }

    public DateTime? LEAVING_DT { get; set; }

    public string STATUS { get; set; }

    public string BANK_NAME { get; set; }

    public string BANK_IFSC_CODE { get; set; }

    public string A_C_NO { get; set; }

    public string UAN_NO { get; set; }

    public string P_F__No_ { get; set; }

    public string ESICNO { get; set; }

    public string PAN_NO { get; set; }

    public string AADHAR_NO { get; set; }

    public bool? PFApplicable { get; set; }

    public bool? ESICApplicable { get; set; }

    public string F_P_F__Applicable_ { get; set; }

    public string O_T__Applicable_ { get; set; }

    public string P_Tax_Applicable_ { get; set; }

    public string Bonus_Applicable_ { get; set; }

    public string WK_OFF_PAY_APPLICABLE_ { get; set; }
}