// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class PaybleDay
{
    public string Ecode { get; set; }

    public string STCode { get; set; }

    public string LocationName { get; set; }

    public string FULL_NAME { get; set; }

    public string DepartmentName { get; set; }

    public string DesignationName { get; set; }

    public string Month { get; set; }

    public decimal? TotalDaysInMonth { get; set; }

    public decimal? Attendance { get; set; }

    public decimal? Actual_Weekly_Off { get; set; }

    public decimal? weeklyoffpresent { get; set; }

    public decimal? leave_availed { get; set; }

    public decimal? Payble_Days { get; set; }

    public decimal? EXTRA_DAYS { get; set; }

    public decimal? Absent { get; set; }
}