// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class prc_GetEmployeeWeekOffsResult
    {
        [StringLength(20)]
        public string Ecode { get; set; }
        public DateTime? DOJ { get; set; }
        public int? LocationId { get; set; }
        public int? EmpDesignationId { get; set; }
        public DateTime? Calc { get; set; }
        [StringLength(10)]
        public string STCode { get; set; }
        public DateTime? IF_Joining_Date { get; set; }
        [StringLength(10)]
        public string LocationCode { get; set; }
        public int? BudgetDesignationId { get; set; }
        public int? AllowedSaturdays { get; set; }
        public int? AllowedSundays { get; set; }
        public int? TotalWeekOffs { get; set; }
    }
}
