// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class prc_runecode_iterate_DailyResult
    {
        [StringLength(20)]
        public string EMPID { get; set; }
        [StringLength(7)]
        public string MONTH { get; set; }
    }
}
