// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class proc_BGTSEATMASTERResult
    {
        [StringLength(50)]
        public string STCode { get; set; }
        public int? DepartmentId { get; set; }
        [StringLength(255)]
        public string DepartmentName { get; set; }
        public int? DesignationId { get; set; }
        [StringLength(255)]
        public string DesignationName { get; set; }
        [StringLength(50)]
        public string SeatOrStatus { get; set; }
        [Column("SALARY_BGT", TypeName = "decimal(18,2)")]
        public decimal? SALARY_BGT { get; set; }
        [Column("ActualSalary", TypeName = "decimal(18,2)")]
        public decimal? ActualSalary { get; set; }
        [StringLength(20)]
        public string Ecode { get; set; }
        [StringLength(50)]
        public string FullName { get; set; }
        [StringLength(20)]
        public string ReportEcode { get; set; }
        [StringLength(50)]
        public string ReportFullName { get; set; }
        [StringLength(255)]
        public string BGTReportingDesig { get; set; }
        [StringLength(255)]
        public string ActualReportingDesig { get; set; }
        public bool? ACTIVE { get; set; }
        public bool? StoreStatus { get; set; }
        [StringLength(255)]
        public string LocationName { get; set; }
        [StringLength(4000)]
        public string OpeningDate { get; set; }
    }
}
