// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class proc_OpeningsResult
    {
        [StringLength(50)]
        public string LOC_CODE { get; set; }
        [StringLength(307)]
        public string Location { get; set; }
        public int? DepartmentId { get; set; }
        [StringLength(255)]
        public string DepartmentName { get; set; }
        public int? DesignationId { get; set; }
        [StringLength(255)]
        public string DesignationName { get; set; }
        public int? SeatBudget { get; set; }
        public int EmpCount { get; set; }
        public int? Vacancy { get; set; }
        public string KeyResponsibility { get; set; }
        public string KeySkills { get; set; }
    }
}
