// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class PTPolicyMaster
{
    public string State { get; set; }

    public decimal? SlabMin { get; set; }

    public decimal? SlabMax { get; set; }

    public decimal? PtRate { get; set; }

    public string Frequency { get; set; }

    public int Id { get; set; }
}