// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class PunchRecord
{
    public int Id { get; set; }

    public string EmployeeId { get; set; }

    public DateTime PunchTime { get; set; }
}