// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class ReferencesTableType
    {
        [StringLength(200)]
        public string FullName { get; set; }
        [StringLength(200)]
        public string Company_Designation { get; set; }
        [StringLength(200)]
        public string Contact_Details { get; set; }
        [StringLength(200)]
        public string Bussiness_Details { get; set; }
    }
}
