// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class RetailEmployee
{
    public string Employee_Code { get; set; }

    public string Department { get; set; }

    public string Designation { get; set; }

    public string states { get; set; }
}