// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class SalaryCyclePolicy
{
    public int SalaryCyclePolicyId { get; set; }

    public string Type { get; set; }

    public DateTime? EffectiveDate { get; set; }

    public byte? From { get; set; }

    public byte? To { get; set; }

    public string Custom_type { get; set; }
}