// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class SalaryRunQueue
{
    public long QueueId { get; set; }

    public string Ecode { get; set; }

    public string MonthKey { get; set; }

    public string Status { get; set; }

    public string LastError { get; set; }

    public DateTime? ProcessedOn { get; set; }
}