// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class SearchEmployeeDetailsResult
    {
        public long EmployeeId { get; set; }
        [Column("FULL NAME")]
        [StringLength(50)]
        public string FULLNAME { get; set; }
        [StringLength(20)]
        public string Ecode { get; set; }
    }
}
