// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class Shift_Schedule
{
    public string Shift_Code { get; set; }

    public string Shift_Name { get; set; }

    public TimeSpan Start_Time { get; set; }

    public TimeSpan End_Time { get; set; }

    public int Id { get; set; }
}