// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class sp_CalculateEmployeePayroll_arithResult
    {
        [Column("OpeningCompOffBalance", TypeName = "decimal(18,2)")]
        public decimal? OpeningCompOffBalance { get; set; }
        [Column("OpeningEarnedLeaveBalance", TypeName = "decimal(18,2)")]
        public decimal? OpeningEarnedLeaveBalance { get; set; }
        [Column("OpeningCasualLeaveBalance", TypeName = "decimal(18,2)")]
        public decimal? OpeningCasualLeaveBalance { get; set; }
    }
}
