// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class sp_CalculateEmployeePayroll_PT_LWF_Dev_Without_PF_ESIC_PTAX_LWFResult
    {
    }
}
