// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class sp_dcattendance_gapreportResult
    {
        [StringLength(255)]
        public string Ecode { get; set; }
        [Column("EMP-NAME")]
        [StringLength(255)]
        public string EMPNAME { get; set; }
        [StringLength(255)]
        public string Department { get; set; }
        [Column("SUB-DEPARTMENT")]
        [StringLength(255)]
        public string SUBDEPARTMENT { get; set; }
        [StringLength(10)]
        public string AttendanceDate { get; set; }
        [StringLength(1)]
        public string DcAttendance { get; set; }
        [StringLength(1)]
        public string SaviourAttendance { get; set; }
        [StringLength(1)]
        public string FinalAttendance { get; set; }
        public DateTime? LastUpdatedDateTime { get; set; }
    }
}
