// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class sp_FNF_GetFnfDetailsByEcodeByGautamResult
    {
        [StringLength(20)]
        public string Ecode { get; set; }
        [StringLength(50)]
        public string EmployeeName { get; set; }
        public DateTime? DOJ { get; set; }
        public DateTime? LastDay { get; set; }
        [Column("NoticePeriod", TypeName = "decimal(18,2)")]
        public decimal? NoticePeriod { get; set; }
        [StringLength(50)]
        public string ResignationTypeName { get; set; }
        public DateTime? ResignationDate { get; set; }
        [StringLength(200)]
        public string Remarks { get; set; }
        [StringLength(10)]
        public string LastPunchMonth { get; set; }
        [Column("LastPunchMonthDays", TypeName = "decimal(18,2)")]
        public decimal? LastPunchMonthDays { get; set; }
        [Column("Rate", TypeName = "decimal(18,2)")]
        public decimal? Rate { get; set; }
        [Column("EarnedLeaveDays", TypeName = "decimal(18,2)")]
        public decimal? EarnedLeaveDays { get; set; }
        [Column("EarnedLeaveAmount", TypeName = "decimal(18,2)")]
        public decimal? EarnedLeaveAmount { get; set; }
        [Column("UnpaidAmount", TypeName = "decimal(18,2)")]
        public decimal? UnpaidAmount { get; set; }
        [Column("FinalBonus", TypeName = "decimal(18,2)")]
        public decimal? FinalBonus { get; set; }
        [StringLength(10)]
        public string BonusStartMonth { get; set; }
        [StringLength(10)]
        public string BonusEndMonth { get; set; }
        [StringLength(200)]
        public string BonusRemarks { get; set; }
        [Column("YearsServed", TypeName = "decimal(18,2)")]
        public decimal? YearsServed { get; set; }
        [Column("GratuityAmount", TypeName = "decimal(18,2)")]
        public decimal? GratuityAmount { get; set; }
        [StringLength(250)]
        public string ResignationAttachment { get; set; }
    }
}
