// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class sp_FNF_CalculateBonusResult
    {
        public int? Year { get; set; }
        public int? Month { get; set; }
        [Column("Rate", TypeName = "decimal(18,2)")]
        public decimal? Rate { get; set; }
        [Column("Paid", TypeName = "decimal(18,2)")]
        public decimal? Paid { get; set; }
        public int? DaysWorked { get; set; }
        public int? PayableDays { get; set; }
        [Column("BonusForMonth", TypeName = "decimal(18,2)")]
        public decimal? BonusForMonth { get; set; }
    }
}
