// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class sp_FNF_CalcLeaveEncashmentResult
    {
        [StringLength(50)]
        public string Ecode { get; set; }
        public DateTime? FromDate { get; set; }
        public DateTime? ToDate { get; set; }
        [Column("MonthlyBase", TypeName = "decimal(18,2)")]
        public decimal? MonthlyBase { get; set; }
        public int? DivideByDays { get; set; }
        [Column("PerDayRate", TypeName = "decimal(18,2)")]
        public decimal? PerDayRate { get; set; }
        [Column("ELDays", TypeName = "decimal(18,2)")]
        public decimal? ELDays { get; set; }
        [Column("LeaveEncashmentAmount", TypeName = "decimal(18,2)")]
        public decimal? LeaveEncashmentAmount { get; set; }
    }
}
