// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class sp_FNF_SavePaymentResult
    {
        [Column("PaymentId", TypeName = "decimal(38,0)")]
        public decimal? PaymentId { get; set; }
    }
}
