// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class sp_FNF_CalcGratuityResult
    {
        public long EmployeeId { get; set; }
        [StringLength(20)]
        public string Ecode { get; set; }
        public DateTime? DOJ { get; set; }
        public DateTime? DateOfLeft { get; set; }
        [Column("BasicSalary", TypeName = "decimal(18,2)")]
        public decimal? BasicSalary { get; set; }
        [Column("DA", TypeName = "decimal(18,2)")]
        public decimal? DA { get; set; }
        public int? CompletedYears { get; set; }
        [Column("Gratuity", TypeName = "decimal(18,2)")]
        public decimal? Gratuity { get; set; }
    }
}
