// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class sp_GetPayrollSummaryResult
    {
        [StringLength(255)]
        public string LocationName { get; set; }
        [StringLength(10)]
        public string STCode { get; set; }
        [StringLength(50)]
        public string Ecode { get; set; }
        public DateTime? MonthYear { get; set; }
        [Column("Payable_Salary", TypeName = "decimal(18,2)")]
        public decimal Payable_Salary { get; set; }
        [Column("GiventoBank", TypeName = "decimal(18,2)")]
        public decimal GiventoBank { get; set; }
        [Column("PaidByBank", TypeName = "decimal(18,2)")]
        public decimal PaidByBank { get; set; }
        [Column("ReturnByBank", TypeName = "decimal(18,2)")]
        public decimal ReturnByBank { get; set; }
        [Column("DifferencePayableMinusGiven", TypeName = "decimal(19,2)")]
        public decimal? DifferencePayableMinusGiven { get; set; }
        [Column("DifferencePayableMinusPaid", TypeName = "decimal(19,2)")]
        public decimal? DifferencePayableMinusPaid { get; set; }
        [Column("DifferencePayableMinusReturned", TypeName = "decimal(19,2)")]
        public decimal? DifferencePayableMinusReturned { get; set; }
        [Column("DifferenceGivenMinusPaid", TypeName = "decimal(19,2)")]
        public decimal? DifferenceGivenMinusPaid { get; set; }
        [Column("DifferenceGivenMinusReturned", TypeName = "decimal(19,2)")]
        public decimal? DifferenceGivenMinusReturned { get; set; }
    }
}
