// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class sp_GetEmployeeSeparationsResult
    {
        public int EmployeeSeprationId { get; set; }
        public long EmpId { get; set; }
        public DateTime? LastDay { get; set; }
        public int? NoticePeriod { get; set; }
        [StringLength(50)]
        public string ResignationType { get; set; }
        public DateTime ResignationDate { get; set; }
        [StringLength(255)]
        public string Remarks { get; set; }
        public bool? IsApprovedByManager { get; set; }
        [StringLength(8)]
        public string Status { get; set; }
    }
}
