// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class sp_GetUserByRefreshTokenResult
    {
        public int Id { get; set; }
        [StringLength(50)]
        public string Ecode { get; set; }
        [StringLength(100)]
        public string EmailAddress { get; set; }
        public int EmployeeId { get; set; }
        [StringLength(50)]
        public string Role { get; set; }
        [StringLength(50)]
        public string ReportHeadEcode { get; set; }
        public int? Reportheadid { get; set; }
        [StringLength(2147483647)]
        public string RefreshToken { get; set; }
        public DateTime? RefreshTokenExpiry { get; set; }
    }
}
