// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class sp_GetEmployeeLeaveBalanceResult
    {
        [StringLength(10)]
        public string MonthYear { get; set; }
        [StringLength(20)]
        public string Ecode { get; set; }
        [Column("Remaining_EL", TypeName = "decimal(19,2)")]
        public decimal? Remaining_EL { get; set; }
        [Column("Remaining_CL", TypeName = "decimal(19,2)")]
        public decimal? Remaining_CL { get; set; }
        [Column("Remaining_CompOff", TypeName = "decimal(19,2)")]
        public decimal? Remaining_CompOff { get; set; }
    }
}
