// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class SP_GetApplicantFeedBackResult
    {
        [StringLength(100)]
        public string CandidateName { get; set; }
        [StringLength(2147483647)]
        public string EMAILADDRESS { get; set; }
        [StringLength(255)]
        public string Designation { get; set; }
        [StringLength(2147483647)]
        public string MOBILE { get; set; }
        public int RoundId { get; set; }
        [StringLength(73)]
        public string Interviewer { get; set; }
        [StringLength(2147483647)]
        public string FeedBack { get; set; }
        [StringLength(100)]
        public string Status { get; set; }
        [StringLength(200)]
        public string InterviewerStatus { get; set; }
        [StringLength(77)]
        public string CreatedBy { get; set; }
        [Column("Created On")]
        public DateTime? CreatedOn { get; set; }
    }
}
