// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class sp_GetTotalDeductionByEcodeResult
    {
        [StringLength(50)]
        public string ECODE { get; set; }
        [StringLength(10)]
        public string STCode { get; set; }
        [StringLength(255)]
        public string LocationName { get; set; }
        [Column("FULL NAME")]
        [StringLength(50)]
        public string FULLNAME { get; set; }
        [StringLength(255)]
        public string DepartmentName { get; set; }
        [StringLength(255)]
        public string DesignationName { get; set; }
        [StringLength(6)]
        public string MONTH { get; set; }
        public string Year { get; set; }
        [Column("PF", TypeName = "decimal(18,2)")]
        public decimal? PF { get; set; }
        [Column("ESIC", TypeName = "decimal(18,2)")]
        public decimal? ESIC { get; set; }
        [Column("TDS", TypeName = "decimal(18,2)")]
        public decimal? TDS { get; set; }
        [Column("PTax", TypeName = "decimal(18,2)")]
        public decimal? PTax { get; set; }
        [Column("Loan", TypeName = "decimal(18,2)")]
        public decimal? Loan { get; set; }
        [Column("CashShort", TypeName = "decimal(18,2)")]
        public decimal? CashShort { get; set; }
        [Column("DieselDeduction", TypeName = "decimal(18,2)")]
        public decimal? DieselDeduction { get; set; }
        [Column("Penality", TypeName = "decimal(18,2)")]
        public decimal? Penality { get; set; }
        [Column("Lwf", TypeName = "decimal(18,2)")]
        public decimal? Lwf { get; set; }
        [Column("TotalDeductions", TypeName = "decimal(18,2)")]
        public decimal? TotalDeductions { get; set; }
    }
}
