// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class sp_GetEmployeeDetails_HoldListResult
    {
        public long EmployeeId { get; set; }
        public long? CandidateId { get; set; }
        [StringLength(135)]
        public string LocBasedECode { get; set; }
        [StringLength(50)]
        public string FullName { get; set; }
        [StringLength(255)]
        public string DepartmentName { get; set; }
        [StringLength(255)]
        public string DesignationName { get; set; }
        [StringLength(255)]
        public string LocationName { get; set; }
        [StringLength(10)]
        public string STCode { get; set; }
        [StringLength(20)]
        public string Ecode { get; set; }
        [StringLength(100)]
        public string ReportHeadEcode { get; set; }
        public bool? IsActive { get; set; }
        public bool? IsDeleted { get; set; }
        public bool? isresgined { get; set; }
        public DateTime? DateOfLeft { get; set; }
        public DateTime? DateOfResignation { get; set; }
        [Column("Payble_Days", TypeName = "decimal(15,2)")]
        public decimal? Payble_Days { get; set; }
        [Column("Final_Amount", TypeName = "decimal(18,2)")]
        public decimal? Final_Amount { get; set; }
    }
}
