// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class SP_GetInterviewBackgroundProcessResult
    {
        [StringLength(2147483647)]
        public string FirstName { get; set; }
        [StringLength(2147483647)]
        public string LastName { get; set; }
        [StringLength(255)]
        public string Designation { get; set; }
        [StringLength(2147483647)]
        public string Mobile { get; set; }
        [StringLength(2147483647)]
        public string Email { get; set; }
        [StringLength(20)]
        public string Status { get; set; }
        [StringLength(150)]
        public string Remarks { get; set; }
    }
}
