// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class sp_GetEmployeeSalarySlipDetailsnewResult
    {
        [StringLength(20)]
        public string ECode { get; set; }
        public long? EmployeeId { get; set; }
        [StringLength(50)]
        public string EmployeeName { get; set; }
        [StringLength(255)]
        public string Designation { get; set; }
        public DateTime? DateofJoining { get; set; }
        [StringLength(255)]
        public string LocationName { get; set; }
        [StringLength(255)]
        public string Department { get; set; }
        [StringLength(30)]
        public string BankAccountNo { get; set; }
        [StringLength(15)]
        public string PAN_NO { get; set; }
        [StringLength(100)]
        public string BankName { get; set; }
        [StringLength(10)]
        public string NoofDays { get; set; }
        [StringLength(15)]
        public string IfscCode { get; set; }
        [StringLength(2147483647)]
        public string UniversalAccountNumber { get; set; }
        [StringLength(100)]
        public string EsicNo { get; set; }
        [Column("BasicSalaryBud", TypeName = "decimal(18,2)")]
        public decimal? BasicSalaryBud { get; set; }
        [Column("BasicSalary", TypeName = "decimal(18,2)")]
        public decimal? BasicSalary { get; set; }
        [Column("CCABud", TypeName = "decimal(18,2)")]
        public decimal? CCABud { get; set; }
        [Column("CCA", TypeName = "decimal(18,2)")]
        public decimal? CCA { get; set; }
        [Column("DABud", TypeName = "decimal(18,2)")]
        public decimal? DABud { get; set; }
        [Column("DA", TypeName = "decimal(18,2)")]
        public decimal? DA { get; set; }
        [Column("HRABud", TypeName = "decimal(18,2)")]
        public decimal? HRABud { get; set; }
        [Column("HRA", TypeName = "decimal(18,2)")]
        public decimal? HRA { get; set; }
        [StringLength(32)]
        public string Incentive { get; set; }
        [Column("SpecialAllowanceBud", TypeName = "decimal(18,2)")]
        public decimal? SpecialAllowanceBud { get; set; }
        [Column("SpecialAllowance", TypeName = "decimal(18,2)")]
        public decimal? SpecialAllowance { get; set; }
        [Column("ExtraAllowance", TypeName = "decimal(18,2)")]
        public decimal? ExtraAllowance { get; set; }
        [Column("GrossEarningsCTCRef", TypeName = "decimal(22,2)")]
        public decimal? GrossEarningsCTCRef { get; set; }
        [Column("GrossEarningsAmount", TypeName = "decimal(24,2)")]
        public decimal? GrossEarningsAmount { get; set; }
        [Column("EPF", TypeName = "decimal(18,2)")]
        public decimal? EPF { get; set; }
        [Column("ESIC", TypeName = "decimal(18,2)")]
        public decimal? ESIC { get; set; }
        [StringLength(32)]
        public string TDS { get; set; }
        [StringLength(32)]
        public string PTax { get; set; }
        [StringLength(32)]
        public string Loan { get; set; }
        [StringLength(32)]
        public string CashShort { get; set; }
        [StringLength(32)]
        public string DieselDeduction { get; set; }
        [StringLength(32)]
        public string Penality { get; set; }
        [StringLength(50)]
        public string Lwf { get; set; }
        [Column("GrossDeduction", TypeName = "decimal(18,2)")]
        public decimal? GrossDeduction { get; set; }
        [Column("GrossNetPay", TypeName = "decimal(19,2)")]
        public decimal? GrossNetPay { get; set; }
        [Column("Fuel_and_Maintenance", TypeName = "decimal(18,2)")]
        public decimal? Fuel_and_Maintenance { get; set; }
        [Column("Books_and_Periodicals", TypeName = "decimal(18,2)")]
        public decimal? Books_and_Periodicals { get; set; }
        [Column("Professional_Attire", TypeName = "decimal(18,2)")]
        public decimal? Professional_Attire { get; set; }
        [Column("Driver_Wages", TypeName = "decimal(18,2)")]
        public decimal? Driver_Wages { get; set; }
        [Column("Mobile_Bill", TypeName = "decimal(18,2)")]
        public decimal? Mobile_Bill { get; set; }
        [Column("Meal_Voucher", TypeName = "decimal(18,2)")]
        public decimal? Meal_Voucher { get; set; }
        [Column("GrossEarnings", TypeName = "decimal(18,2)")]
        public decimal? GrossEarnings { get; set; }
        [Column("FinalGrossEarnings_Netpay", TypeName = "decimal(18,2)")]
        public decimal? FinalGrossEarnings_Netpay { get; set; }
        [Column("EC_PF", TypeName = "decimal(18,2)")]
        public decimal? EC_PF { get; set; }
        [Column("EC_EPS", TypeName = "decimal(18,2)")]
        public decimal? EC_EPS { get; set; }
        [Column("ERC_PF", TypeName = "decimal(18,2)")]
        public decimal? ERC_PF { get; set; }
        [StringLength(50)]
        public string E_VPF { get; set; }
        [Column("Payble_Days", TypeName = "decimal(18,2)")]
        public decimal? Payble_Days { get; set; }
        [Column("EarnedLeaveBalance", TypeName = "decimal(18,2)")]
        public decimal? EarnedLeaveBalance { get; set; }
        [Column("EarnedLeaveUsed", TypeName = "decimal(18,2)")]
        public decimal? EarnedLeaveUsed { get; set; }
        [Column("CasualLeaveBalance", TypeName = "decimal(18,2)")]
        public decimal? CasualLeaveBalance { get; set; }
        [Column("CasualLeaveUsed", TypeName = "decimal(18,2)")]
        public decimal? CasualLeaveUsed { get; set; }
        [Column("CompoOffBalance", TypeName = "decimal(18,2)")]
        public decimal? CompoOffBalance { get; set; }
        [Column("CompoOffUsed", TypeName = "decimal(18,2)")]
        public decimal? CompoOffUsed { get; set; }
        [StringLength(50)]
        public string MONTH { get; set; }
        [StringLength(50)]
        public string PF_Number { get; set; }
    }
}
