// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class sp_GetMonthlyAttendanceGeoSummaryResult
    {
        public long EmployeeId { get; set; }
        public DateTime? AttendanceDate { get; set; }
        public int? PunchCount { get; set; }
        public int? InCount { get; set; }
        public int? OutCount { get; set; }
        [Column("Latitude", TypeName = "decimal(9,6)")]
        public decimal? Latitude { get; set; }
        [Column("Longitude", TypeName = "decimal(9,6)")]
        public decimal? Longitude { get; set; }
        public TimeSpan PunchIn { get; set; }
        public TimeSpan PunchOut { get; set; }
        public int? TotalWorkingMinutes { get; set; }
        [StringLength(33)]
        public string TotalWorkingHours { get; set; }
        public int? LateMinutes { get; set; }
        public int? EarlyMinutes { get; set; }
        public int? StatusId { get; set; }
        [StringLength(50)]
        public string StatusName { get; set; }
        [StringLength(8)]
        public string AttendanceStatus { get; set; }
    }
}
