// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class sp_GetScheduledInterviewsResult
    {
        public int ScheduleId { get; set; }
        public int ApplicantId { get; set; }
        [StringLength(100)]
        public string CandidateName { get; set; }
        public DateTime InterviewDateTime { get; set; }
        [StringLength(50)]
        public string InterviewMode { get; set; }
        [StringLength(100)]
        public string InterviewLocation { get; set; }
        [StringLength(2147483647)]
        public string Notes { get; set; }
        public int RoundId { get; set; }
        public int? InterviewRoundId { get; set; }
        public int? InterviewerId { get; set; }
        [StringLength(2147483647)]
        public string FeedBack { get; set; }
        [StringLength(100)]
        public string Status { get; set; }
        [StringLength(200)]
        public string InterviewerStatus { get; set; }
    }
}
