// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class sp_GetLocationAssignmentsResult
    {
        public int AssignLocationHistoryId { get; set; }
        public long EmployeeId { get; set; }
        [StringLength(20)]
        public string Ecode { get; set; }
        [StringLength(50)]
        public string EmployeeName { get; set; }
        public long CandidateId { get; set; }
        public int AssignedLocation { get; set; }
        [StringLength(25)]
        public string AssignedReason { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public DateTime AssignedOnDate { get; set; }
        public DateTime? ReleasedOnDate { get; set; }
        public int TransferApprovalStatus { get; set; }
        public int IsReportingHeadApproval { get; set; }
        public int IsHRApproval { get; set; }
        [StringLength(255)]
        public string AssignLocationName { get; set; }
        [StringLength(10)]
        public string AssignLocationSTCode { get; set; }
        [StringLength(255)]
        public string BaseLocation { get; set; }
        [StringLength(10)]
        public string BaseLocationSTCode { get; set; }
        public bool PermanentTransfer { get; set; }
        public bool TemporaryTransfer { get; set; }
        [StringLength(255)]
        public string DesignationName { get; set; }
        [StringLength(255)]
        public string DepartmentName { get; set; }
        public int DepartmentId { get; set; }
        public int DesignationId { get; set; }
        public DateTime? CreatedOn { get; set; }
        public DateTime? UpdatedOn { get; set; }
        [StringLength(20)]
        public string CreatedBy { get; set; }
        [StringLength(20)]
        public string UpdatedBy { get; set; }
    }
}
