// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class sp_GetAllEmployeeTransferByManagerIdResult
    {
        public long? CandidateId { get; set; }
        [StringLength(2147483647)]
        public string CandidateName { get; set; }
        public int? AssignedLocation { get; set; }
        [StringLength(25)]
        public string AssignedReason { get; set; }
        public bool? IsActive { get; set; }
        public DateTime AssignedOnDate { get; set; }
        public DateTime? ReleasedOnDate { get; set; }
        public int? TransferApprovalStatus { get; set; }
        public int? IsReportingHeadApproval { get; set; }
        public int? IsHRApproval { get; set; }
        [StringLength(500)]
        public string ReportHeadEcode { get; set; }
    }
}
