// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class sp_GetScheduleInterviewWithRoundsResult
    {
        public int ScheduleId { get; set; }
        public int ApplicantId { get; set; }
        [StringLength(100)]
        public string CandidateName { get; set; }
        public DateTime InterviewDateTime { get; set; }
        [StringLength(50)]
        public string InterviewMode { get; set; }
        [StringLength(100)]
        public string InterviewLocation { get; set; }
        [StringLength(2147483647)]
        public string Notes { get; set; }
        public int RoundId { get; set; }
        [StringLength(8000)]
        public string InterviewerIds { get; set; }
        [StringLength(8000)]
        public string Statuses { get; set; }
        [StringLength(2147483647)]
        public string Feedbacks { get; set; }
        [StringLength(100)]
        public string RoundStatus { get; set; }
        [StringLength(8)]
        public string RoundApprovalStatus { get; set; }
    }
}
