// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class sp_GetRegularizeRequestsBulkResult
    {
        [StringLength(20)]
        public string Ecode { get; set; }
        [Column("FULL NAME")]
        [StringLength(50)]
        public string FULLNAME { get; set; }
        [StringLength(100)]
        public string FirstName { get; set; }
        [StringLength(100)]
        public string LastName { get; set; }
        public DateTime RequestDate { get; set; }
        [StringLength(500)]
        public string Reason { get; set; }
        [StringLength(50)]
        public string StatusName { get; set; }
        [StringLength(50)]
        public string ReportingManagerName { get; set; }
        [StringLength(2147483647)]
        public string EmployeeRemarks { get; set; }
        public TimeSpan? PunchIn { get; set; }
        public TimeSpan? PunchOut { get; set; }
    }
}
