// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class sp_GetLeaveRequestsAllEmployeeResult
    {
        [StringLength(20)]
        public string Ecode { get; set; }
        [Column("FULL NAME")]
        [StringLength(50)]
        public string FULLNAME { get; set; }
        [StringLength(100)]
        public string FirstName { get; set; }
        [StringLength(100)]
        public string LastName { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        [StringLength(500)]
        public string Reason { get; set; }
        [StringLength(50)]
        public string StatusName { get; set; }
        [StringLength(50)]
        public string ReportingManagerName { get; set; }
        [StringLength(100)]
        public string LeaveTypeName { get; set; }
        public bool? FirstHalf { get; set; }
        public bool? SecondHalf { get; set; }
        public bool? FullDay { get; set; }
    }
}
