// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class sp_GetOfferletterOnMailResult
    {
        public long CId { get; set; }
        [StringLength(300)]
        public string Email { get; set; }
        [StringLength(300)]
        public string pdfName { get; set; }
        [StringLength(2147483647)]
        public string Full_Name { get; set; }
        [StringLength(255)]
        public string DesignationName { get; set; }
        [StringLength(300)]
        public string FilePath { get; set; }
        [StringLength(2147483647)]
        public string TITLE { get; set; }
    }
}
