// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class sp_GetInterviewFormdataByIdResult
    {
        [StringLength(2147483647)]
        public string InterviewFormData { get; set; }
    }
}
