// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class SP_InterviewAssignedResult
    {
        [Column("Applied Date")]
        public DateTime? AppliedDate { get; set; }
        [StringLength(100)]
        public string CurrentLocation { get; set; }
        [StringLength(1000)]
        public string PreferredLocation { get; set; }
        [Column("Preferred State")]
        [StringLength(100)]
        public string PreferredState { get; set; }
        [Column("Store Code")]
        [StringLength(266)]
        public string StoreCode { get; set; }
        [StringLength(100)]
        public string Name { get; set; }
        [StringLength(2147483647)]
        public string Email { get; set; }
        [StringLength(255)]
        public string Designation { get; set; }
        [StringLength(2147483647)]
        public string MOBILE { get; set; }
        [Column("Experience", TypeName = "decimal(18,2)")]
        public decimal? Experience { get; set; }
        [Column("Current Company")]
        [StringLength(2147483647)]
        public string CurrentCompany { get; set; }
        [Column("Current Salary", TypeName = "decimal(18,2)")]
        public decimal? CurrentSalary { get; set; }
        [StringLength(50)]
        public string InterviewMode { get; set; }
        public DateTime? InterviewDate { get; set; }
        public bool? IsResumeUploaded { get; set; }
        [Column("Assign By")]
        [StringLength(73)]
        public string AssignBy { get; set; }
        [Column("Assign To")]
        [StringLength(73)]
        public string AssignTo { get; set; }
        public int RoundId { get; set; }
        [Column("Created On")]
        public DateTime? CreatedOn { get; set; }
        [StringLength(2147483647)]
        public string UpdatedBy { get; set; }
        public DateTime? UpdatedOn { get; set; }
    }
}
