// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class SP_InterviewBackgroundProcessResult
    {
        public int Success { get; set; }
        [StringLength(28)]
        public string Message { get; set; }
    }
}
