// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class sp_TemporalVersioningOffResult
    {
        [StringLength(3)]
        public string VersioningStatus { get; set; }
        [StringLength(517)]
        public string TableName { get; set; }
        [StringLength(517)]
        public string HistoryTable { get; set; }
    }
}
