// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class SpUpsertEmployeeStoreResult
    {
        public long EmployeeId { get; set; }
        [StringLength(20)]
        public string Ecode { get; set; }
        [StringLength(50)]
        public string FullName { get; set; }
        [StringLength(150)]
        public string Email { get; set; }
        public int? LocationId { get; set; }
        public bool? IsStore { get; set; }
        [StringLength(255)]
        public string PasswordHash { get; set; }
        public int? RoleId { get; set; }
        public DateTime? AssignedOn { get; set; }
        public DateTime? LastUpdatedOn { get; set; }
    }
}
