// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class StagingEmployee
{
    public int? EmployeeId { get; set; }

    public int? CandidateId { get; set; }

    public string FILE_PATH { get; set; }

    public string TITLE { get; set; }

    public string FULL_NAME { get; set; }

    public string FATHER_S_NAME { get; set; }

    public string MOTHER_S_NAME { get; set; }

    public string PASPORT_SIZE_PHOTO { get; set; }

    public DateTime? DOB { get; set; }

    public string GENDER { get; set; }

    public string PAN_NO { get; set; }

    public string AADHAR_NO { get; set; }

    public string NAME_ON_ADHAR { get; set; }

    public string PLACE_OF_BIRTH { get; set; }

    public string PRESENT_ADDRESS { get; set; }

    public string PRESENT_ADDRESS_PIN_CODE { get; set; }

    public string PERMANENT_ADDRESS { get; set; }

    public string MARITIAL_STATUS { get; set; }

    public string MOBILE { get; set; }

    public string EMAIL_ADDRESS { get; set; }

    public string NATIONALITY { get; set; }

    public string RELIGION { get; set; }

    public string BANK_NAME { get; set; }

    public string A_C_NO { get; set; }

    public string BANK_IFSC_CODE { get; set; }

    public string REFERENCE1_OF_LAST_3_COMPANY { get; set; }

    public string CONTACT1_OF_LAST_3_COMPANY { get; set; }

    public string REFERENCE2_OF_LAST_3_COMPANY1 { get; set; }

    public string CONTACT2_OF_LAST_3_COMPANY1 { get; set; }

    public string REFERENCE3_OF_LAST_3_COMPANY11 { get; set; }

    public string CONTACT3_OF_LAST_3_COMPANY11 { get; set; }

    public string REFERENCE4_OF_LAST_3_COMPANY11 { get; set; }

    public string CONTACT4_OF_LAST_3_COMPANY11 { get; set; }

    public string REFERENCE5_OF_LAST_3_COMPANY111 { get; set; }

    public string CONTACT5_OF_LAST_3_COMPANY111 { get; set; }

    public string FAMILY_MEMBER_Name { get; set; }

    public string FAMILY_MEMBER_Relation { get; set; }

    public DateTime? FAMILY_MEMBER_DOB { get; set; }

    public string COMPANY_1 { get; set; }

    public string COMPANY_2 { get; set; }

    public string COMPANY_3 { get; set; }

    public string WORK_LOCATION { get; set; }

    public string POSITION_HELD_IN_PREVIOUS_COMPANY { get; set; }

    public DateTime? From { get; set; }

    public DateTime? To { get; set; }

    public decimal? In_Hand_Salary { get; set; }

    public decimal? LAST_CTC_ANNUAL_ { get; set; }

    public string HIGHEST_QUALIFICATION { get; set; }

    public DateTime? CreatedOn { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public string DeletedBy { get; set; }

    public DateTime? DeletedOn { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsDeleted { get; set; }

    public bool? IsSalarySlipUploaded { get; set; }

    public bool? IsBankStatementUploaded { get; set; }

    public bool? IsPrevOfferLetterUploaded { get; set; }

    public bool? IsPassportPhotoUploaded { get; set; }

    public bool? IsPanAttachmentUploaded { get; set; }

    public bool? IsAadharAttachmentUploaded { get; set; }

    public bool? IsBankPassbookAttachmentUpoaded { get; set; }

    public bool? IsEducationAttachmentUploaded { get; set; }

    public string UDF1 { get; set; }

    public string UDF2 { get; set; }

    public string UDF3 { get; set; }

    public string UDF4 { get; set; }

    public string UDF5 { get; set; }

    public string UDF6 { get; set; }

    public string UDF7 { get; set; }

    public string LastUpdatedBy { get; set; }

    public string Ecode { get; set; }

    public int? DesignationId { get; set; }

    public int? DepartmentId { get; set; }

    public int? LocationId { get; set; }

    public DateTime? DOJ { get; set; }

    public DateTime? DateOfResignation { get; set; }

    public DateTime? DateOfLeft { get; set; }

    public bool? isresgined { get; set; }

    public string FirstName { get; set; }

    public string MiddleName { get; set; }

    public string LastName { get; set; }

    public string PasswordHash { get; set; }

    public string PasswordSalt { get; set; }

    public string ReportHeadEcode { get; set; }
}