// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class StateMasterWithMinWage
{
    public string StateName { get; set; }

    public int MinWages { get; set; }

    public int Id { get; set; }

    public virtual ICollection<Candidate> Candidates { get; set; } = new List<Candidate>();
}