// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class StoreRoutingMaster
{
    public int Id { get; set; }

    public int StagingSequence { get; set; }

    public string StagingName { get; set; }

    public int RoutingSequence { get; set; }

    public string RoutingName { get; set; }

    public string BgtTimeline { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedDate { get; set; }

    public virtual ICollection<StoreRoutingTransaction> StoreRoutingTransactions { get; set; } = new List<StoreRoutingTransaction>();
}