// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class StoreMasterBulk
{
    public string DEPTSNO { get; set; }

    public string LOC { get; set; }

    public string Company { get; set; }

    public string REGION { get; set; }

    public string CL { get; set; }

    public string SUBDEPTSNO { get; set; }

    public string SUBDEPT { get; set; }

    public string DESGSNO { get; set; }

    public string DESG_ { get; set; }

    public string SS { get; set; }

    public string SEATMASTERNO { get; set; }

    public string Emp_Code { get; set; }

    public string Name_of_Employee { get; set; }

    public string E_MAIL_ID { get; set; }

    public string CONTACT_NO { get; set; }

    public string Gender { get; set; }

    public string D_O_B_ { get; set; }

    public string D_O_J_ { get; set; }

    public string Role { get; set; }

    public string KRA { get; set; }

    public string KPI { get; set; }

    public string TRAININGCONTENT { get; set; }

    public string YESNO { get; set; }

    public string GOAL { get; set; }

    public string GRADE { get; set; }

    public string Reporting_MANAGER_DESG { get; set; }

    public string REPORTING_MANAGER_NM { get; set; }

    public string REPORTING_MANAGER_MAIL_ID { get; set; }

    public string REPORTING_MANAGER_CONTACT_NO { get; set; }
}