// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class StoreStateLinking
{
    public string ST_CD { get; set; }

    public string State { get; set; }

    public int Id { get; set; }
}