// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class StoreLocation
{
    public int StoreLocationsId { get; set; }

    public string NameOfLocation { get; set; }

    public string LocationIncharge { get; set; }

    public string Address { get; set; }

    public string SAPCode { get; set; }

    public string Zone { get; set; }

    public bool? BillingOver50Lac { get; set; }

    public string PFCode { get; set; }

    public string ESICode { get; set; }

    public string Type { get; set; }

    public int StateId { get; set; }

    public string WeeklyOff { get; set; }

    public string EmailID { get; set; }

    public string ERPSiteNameCode { get; set; }

    public string Udf1 { get; set; }

    public string Udf2 { get; set; }

    public string Udf3 { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedOn { get; set; }

    public string LastupdatedBy { get; set; }

    public int? LocationId { get; set; }

    public virtual State State { get; set; }

    public virtual ICollection<tblStoreBudget> tblStoreBudgets { get; set; } = new List<tblStoreBudget>();
}