// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class StoreRoutingTransactionAttachment
{
    public int Id { get; set; }

    public int StoreRoutingTransactionId { get; set; }

    public string Attachment { get; set; }

    public virtual StoreRoutingTransaction StoreRoutingTransaction { get; set; }
}