// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class StoreRoutingTransaction
{
    public int Id { get; set; }

    public int LocationId { get; set; }

    public int StoreRoutingMasterId { get; set; }

    public string Remarks { get; set; }

    public DateTime ActionDate { get; set; }

    public int ActionById { get; set; }

    public virtual tblLocation Location { get; set; }

    public virtual StoreRoutingMaster StoreRoutingMaster { get; set; }

    public virtual ICollection<StoreRoutingTransactionAttachment> StoreRoutingTransactionAttachments { get; set; } = new List<StoreRoutingTransactionAttachment>();
}