// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class Table_Temp
{
    public string Ecode { get; set; }

    public string ReportEcode { get; set; }

    public string Status { get; set; }

    public string RequestDate { get; set; }

    public string PunchIn { get; set; }

    public string PunchOut { get; set; }
}