// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class tbl_InterviewerDetail
{
    public int Id { get; set; }

    public int? InterviewerId { get; set; }

    public string Name { get; set; }

    public string Feedback { get; set; }

    public virtual tbl_Interviewer Interviewer { get; set; }
}