// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class TBL_DCEMPLOYEE
{
    public string E_CODE { get; set; }

    public string EMP_NAME { get; set; }

    public string EMAIL_ID { get; set; }

    public bool? IS_CONTRACT { get; set; }

    public string DESIGNATION { get; set; }

    public string DEPARTMENT { get; set; }

    public string SUB_DEPARTMENT { get; set; }

    public string REPORTING_MANAGER_NAME { get; set; }

    public string RPT_PERSON_CARD { get; set; }

    public string ACT_IN_ACT { get; set; }

    public string PasswordHash { get; set; }

    public string Location { get; set; }
}