// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class tbl_Month_salary
{
    public string ecode { get; set; }

    public decimal? BasicSalary { get; set; }

    public decimal? HRA { get; set; }

    public decimal? CCA { get; set; }

    public decimal? SpecialAllowance { get; set; }

    public decimal? DA { get; set; }

    public decimal? Reimbersment { get; set; }

    public decimal? Fuel_and_Maintainence { get; set; }

    public decimal? Books_and_Periodicals { get; set; }

    public decimal? Professional_Attire { get; set; }

    public decimal? Driver_Wages { get; set; }

    public decimal? Mobile_Bill { get; set; }

    public decimal? Meal_Voucher { get; set; }

    public decimal? monthlyGrossCTC { get; set; }

    public string MONTH { get; set; }

    public string Extra_day_allowence { get; set; }

    public string Incentive { get; set; }

    public string Arrers { get; set; }

    public decimal? PF { get; set; }

    public decimal? ESIC { get; set; }

    public int? MonthNo { get; set; }

    public decimal? monthlyGrossCTC_afterDeduction_ { get; set; }

    public decimal? TDS { get; set; }

    public decimal? PTax { get; set; }

    public decimal? Loan { get; set; }

    public decimal? CashShort { get; set; }

    public decimal? DieselDeduction { get; set; }

    public decimal? Penality { get; set; }

    public decimal? Lwf { get; set; }

    public decimal? Overtime { get; set; }

    public decimal? Fooding_Allowance { get; set; }

    public decimal? Mobile_Bill1 { get; set; }
}