// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class tbl_ecipf_ecode
{
    public string ECODE { get; set; }

    public bool? PF { get; set; }

    public bool? ESI { get; set; }
}