// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class tbl_30seplessactive_employee
{
    public string E_Code { get; set; }

    public string Machine_Company_Name { get; set; }

    public DateTime? Attendance_Punch { get; set; }
}