// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class tbl_Interviewer
{
    public int Id { get; set; }

    public int? ApplicantId { get; set; }

    public string Round { get; set; }

    public string Level { get; set; }

    public string Status { get; set; }

    public string Remark { get; set; }

    public virtual ICollection<tbl_InterviewerDetail> tbl_InterviewerDetails { get; set; } = new List<tbl_InterviewerDetail>();
}