// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class tbl_attendancecount
{
    public string UserID { get; set; }

    public string AttendanceMonth { get; set; }

    public decimal? TotalAttendance { get; set; }

    public int? Present { get; set; }

    public decimal? Absent { get; set; }

    public int? MIS { get; set; }
}