// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class tbl_calculatePaybleday
{
    public int EmployeeAttendancePayrollId { get; set; }

    public string Month { get; set; }

    public int? YEAR { get; set; }

    public int? LocationCategoryId { get; set; }

    public int? DesignationId { get; set; }

    public string EmployeeName { get; set; }

    public string Ecode { get; set; }

    public long? EmployeeId { get; set; }

    public decimal? Attendance { get; set; }

    public decimal? weeklyoffpresent { get; set; }

    public decimal? Actual_Weekly_Off { get; set; }

    public decimal? leave_availed { get; set; }

    public decimal? InitialPaybledays { get; set; }

    public decimal? TotalDaysInMonth { get; set; }

    public decimal? Payble_Days { get; set; }

    public decimal? EXTRA_DAYS { get; set; }

    public decimal? Absent { get; set; }

    public bool? Status { get; set; }

    public int? WeekHolidays { get; set; }

    public int? SatHolidays { get; set; }

    public decimal? NC_Attendance { get; set; }

    public decimal? LWP { get; set; }

    public decimal? AdjustedDays { get; set; }
}