// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class tbl_30seplessactive_employees_refer
{
    public string Ecode { get; set; }

    public DateTime? DateOfLeft { get; set; }

    public DateTime? Attendance_Punch { get; set; }

    public int? DOL_Reason { get; set; }

    public string Machine_Company_Name { get; set; }
}