// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class tbl_rahul_esic_pf_temp
{
    public string Ecode { get; set; }

    public bool? PFApplicable { get; set; }

    public bool? ESICApplicable { get; set; }

    public bool? pf { get; set; }

    public bool? esi { get; set; }
}