// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class tblAttendanceCountAttachment
{
    public long AttachmentId { get; set; }

    public long AttendanceCountApprovalId { get; set; }

    public string FileUrl { get; set; }

    public string FileName { get; set; }

    public long? FileSize { get; set; }

    public DateTime? CreatedOn { get; set; }

    public string CreatedBy { get; set; }
}