// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class tblAttendanceCountApproval
{
    public long AttendanceCountApprovalId { get; set; }

    public string ECode { get; set; }

    public string MonthYear { get; set; }

    public int AttendanceCount { get; set; }

    public string EmployeeRemarks { get; set; }

    public bool? IsCMApproved { get; set; }

    public string CMApprovedBy { get; set; }

    public DateTime? CMApprovedOn { get; set; }

    public string CMRemarks { get; set; }

    public bool? IsRMApproved { get; set; }

    public string RMApprovedBy { get; set; }

    public DateTime? RMApprovedOn { get; set; }

    public string RMRemarks { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedOn { get; set; }

    public string LastUpdatedBy { get; set; }

    public DateTime? UpdatedOn { get; set; }
}