// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class tblAbscondingReason
{
    public int AbscondingReasonId { get; set; }

    public int? ResignationTypeId { get; set; }

    public string AbscondingReasonName { get; set; }

    public virtual tblResignationType ResignationType { get; set; }
}