// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class tblAttendanceRegularizationRequest_nc
{
    public long AttendanceRequestId { get; set; }

    public long? EmployeeId { get; set; }

    public DateTime RequestDate { get; set; }

    public string Reason { get; set; }

    public string Status { get; set; }

    public long? ReportingManagerId { get; set; }

    public DateTime? CreatedOn { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public string UDF1 { get; set; }

    public string UDF2 { get; set; }

    public string UDF3 { get; set; }

    public string UDF4 { get; set; }

    public string UDF5 { get; set; }

    public string UDF6 { get; set; }

    public string UDF7 { get; set; }

    public string LastUpdatedBy { get; set; }

    public TimeSpan? PunchIn { get; set; }

    public TimeSpan? PunchOut { get; set; }

    public int? StatusId { get; set; }

    public string Remarks { get; set; }

    public string FileUrl { get; set; }

    public int? PunchTypeId { get; set; }

    public int? RequestTypeId { get; set; }

    public string EmployeeRemarks { get; set; }

    public int? ManagerApprovalStatusId { get; set; }

    public long? ManagerApproverId { get; set; }

    public DateTime? ManagerApprovalOn { get; set; }

    public string ManagerRemarks { get; set; }

    public int? LpApprovalStatusId { get; set; }

    public long? LpApproverId { get; set; }

    public DateTime? LpApprovalOn { get; set; }

    public string LpRemarks { get; set; }
}