// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class tblBlackListType
{
    public int BlacklistTypeID { get; set; }

    public string BlacklistTypeName { get; set; }
}