// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class tblBlacklistReason
{
    public int BlacklistReasonId { get; set; }

    public int? ResignationTypeId { get; set; }

    public string BlacklistReasonName { get; set; }

    public virtual tblResignationType ResignationType { get; set; }
}