// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class tblBonus_Upload
{
    public int bigid { get; set; }

    public string E_Code { get; set; }

    public DateTime? Date { get; set; }

    public string Acc_Number { get; set; }

    public decimal Amount { get; set; }

    public string UTR { get; set; }

    public string createdBy { get; set; }

    public DateTime? createdOn { get; set; }

    public string updatedBy { get; set; }

    public DateTime? updatedOn { get; set; }

    public bool? isactive { get; set; }

    public bool? isdeleted { get; set; }
}