// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class tblCompOffRequest
{
    public int CompOffId { get; set; }

    public long? EmployeeId { get; set; }

    public DateTime RequestedDate { get; set; }

    public string Reason { get; set; }

    public string Status { get; set; }

    public long? ApprovedBy { get; set; }

    public DateTime? ApprovedOn { get; set; }

    public virtual tblEmployee Employee { get; set; }
}