// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class tblCompany
{
    public int CompanyId { get; set; }

    public string CompanyName { get; set; }

    public virtual ICollection<tblEmployee> tblEmployees { get; set; } = new List<tblEmployee>();
}