// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class tblCompOff
{
    public int CompOffId { get; set; }

    public string Ecode { get; set; }

    public DateTime? MonthYear { get; set; }

    public decimal CompOffEarn { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedOn { get; set; }
}