// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class tblDCAttendance
{
    public string Ecode { get; set; }

    public DateTime? AttendanceDate { get; set; }

    public bool? Status { get; set; }

    public DateTime? SubmitOn { get; set; }

    public long DCAttendanceId { get; set; }
}