// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class tblDepartment
{
    public int DepartmentId { get; set; }

    public string DepartmentName { get; set; }

    public DateTime? CreatedOn { get; set; }

    public string DepartmentCode { get; set; }

    public bool? isActive { get; set; }

    public bool? isDeleted { get; set; }

    public virtual ICollection<AssignLocationHistory> AssignLocationHistories { get; set; } = new List<AssignLocationHistory>();
}