// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class tblDesignation
{
    public int DesignationId { get; set; }

    public string DesignationName { get; set; }

    public DateTime? CreatedOn { get; set; }

    public string DesignationCode { get; set; }

    public bool? isActive { get; set; }

    public bool? isDeleted { get; set; }

    public virtual ICollection<AssignLocationHistory> AssignLocationHistories { get; set; } = new List<AssignLocationHistory>();

    public virtual JD JD { get; set; }

    public virtual ICollection<tblEmployeeAttendancePayrollCalculation> tblEmployeeAttendancePayrollCalculations { get; set; } = new List<tblEmployeeAttendancePayrollCalculation>();

    public virtual ICollection<tblEmployee> tblEmployees { get; set; } = new List<tblEmployee>();

    public virtual ICollection<tblStoreBudget> tblStoreBudgets { get; set; } = new List<tblStoreBudget>();
}