// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class tblEmployeePunch
{
    public string UserID { get; set; }

    public DateTime PunchDate { get; set; }

    public TimeSpan PunchTime { get; set; }

    public string CreatedBy { get; set; }

    public DateTimeOffset CreatedOn { get; set; }

    public string LastUpdatedBy { get; set; }
}