// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class tblEmployeeDeduction
{
    public int ID { get; set; }

    public string ECode { get; set; }

    public string STCode { get; set; }

    public string MONTH { get; set; }

    public string Year { get; set; }

    public string PF { get; set; }

    public string ESIC { get; set; }

    public string TDS { get; set; }

    public string PTax { get; set; }

    public string Loan { get; set; }

    public string CashShort { get; set; }

    public string DieselDeduction { get; set; }

    public string Penality { get; set; }

    public string Lwf { get; set; }

    public DateTime? CreatedOn { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsDeleted { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public int? MonthNo { get; set; }

    public decimal? TotalDeductions { get; set; }

    public string LwfEmployeer { get; set; }

    public decimal? Monthly_Advance { get; set; }
}