// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class tblEmployeeSalaryAddon
{
    public int ID { get; set; }

    public string ECode { get; set; }

    public string STCode { get; set; }

    public int MONTH { get; set; }

    public string Arears { get; set; }

    public string Incentive { get; set; }

    public string Reimbursement { get; set; }

    public DateTime? CreatedOn { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsDeleted { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime? UpdatedOn { get; set; }
}