// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class tblEmployeeSepration
{
    public int EmployeeSeprationId { get; set; }

    public long EmployeeId { get; set; }

    public DateTime? LastDay { get; set; }

    public int? NoticePeriod { get; set; }

    public int ResignationTypeId { get; set; }

    public DateTime ResignationDate { get; set; }

    public string Remarks { get; set; }

    public bool? IsApprovedByManager { get; set; }

    public string ManagerRemarks { get; set; }

    public bool? IsRevoked { get; set; }

    public bool? IsApprovedByHR { get; set; }

    public string HRRemarks { get; set; }

    public bool? IsAbscond { get; set; }

    public string AbscondRemarks { get; set; }

    public string AbscondedBy { get; set; }

    public DateTime CreatedOn { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? LastUpdatedOn { get; set; }

    public string LastUpdatedBy { get; set; }

    public bool? IsActive { get; set; }

    public virtual tblEmployee Employee { get; set; }

    public virtual tblResignationType ResignationType { get; set; }
}