// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class tblEmployeePayableDay
{
    public string Ecode { get; set; }

    public string Month { get; set; }

    public int? BudgetMonthDays { get; set; }

    public int? Attendance { get; set; }

    public decimal? WeeklyOff { get; set; }

    public decimal? LeaveAdjust { get; set; }

    public decimal? PayableDays { get; set; }

    public DateTime? LastUpdatedOn { get; set; }
}