// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class tblEmpESICDatum
{
    public int ID { get; set; }

    public string Ecode { get; set; }

    public string STCode { get; set; }

    public string Month { get; set; }

    public string Year { get; set; }

    public decimal? monthlyGrossCTC { get; set; }

    public decimal? EmpESIC { get; set; }

    public decimal? EmprESIC { get; set; }

    public DateTime? CreatedOn { get; set; }

    public int? MonthNo { get; set; }
}