// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class tblEmployeeInActiveFile
{
    public int Id { get; set; }

    public int? EmpId { get; set; }

    public string FilePath { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsDeleted { get; set; }

    public DateTime? CreatedOn { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime? UpdatedOn { get; set; }

    /// <summary>
    /// What kind of document this file is: "Inactivation" (captured when the
    /// employee was made inactive) or "NOC". NULL on the rows that existed
    /// before this column was added and means the same as "Inactivation" -
    /// every query that predates the column simply ignores it.
    ///
    /// Constrained in the database (CK_tblEmployeeInActiveFiles_DocumentType)
    /// to NULL / 'Inactivation' / 'NOC'.
    /// </summary>
    public string DocumentType { get; set; }
}