// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class tblEmployeeAttendancePayrollCalculation
{
    public int EmployeeAttendancePayrollId { get; set; }

    public string Month { get; set; }

    public string Year { get; set; }

    public int? LocationCategoryId { get; set; }

    public int? DesignationId { get; set; }

    public string EmployeeName { get; set; }

    public string Ecode { get; set; }

    public long? EmployeeId { get; set; }

    public int? Attendance { get; set; }

    public long? EmployeeLeaveBalanceId { get; set; }

    public decimal? WeeklyOff { get; set; }

    public decimal? ExtraDays { get; set; }

    public decimal? Payroll { get; set; }

    public decimal? Salary { get; set; }

    public decimal? LeaveAdjust { get; set; }

    public virtual tblDesignation Designation { get; set; }

    public virtual tblEmployee Employee { get; set; }

    public virtual LocationCategory LocationCategory { get; set; }
}