// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class tblEmployee_Log
{
    public int LogId { get; set; }

    public string Ecode { get; set; }

    public string UserName { get; set; }

    public string ActionTaken { get; set; }

    public DateTime? ActionDate { get; set; }

    public string OldData { get; set; }

    public string NewData { get; set; }
}