// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class tblExperience
{
    public long ID { get; set; }

    public long? CID { get; set; }

    public string Name_of_Company { get; set; }

    public string Work_Location { get; set; }

    public string Position_Held { get; set; }

    public DateTime? From { get; set; }

    public DateTime? To { get; set; }

    public decimal? Last_CTC { get; set; }

    public decimal? InHand { get; set; }

    public DateTime? CreatedOn { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public string UpdatedBy { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsDeleted { get; set; }

    public int? TotalIndustryExperience_yrs { get; set; }

    public int? TotalRetailExperience_yrs { get; set; }

    public int? Notice_Period { get; set; }

    public decimal? Expected_CTC { get; set; }
}