// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class tblEmployeeDetail_temp
{
    public string Employee_Code { get; set; }

    public string LocBasedECode { get; set; }

    public string Name_of_Employee { get; set; }

    public string Posted_Location { get; set; }

    public string Joined_Location { get; set; }

    public string Sex { get; set; }

    public string D_O_B_ { get; set; }

    public string Department { get; set; }

    public string Designation { get; set; }

    public string Home_Town { get; set; }

    public string D_O_J_ { get; set; }

    public string D_O_L_ { get; set; }

    public string Resignation_Date { get; set; }

    public string Name_of_Bank { get; set; }

    public string A_c_No_ { get; set; }

    public string IFSC_Code { get; set; }

    public string Permanent_Addess { get; set; }

    public string Present_Address { get; set; }

    public string Mob_No_ { get; set; }

    public string Phone_No_ { get; set; }

    public string Email_Id { get; set; }

    public string Aadhar_No_ { get; set; }

    public string PAN_No_ { get; set; }

    public string Qualification { get; set; }

    public string Father_s_Name { get; set; }

    public string Mothers_Name { get; set; }

    public string Marital_Status { get; set; }

    public string Reporting_Head_ECode { get; set; }

    public string Reporting_Head_Name { get; set; }

    public string Relation { get; set; }

    public string CHILD_DOB { get; set; }

    public string Company { get; set; }

    public string Gross_Salary { get; set; }

    public string Joining_Salary { get; set; }

    public string Annual_CTC { get; set; }

    public string Sal_Structure { get; set; }

    public DateTime? D_O_J_Group { get; set; }

    public bool? P_F__Applicable_ { get; set; }

    public string P_F__No_ { get; set; }

    public string Previous_P_F__No_ { get; set; }

    public bool? E_S_I__Applicable_ { get; set; }

    public string ESIC_NO { get; set; }

    public string E_S_I__No_ { get; set; }

    public string Universal_A_c_Number { get; set; }

    public string Basic_Salary { get; set; }

    public string D_A_ { get; set; }

    public string H_R_A_ { get; set; }

    public string C_C_A_ { get; set; }

    public string Special_Allowance { get; set; }

    public string Extra_Allowance { get; set; }

    public string MONTHLY_CTC_ { get; set; }

    public string Annually_Net_CTC { get; set; }

    public string Salary_Expectation { get; set; }

    public int Conveyance { get; set; }

    public int Medical_Allowance { get; set; }

    public int Incentive { get; set; }

    public int Fooding_Allowance { get; set; }

    public int Leave_Encashment { get; set; }

    public int Medical_Reim { get; set; }

    public int Lta { get; set; }

    public int Bonus_Ex_Gratia { get; set; }

    public int Cca { get; set; }

    public int P_Tax { get; set; }

    public int L_W_F_ { get; set; }

    public int Inc_Paid { get; set; }

    public int Tds { get; set; }

    public int Esi { get; set; }

    public int Recovery { get; set; }

    public int Cash_Short { get; set; }

    public int Diesel_Deduction { get; set; }

    public int Penalty { get; set; }

    public int Lwf { get; set; }

    public int Medical { get; set; }

    public int Fuel___Maintenance { get; set; }

    public int Books___Periodicals { get; set; }

    public int Professional_Attire { get; set; }

    public int Driver_Wages { get; set; }

    public int Meal_Voucher { get; set; }

    public int Gross_Salary_2 { get; set; }

    public int Employeer_PF { get; set; }

    public int Employeer_ESI { get; set; }

    public int AC_NO_2 { get; set; }

    public int AC_NO_21 { get; set; }

    public int GRATITY { get; set; }

    public int T_D_S_ { get; set; }

    public string Payment_Mode { get; set; }

    public string Passport_No_ { get; set; }

    public string FATHER_DOB { get; set; }

    public string MOTHER_DOB { get; set; }

    public string SPOUSE_DOB { get; set; }

    public string CHILD_NAME_2 { get; set; }

    public string Relation_2 { get; set; }

    public string CHILD_DOB_2 { get; set; }

    public string LIC_No_ { get; set; }

    public string P_A_policy_no_ { get; set; }

    public string Mediclaim_No_ { get; set; }

    public string Fooding_Details { get; set; }

    public string Accomodation_Details { get; set; }

    public string Desig__Band { get; set; }

    public string Annual_Gross { get; set; }

    public string Hold_Salary__ { get; set; }

    public string Hold_Reason_Remark { get; set; }

    public string Reimbursement_A_c_No_ { get; set; }

    public string Reimbursement_Bank { get; set; }

    public string Notice_Days { get; set; }

    public string Date_of_Confirmation { get; set; }

    public string branch { get; set; }

    public string empstatus { get; set; }

    public string trfreason { get; set; }

    public string trfrdate { get; set; }

    public string trfremark { get; set; }

    public string senior { get; set; }

    public string junior { get; set; }

    public string icustomer { get; set; }

    public string hod { get; set; }

    public string rmanager { get; set; }

    public string jbname { get; set; }

    public string jobprofile { get; set; }

    public string subdesig { get; set; }

    public string sdsgrade { get; set; }

    public string states { get; set; }

    public bool? Is_Active { get; set; }

    public bool? Is_Store { get; set; }

    public long? Employee_Role_ID { get; set; }

    public string Role_Name { get; set; }
}