// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class tblfinalstoremaster
{
    public int Id { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }
}