// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class tblInterviewRound
{
    public int Id { get; set; }

    public int ScheduleId { get; set; }

    public int RoundId { get; set; }

    public int InterviewerId { get; set; }

    public string FeedBack { get; set; }

    public string Status { get; set; }

    public string InterviewerStatus { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }
}