// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class tblIncentiveAttachment
{
    public long AttachmentId { get; set; }

    public long IncentiveId { get; set; }

    public string FileName { get; set; }

    public string FileType { get; set; }

    public long? FileSizeBytes { get; set; }

    public string FilePath { get; set; }

    public DateTime UploadedAt { get; set; }

    public virtual tblIncentive Incentive { get; set; }
}