// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class tblIncentive
{
    public long IncentiveId { get; set; }

    public string Ecode { get; set; }

    public DateTime Month { get; set; }

    public decimal Amount { get; set; }

    public string Remarks { get; set; }

    public string CreatedBy { get; set; }

    public bool CmdApproved { get; set; }

    public bool HrApproved { get; set; }

    public int StatusId { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public int? CmdStatusId { get; set; }

    public int? HrStatusId { get; set; }

    public string CmdRemarks { get; set; }

    public string HrRemarks { get; set; }

    public virtual ICollection<tblIncentiveAttachment> tblIncentiveAttachments { get; set; } = new List<tblIncentiveAttachment>();
}