// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class tblJobPosition
{
    public int JobPositionId { get; set; }

    public int? StoreBudgetId { get; set; }

    public string JobId { get; set; }

    public bool IsFilled { get; set; }

    public DateTime? CreatedOn { get; set; }

    public string CreatedBy { get; set; }

    public virtual tblStoreBudget StoreBudget { get; set; }
}