// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class tblLocation_2025_06_13
{
    public string STCode { get; set; }

    public string LocationName { get; set; }

    public int? StateId { get; set; }

    public DateTime? CreatedOn { get; set; }

    public int LocationId { get; set; }
}