// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class tblLeaveType
{
    public int LeaveTypeId { get; set; }

    public string LeaveTypeName { get; set; }

    public virtual ICollection<tblLeavePolicy> tblLeavePolicies { get; set; } = new List<tblLeavePolicy>();

    public virtual ICollection<tblLeaveRequest> tblLeaveRequests { get; set; } = new List<tblLeaveRequest>();
}