// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class tblLocationDesignationPolicyHistory
{
    public int HistoryId { get; set; }

    public int? LocationDesignationPolicyId { get; set; }

    public string LocationCategoryId { get; set; }

    public string LocationCategoryName { get; set; }

    public int? DesignationId { get; set; }

    public string DesignationName { get; set; }

    public decimal? TotalAttendanceFrom { get; set; }

    public decimal? TotalAttendanceTo { get; set; }

    public decimal? WeeklyOff { get; set; }

    public int? ForWhichWeeks { get; set; }

    public string Month_Year { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsDeleted { get; set; }

    public string ActionType { get; set; }

    public string ActionBy { get; set; }

    public DateTime? ActionOn { get; set; }
}