// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class tblLeaveRequest
{
    public long LeaveRequestId { get; set; }

    public long? EmployeeId { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime EndDate { get; set; }

    public string Reason { get; set; }

    public int? StatusId { get; set; }

    public long? ReportingManagerId { get; set; }

    public DateTime? CreatedOn { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public string UDF1 { get; set; }

    public string UDF2 { get; set; }

    public string UDF3 { get; set; }

    public string UDF4 { get; set; }

    public string UDF5 { get; set; }

    public string UDF6 { get; set; }

    public string UDF7 { get; set; }

    public string LastUpdatedBy { get; set; }

    public int? LeaveTypeId { get; set; }

    public string Remarks { get; set; }

    public bool? IsRevoked { get; set; }

    public bool? FirstHalf { get; set; }

    public bool? SecondHalf { get; set; }

    public bool? FullDay { get; set; }

    public long? RelieverEmployeeId { get; set; }

    public virtual tblEmployee Employee { get; set; }

    public virtual tblLeaveType LeaveType { get; set; }

    public virtual tblEmployee ReportingManager { get; set; }

    public virtual tblStatus Status { get; set; }
}