// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class tblLocationDesignationPolicyBackup_2025_02_09
{
    public string LocationCategoryId { get; set; }

    public string LocationCategoryName { get; set; }

    public int? DesignationId { get; set; }

    public string DesignationName { get; set; }

    public string TotalAttendance { get; set; }

    public decimal? WeeklyOff { get; set; }

    public int LocationDesignationPolicyId { get; set; }

    public int? ForWhichWeeks { get; set; }

    public string Month_Year { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsDeleted { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedOn { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public decimal? TotalAttendanceFrom { get; set; }

    public decimal? TotalAttendanceTo { get; set; }
}