// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class tblLocationDesignationPolicyMonth
{
    public string LocationCategoryId { get; set; }

    public string LocationCategoryName { get; set; }

    public int? DesignationId { get; set; }

    public string DesignationName { get; set; }

    public string TotalAttendance { get; set; }

    public decimal? WeeklyOff { get; set; }

    public int LocationDesignationPolicyId { get; set; }

    public int? ForWhichWeeks { get; set; }

    public string Month_Year { get; set; }
}