// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class tblNewCandidateApproval
{
    public long ApprovalId { get; set; }

    public long CandidateId { get; set; }

    public int? HRApprovalStatus { get; set; }

    public int? AuditApprovalStatus { get; set; }

    public string HRReviewedBy { get; set; }

    public string AuditReviewedBy { get; set; }

    public DateTime? CreatedOn { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public string UDF1 { get; set; }

    public string UDF2 { get; set; }

    public string UDF3 { get; set; }

    public string UDF4 { get; set; }

    public string UDF5 { get; set; }

    public string UDF6 { get; set; }

    public string UDF7 { get; set; }

    public string LastUpdatedBy { get; set; }

    public int? ClusterManagerApprovalStatus { get; set; }

    public string ClusterManagerReviewBy { get; set; }

    public DateTime? HRApprovedOn { get; set; }

    public DateTime? AuditApprovedOn { get; set; }

    public DateTime? ClusterManagerApprovedOn { get; set; }

    public string ClusterManagerRemarks { get; set; }

    public string AuditRemarks { get; set; }

    public string HRRemarks { get; set; }

    public virtual tblStatus AuditApprovalStatusNavigation { get; set; }

    public virtual Candidate Candidate { get; set; }

    public virtual tblStatus HRApprovalStatusNavigation { get; set; }
}