// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class tblNatureOfWork
{
    public int NatureOfWorkId { get; set; }

    public string WorkName { get; set; }
}