// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class tblPaidInCash
{
    public long PaidInCashId { get; set; }

    public string E_CODE { get; set; }

    public decimal? AMOUNT { get; set; }

    public string MONTH { get; set; }

    public string LOCATION { get; set; }

    public DateTime? createdon { get; set; }
}