// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class tblPaidByBank_27102025
{
    public string Ecode { get; set; }

    public string A_C { get; set; }

    public string PaidByBank { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedOn { get; set; }

    public string LastUpdatedBy { get; set; }

    public DateTime? LastUpdatedOn { get; set; }

    public int tblPaidByBankId { get; set; }

    public DateTime? Date { get; set; }

    public string UTR { get; set; }
}