// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class tblPayment
{
    public long PaymentId { get; set; }

    public string E_CODE { get; set; }

    public decimal? Incentive { get; set; }

    public decimal? ARREAR { get; set; }

    public decimal? Overtime { get; set; }

    public decimal? Fooding_Allowance { get; set; }

    public decimal? Mobile_Bill { get; set; }

    public string MONTH { get; set; }

    public decimal? Bonus { get; set; }
}