// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class tblPF_Approval
{
    public int bigid { get; set; }

    public string E_Code { get; set; }

    public string _Month { get; set; }

    public string Challan_No { get; set; }

    public string Attachment { get; set; }

    public string createdBy { get; set; }

    public DateTime? createdOn { get; set; }

    public string updatedBy { get; set; }

    public DateTime? updatedOn { get; set; }

    public bool? isactive { get; set; }

    public bool? isdeleted { get; set; }

    public string EmployeeEcode { get; set; }
}