// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class tblRefrence
{
    public long ID { get; set; }

    public long? CID { get; set; }

    public string FullName { get; set; }

    public string Company_Designation { get; set; }

    public string Contact_Details { get; set; }

    public string Bussiness_Details { get; set; }

    public DateTime? CreatedOn { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public string UpdatedBy { get; set; }

    public bool? IsActive { get; set; }
}