// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class tblRescheduleLog
{
    public int LogId { get; set; }

    public int ScheduleId { get; set; }

    public int ApplicantId { get; set; }

    public DateTime? OldInterviewDateTime { get; set; }

    public DateTime? NewInterviewDateTime { get; set; }

    public string OldInterviewMode { get; set; }

    public string NewInterviewMode { get; set; }

    public string OldInterviewLocation { get; set; }

    public string NewInterviewLocation { get; set; }

    public string RescheduledBy { get; set; }

    public DateTime? RescheduledOn { get; set; }

    public string Notes { get; set; }
}