// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class tblRetention
{
    public int RetentionId { get; set; }

    public string LocCode { get; set; }

    public string Location { get; set; }

    public string Ecode { get; set; }

    public string Name { get; set; }

    public DateTime? JoiningDate { get; set; }

    public string EmpStatus { get; set; }

    public bool? RetentionApplicable { get; set; }

    public string RetBonus { get; set; }

    public DateTime? DateOfComplition { get; set; }

    public DateTime? ResignationStartDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreateDate { get; set; }

    public string LastUpdatedBy { get; set; }

    public DateTime? LastUpdatedOn { get; set; }

    public bool? IsDeleted { get; set; }

    public bool? IsActive { get; set; }
}