// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class tblRequestType
{
    public int RequestTypeId { get; set; }

    public string RequestTypeName { get; set; }

    public string Description { get; set; }

    public virtual ICollection<tblAttendanceRegularizationRequest> tblAttendanceRegularizationRequests { get; set; } = new List<tblAttendanceRegularizationRequest>();
}