// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class tblResignationType
{
    public int ResignationTypeId { get; set; }

    public string ResignationTypeName { get; set; }

    public virtual ICollection<tblAbscondingReason> tblAbscondingReasons { get; set; } = new List<tblAbscondingReason>();

    public virtual ICollection<tblBlacklistReason> tblBlacklistReasons { get; set; } = new List<tblBlacklistReason>();

    public virtual ICollection<tblEmployeeSepration> tblEmployeeSeprations { get; set; } = new List<tblEmployeeSepration>();
}