// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class tblRetentionBonu
{
    public int RetentionID { get; set; }

    public string ECode { get; set; }

    public DateTime LetterIssueDate { get; set; }

    public DateTime RetentionStart { get; set; }

    public DateTime RetentionEnd { get; set; }

    public decimal MonthlyGrossAtIssue { get; set; }

    public decimal Percentage { get; set; }

    public decimal BonusAmount { get; set; }

    public bool? Accepted { get; set; }

    public DateTime? AcceptedOn { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsDeleted { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public DateTime? CreatedOn { get; set; }
}