// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class tblShiftMap
{
    public int ShiftMapID { get; set; }

    public string Ecode { get; set; }

    public int ShiftID { get; set; }

    public bool? IsActive { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedOn { get; set; }

    public DateTime? LastUpdatedOn { get; set; }

    public string LastUpdatedBy { get; set; }

    public virtual tblEmployee EcodeNavigation { get; set; }

    public virtual tblShiftMaster Shift { get; set; }
}