// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class tblStatus
{
    public int StatusId { get; set; }

    public string StatusName { get; set; }

    public DateTime? CreatedOn { get; set; }

    public string CreatedBy { get; set; }

    public virtual ICollection<AttendanceRecord> AttendanceRecords { get; set; } = new List<AttendanceRecord>();

    public virtual ICollection<Candidate> Candidates { get; set; } = new List<Candidate>();

    public virtual ICollection<tblAttendanceRegularizationRequest> tblAttendanceRegularizationRequestLpApprovalStatuses { get; set; } = new List<tblAttendanceRegularizationRequest>();

    public virtual ICollection<tblAttendanceRegularizationRequest> tblAttendanceRegularizationRequestManagerApprovalStatuses { get; set; } = new List<tblAttendanceRegularizationRequest>();

    public virtual ICollection<tblAttendanceRegularizationRequest> tblAttendanceRegularizationRequestStatusNavigations { get; set; } = new List<tblAttendanceRegularizationRequest>();

    public virtual ICollection<tblLeaveRequest> tblLeaveRequests { get; set; } = new List<tblLeaveRequest>();

    public virtual ICollection<tblNewCandidateApproval> tblNewCandidateApprovalAuditApprovalStatusNavigations { get; set; } = new List<tblNewCandidateApproval>();

    public virtual ICollection<tblNewCandidateApproval> tblNewCandidateApprovalHRApprovalStatusNavigations { get; set; } = new List<tblNewCandidateApproval>();
}