// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class tblShiftMaster
{
    public int ShiftID { get; set; }

    public string ShiftName { get; set; }

    public TimeSpan StartTime { get; set; }

    public TimeSpan EndTime { get; set; }

    public bool IsActive { get; set; }

    public string CreatedBy { get; set; }

    public DateTime CreatedOn { get; set; }

    public DateTime? LastUpdatedOn { get; set; }

    public string LastUpdatedBy { get; set; }

    public virtual ICollection<Candidate> Candidates { get; set; } = new List<Candidate>();

    public virtual ICollection<EmployeeShiftHistory> EmployeeShiftHistories { get; set; } = new List<EmployeeShiftHistory>();

    public virtual ICollection<tblEmployee> tblEmployees { get; set; } = new List<tblEmployee>();

    public virtual ICollection<tblShiftMap> tblShiftMaps { get; set; } = new List<tblShiftMap>();
}