// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class tblState
{
    public int StateId { get; set; }

    public string StateName { get; set; }

    public int RegionId { get; set; }

    public DateTime? CreatedOn { get; set; }
}