// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class tblScheduleInterview
{
    public int ScheduleId { get; set; }

    public int ApplicantId { get; set; }

    public string CandidateName { get; set; }

    public DateTime InterviewDateTime { get; set; }

    public string InterviewMode { get; set; }

    public string InterviewLocation { get; set; }

    public string Notes { get; set; }

    public int RoundId { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public string DeletedBy { get; set; }

    public DateTime? CreatedOn { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public DateTime? DeletedOn { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsDeleted { get; set; }
}