// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class tblServiceCategory
{
    public int ServiceCategoryId { get; set; }

    public string ServiceName { get; set; }

    public virtual ICollection<tblVendorMaster> tblVendorMasters { get; set; } = new List<tblVendorMaster>();
}