// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class tblSalaryProcess
{
    public int SalaryProcessId { get; set; }

    public string Ecode { get; set; }

    public string Location_Code { get; set; }

    public string LocationName { get; set; }

    public string EmployeeName { get; set; }

    public string Designation { get; set; }

    public string Department { get; set; }

    public string MonthYear { get; set; }

    public decimal? TtlBgtDays { get; set; }

    public decimal? ActualTtlDays { get; set; }

    public decimal? GF { get; set; }

    public decimal? Machine { get; set; }

    public decimal? MachineWP { get; set; }

    public decimal? MANUAL { get; set; }

    public decimal? ActualWeekly { get; set; }

    public decimal? PresentWeeklyOff { get; set; }

    public int? HolidayOff { get; set; }

    public decimal? PaybleDays { get; set; }

    public decimal? ExtraDays { get; set; }

    public decimal? Absent { get; set; }

    public decimal? LWP { get; set; }

    public decimal? AdjustedDays { get; set; }

    public string Status { get; set; }

    public decimal? BasicSalaryBud { get; set; }

    public decimal? HRABud { get; set; }

    public decimal? CCABud { get; set; }

    public decimal? SpecialAllowanceBud { get; set; }

    public decimal? DABud { get; set; }

    public decimal? ReimbersmentBud { get; set; }

    public decimal? FuelAndMaintenanceBud { get; set; }

    public decimal? BooksAndPeriodicalsBud { get; set; }

    public decimal? ProfessionalAttireBud { get; set; }

    public decimal? DriverWagesBud { get; set; }

    public decimal? MobileBillBud { get; set; }

    public decimal? MealVoucherBud { get; set; }

    public decimal? MonthlyGrossCTCBud { get; set; }

    public decimal? BasicSalaryActual { get; set; }

    public decimal? HRAActual { get; set; }

    public decimal? CCAActual { get; set; }

    public decimal? SpecialAllowanceActual { get; set; }

    public decimal? DAActual { get; set; }

    public decimal? ExtraDayAllowance { get; set; }

    public decimal? ReimbersmentActual { get; set; }

    public decimal? FuelAndMaintenanceActual { get; set; }

    public decimal? BooksAndPeriodicalsActual { get; set; }

    public decimal? ProfessionalAttireActual { get; set; }

    public decimal? DriverWagesActual { get; set; }

    public decimal? MobileBillActual { get; set; }

    public decimal? MealVoucherActual { get; set; }

    public decimal? PFEmployee { get; set; }

    public decimal? PFEmployer { get; set; }

    public decimal? PFTotal { get; set; }

    public decimal? ESICEmployee { get; set; }

    public decimal? ESICEmployer { get; set; }

    public decimal? ESICTotal { get; set; }

    public decimal? TDS { get; set; }

    public decimal? PTax { get; set; }

    public decimal? Loan { get; set; }

    public decimal? CashShort { get; set; }

    public decimal? DieselDeduction { get; set; }

    public decimal? Penality { get; set; }

    public decimal? Lwf { get; set; }

    public decimal? TotalDeductions { get; set; }

    public decimal? Incentive { get; set; }

    public decimal? ARREAR { get; set; }

    public decimal? Overtime { get; set; }

    public decimal? FoodingAllowance { get; set; }

    public decimal? MobileBill { get; set; }

    public decimal? MonthlyGrossCTCActual { get; set; }

    public decimal? MonthlyGrossCTCActualAfterDeductionAndAddOns { get; set; }

    public decimal? Payble_Days2 { get; set; }

    public decimal? LeaveUsed { get; set; }

    public decimal? OpeningEL { get; set; }

    public decimal? EarnedLeaveAcquired { get; set; }

    public decimal? EarnedLeaveUsed { get; set; }

    public decimal? EarnedLeaveBalance { get; set; }

    public decimal? OpeningCL { get; set; }

    public decimal? CasualLeaveAcquired { get; set; }

    public decimal? CasualLeaveUsed { get; set; }

    public decimal? CasualLeaveBalance { get; set; }

    public decimal? OpeningCompoOff { get; set; }

    public decimal? CompoOffAcquired { get; set; }

    public decimal? CompoOffUsed { get; set; }

    public decimal? CompoOffBalance { get; set; }

    public string MONTH { get; set; }

    public int? BatchNo { get; set; }

    public DateTime? RunAt { get; set; }

    public string SalaryStatus { get; set; }

    public int? ID { get; set; }

    public DateTime? CreatedOn { get; set; }

    public string CreatedBy { get; set; }
}