// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class tblVendorMaster
{
    public long VendorId { get; set; }

    public string ContractorName { get; set; }

    public string ContractorCode { get; set; }

    public string ServiceCategory { get; set; }

    public string NatureOfWork { get; set; }

    public DateTime? ContractStartDate { get; set; }

    public DateTime? ContractEndDate { get; set; }

    public bool? ContractStatus { get; set; }

    public DateTime? CreatedOn { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public string UpdatedBy { get; set; }

    public string DeletedBy { get; set; }

    public DateTime? DeletedOn { get; set; }

    public bool? IsActive { get; set; }

    public int? ServiceCategoryId { get; set; }

    public int? ContarctStatusId { get; set; }

    public virtual tblContractStatus ContarctStatus { get; set; }

    public virtual tblServiceCategory ServiceCategoryNavigation { get; set; }

    public virtual ICollection<tblVendorBankDetail> tblVendorBankDetails { get; set; } = new List<tblVendorBankDetail>();

    public virtual ICollection<tblVendorComplianceDetail> tblVendorComplianceDetails { get; set; } = new List<tblVendorComplianceDetail>();

    public virtual ICollection<tblVendorContactDetail> tblVendorContactDetails { get; set; } = new List<tblVendorContactDetail>();
}