// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class tblVendorContactDetail
{
    public long VendorContactId { get; set; }

    public string RegisteredAddress { get; set; }

    public string SiteAddress { get; set; }

    public string ContactPersonName { get; set; }

    public long? MobileNumber { get; set; }

    public string Email { get; set; }

    public long VendorId { get; set; }

    public DateTime? CreatedOn { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public virtual tblVendorMaster Vendor { get; set; }
}