// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class tblVendorComplianceDetail
{
    public long VendorComplianceId { get; set; }

    public string PAN { get; set; }

    public string GSTIN { get; set; }

    public string PFRegistrationNumber { get; set; }

    public long? ESICRegistrationNumber { get; set; }

    public string LabourLicenseNumber { get; set; }

    public long VendorId { get; set; }

    public DateTime? CreatedOn { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public string UpdatedBy { get; set; }

    public virtual tblVendorMaster Vendor { get; set; }
}