// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class tblVendorBankDetail
{
    public long VendorBankId { get; set; }

    public string BankName { get; set; }

    public string BranchName { get; set; }

    public string AccountHolderName { get; set; }

    public long? AccountNumber { get; set; }

    public string IFSCCode { get; set; }

    public string AccountType { get; set; }

    public string PaymentMode { get; set; }

    public string BeneficiaryName { get; set; }

    public bool? GSTApplicability { get; set; }

    public bool? BankVerificationStatus { get; set; }

    public long VendorId { get; set; }

    public DateTime? CreatedOn { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public string UpdatedBy { get; set; }

    public virtual tblVendorMaster Vendor { get; set; }
}