// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class TempEmpAttendance
{
    public string EmpCode { get; set; }

    public DateTime? AttendanceDate { get; set; }

    public TimeSpan? PunchIn { get; set; }

    public TimeSpan? PunchOut { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedOn { get; set; }

    public string LastUpdatedBy { get; set; }
}