// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class tempCandidateDoc
{
    public long Id { get; set; }

    public long? DID { get; set; }

    public long? EmpId { get; set; }

    public long? CID { get; set; }

    public string FilePath { get; set; }

    public string FileType { get; set; }

    public string FileSize { get; set; }

    public DateTime? CreatedOn { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime? ApprovedOn { get; set; }

    public string ApprovedBy { get; set; }

    public bool? Is_Approved { get; set; }

    public bool IsActive { get; set; }

    public bool IsDeleted { get; set; }

    public bool IsRejected { get; set; }

    public bool IsUpdated { get; set; }
}