// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class tempTblFamily
{
    public long ID { get; set; }

    public long? FID { get; set; }

    public long? EmpId { get; set; }

    public long? CID { get; set; }

    public string Family_Member_Name { get; set; }

    public bool? Is_FamilyMemberName_Approved { get; set; }

    public string Relation { get; set; }

    public bool? Is_Relation_Approved { get; set; }

    public DateTime? DOB { get; set; }

    public bool? Is_DOB_Approved { get; set; }

    public DateTime? AppliedOn { get; set; }

    public string AppliedBy { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public string UpdatedBy { get; set; }

    public string ApprovedBy { get; set; }

    public DateTime? ApprovedOn { get; set; }

    public bool? Is_Approved { get; set; }

    public bool IsActive { get; set; }

    public bool IsDeleted { get; set; }

    public bool IsRejected { get; set; }

    public bool IsUpdated { get; set; }
}