// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class tempTblExperience
{
    public long ID { get; set; }

    public long? EID { get; set; }

    public long? EmpId { get; set; }

    public long? CID { get; set; }

    public string Name_of_Company { get; set; }

    public bool? Is_NameOfCompany_Approved { get; set; }

    public string Work_Location { get; set; }

    public bool? Is_WorkLocation_Approved { get; set; }

    public string Position_Held { get; set; }

    public bool? Is_PositionHeld_Approved { get; set; }

    public DateTime? From { get; set; }

    public bool? Is_FromDate_Approved { get; set; }

    public DateTime? To { get; set; }

    public bool? Is_ToDate_Approved { get; set; }

    public decimal? Last_CTC { get; set; }

    public bool? Is_LastCTC_Approved { get; set; }

    public DateTime? AppliedOn { get; set; }

    public string AppliedBy { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public string UpdatedBy { get; set; }

    public string ApprovedBy { get; set; }

    public DateTime? ApprovedOn { get; set; }

    public bool? Is_Approved { get; set; }

    public bool IsActive { get; set; }

    public bool IsDeleted { get; set; }

    public bool IsRejected { get; set; }

    public bool IsUpdated { get; set; }
}