// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class tempTblEmployee
{
    public int Id { get; set; }

    public long EmployeeId { get; set; }

    public long? CandidateId { get; set; }

    public string TITLE { get; set; }

    public bool? Is_TITLE_Approved { get; set; }

    public string FirstName { get; set; }

    public bool? Is_FirstName_Approved { get; set; }

    public string MiddleName { get; set; }

    public bool? Is_MiddleName_Approved { get; set; }

    public string LastName { get; set; }

    public bool? Is_LastName_Approved { get; set; }

    public string FULL_NAME { get; set; }

    public bool? Is_FULLNAME_Approved { get; set; }

    public string FATHER_S_NAME { get; set; }

    public bool? Is_FATHERSNAME_Approved { get; set; }

    public string MOTHER_S_NAME { get; set; }

    public bool? Is_MOTHERSNAME_Approved { get; set; }

    public string Husband_Name { get; set; }

    public bool? Is_HusbandName_Approved { get; set; }

    public string PLACE_OF_BIRTH { get; set; }

    public bool? Is_PlaceOfBirth_Approved { get; set; }

    public string PAN_NO { get; set; }

    public bool? Is_PANNO_Approved { get; set; }

    public string AADHAR_NO { get; set; }

    public bool? Is_AADHARNO_Approved { get; set; }

    public string NAME_ON_ADHAR { get; set; }

    public bool? Is_NAMEONADHAR_Approved { get; set; }

    public DateTime? DOB { get; set; }

    public bool? Is_DOB_Approved { get; set; }

    public string PRESENT_ADDRESS { get; set; }

    public bool? Is_PRESENTADDRESS_Approved { get; set; }

    public string PERMANENT_ADDRESS { get; set; }

    public bool? Is_PERMANENTADDRESS_Approved { get; set; }

    public string PRESENT_ADDRESS_PIN_CODE { get; set; }

    public bool? Is_PRESENTPIN_Approved { get; set; }

    public string PERMANENT_ADDRESS_PIN_CODE { get; set; }

    public bool? Is_PERMANENTPIN_Approved { get; set; }

    public string MARITIAL_STATUS { get; set; }

    public bool? Is_MARITIALSTATUS_Approved { get; set; }

    public string MOBILE { get; set; }

    public bool? Is_MOBILE_Approved { get; set; }

    public string EMAIL_ADDRESS { get; set; }

    public bool? Is_EMAILADDRESS_Approved { get; set; }

    public string BENEFICIARY_ADDRESS { get; set; }

    public bool? Is_BENEFICIARYADDRESS_Approved { get; set; }

    public string NATIONALITY { get; set; }

    public bool? Is_NATIONALITY_Approved { get; set; }

    public string RELIGION { get; set; }

    public bool? Is_RELIGION_Approved { get; set; }

    public string BANK_NAME { get; set; }

    public bool? Is_BANKNAME_Approved { get; set; }

    public string A_C_NO { get; set; }

    public bool? Is_ACNO_Approved { get; set; }

    public string BANK_IFSC_CODE { get; set; }

    public bool? Is_IFSC_Approved { get; set; }

    public bool? ISRELATIVEINCOMPANY { get; set; }

    public bool? Is_ISRELATIVEINCOMPANY_Approved { get; set; }

    public string AppliedBy { get; set; }

    public DateTime? AppliedOn { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public string ApprovedBy { get; set; }

    public DateTime? ApprovedOn { get; set; }

    public bool? Is_Approved { get; set; }

    public bool? Is_Rejected { get; set; }
}