// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class TempEcode
{
    public string ST_MNGMT_ { get; set; }

    public string Column1 { get; set; }

    public string Column2 { get; set; }

    public string Column3 { get; set; }

    public string Column4 { get; set; }
}