// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class TmpEmployeeUpdate
{
    public string Employee_Code { get; set; }

    public string Name_of_Employee { get; set; }

    public string Posted_Location { get; set; }

    public string Joined_Location { get; set; }
}