// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class TREND_V2R_Emp_DATum
{
    public DateTime? DATE { get; set; }

    public string E_Code { get; set; }

    public string Name_of_Employee { get; set; }

    public string Father_s_Name { get; set; }

    public string Card_No { get; set; }

    public DateTime? DOJ { get; set; }

    public string DOL { get; set; }

    public double? Branch_Code { get; set; }

    public string Branch { get; set; }

    public double? Dept_Code { get; set; }

    public string Department { get; set; }

    public double? Location_Code { get; set; }

    public string Location { get; set; }

    public string Zone { get; set; }

    public string SAP_Code { get; set; }

    public string State { get; set; }

    public double? Month { get; set; }

    public double? Year { get; set; }

    public string Designation { get; set; }

    public string PF_No { get; set; }

    public string SS_No { get; set; }

    public string ESI_No { get; set; }

    public string PAN { get; set; }

    public double? CL { get; set; }

    public double? EL { get; set; }

    public double? SL { get; set; }

    public double? Spl { get; set; }

    public double? Total_Days { get; set; }

    public double? Absent { get; set; }

    public double? Holidays { get; set; }

    public double? Present { get; set; }

    public double? Payable_Days { get; set; }

    public double? Basic_Rate { get; set; }

    public double? Basic { get; set; }

    public double? DA_Rate { get; set; }

    public double? DA { get; set; }

    public double? HRA_Rate { get; set; }

    public double? HRA { get; set; }

    public double? CCA_Rate { get; set; }

    public double? CCA { get; set; }

    public double? Conveyance_Rate { get; set; }

    public double? Conveyance { get; set; }

    public double? Arrears { get; set; }

    public double? Medical_Allowance_Rate { get; set; }

    public double? Medical_Allowance { get; set; }

    public double? Incentive_Rate { get; set; }

    public double? Incentive { get; set; }

    public double? Fooding_Allowance_Rate { get; set; }

    public double? Fooding_Allowance { get; set; }

    public double? Special_Allowance_Rate { get; set; }

    public double? Special_Allowance { get; set; }

    public double? Extra_Allowance_Rate { get; set; }

    public double? Extra_Allowance { get; set; }

    public double? Leave_Encashment_Rate { get; set; }

    public double? Leave_Encashment { get; set; }

    public double? Medical_Reim_Rate { get; set; }

    public double? Medical_Reim { get; set; }

    public double? Lta_Rate { get; set; }

    public double? Lta { get; set; }

    public double? Bonus_Ex_Gratia_Rate { get; set; }

    public double? Bonus_Ex_Gratia { get; set; }

    public double? Cca_Rate1 { get; set; }

    public double? Cca_1 { get; set; }

    public double? N_A { get; set; }

    public double? N_A1 { get; set; }

    public double? N_A2 { get; set; }

    public double? N_A3 { get; set; }

    public double? OT_Hours { get; set; }

    public double? Overtime { get; set; }

    public double? EL_Days { get; set; }

    public double? EL_Amount { get; set; }

    public double? Gross_Salary { get; set; }

    public double? PTax_Rate { get; set; }

    public double? PTax_Ded_ { get; set; }

    public double? LWF_Rate { get; set; }

    public double? LWF_Ded { get; set; }

    public double? Inc_Paid_Rate { get; set; }

    public double? Inc_Paid_Ded { get; set; }

    public double? Tds_Rate { get; set; }

    public double? Tds_Ded { get; set; }

    public double? Esi_Rate { get; set; }

    public double? Esi_Ded { get; set; }

    public double? Recovery_Rate { get; set; }

    public double? Recovery_Ded { get; set; }

    public double? Cash_Short_Rate { get; set; }

    public double? Cash_Short_Ded { get; set; }

    public double? Diesel_Deduction_Rate { get; set; }

    public double? Diesel_Deduction_Ded { get; set; }

    public double? Penalty_Rate { get; set; }

    public double? Penalty_Ded { get; set; }

    public double? Lwf_Rate_1 { get; set; }

    public double? Lwf_Ded_1 { get; set; }

    public double? Employee_PF_Cont { get; set; }

    public double? Oempl_Vpf { get; set; }

    public double? Ovpfrate { get; set; }

    public double? Employee_VPF_Cont { get; set; }

    public double? Employer_PF_Cont { get; set; }

    public double? Employer_FPF_Cont_ { get; set; }

    public double? Employee_ESI_Cont { get; set; }

    public double? Employer_ESI_Cont { get; set; }

    public double? Loan_Installment { get; set; }

    public double? TDS_Ded1 { get; set; }

    public double? Monthly_Advance { get; set; }

    public double? Total_Allowances { get; set; }

    public double? Total_Deductions { get; set; }

    public double? Net_Payable { get; set; }

    public double? Balance_CL { get; set; }

    public double? Balance_EL { get; set; }

    public double? Balance_SL { get; set; }

    public string Arrdue { get; set; }

    public double? Paycash { get; set; }

    public double? Paychq { get; set; }

    public double? Paybank { get; set; }

    public string Mode_of_Payment { get; set; }

    public string Bank_Name { get; set; }

    public string IFSC_Code { get; set; }

    public string BANK_A_C_NO_ { get; set; }

    public double? Ratewage { get; set; }

    public string Holdyn { get; set; }

    public string Hold_Remarks { get; set; }

    public string PF_Applicable_ { get; set; }

    public string FPF_Applicable_ { get; set; }

    public string ESI_Applicable_ { get; set; }

    public double? PF_Salary { get; set; }

    public double? FPF_Salary { get; set; }

    public double? ESI_Salary { get; set; }

    public double? Dliperc { get; set; }

    public double? Edliperc { get; set; }

    public double? Admnperc { get; set; }

    public double? LWF_Cont { get; set; }

    public string Erpecode { get; set; }

    public double? Account_2 { get; set; }

    public double? Account_21 { get; set; }

    public double? Account_22 { get; set; }

    public string Band { get; set; }

    public string Joined_Location { get; set; }

    public string Universal_A_c { get; set; }

    public double? Weekly_Offs { get; set; }

    public double? Compensatory_Off { get; set; }

    public DateTime? DOB { get; set; }

    public string Aadhano { get; set; }

    public string Cmonthyr { get; set; }
}