// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class Tt_IncentiveBulk
    {
        public int RowNo { get; set; }
        [StringLength(50)]
        public string Ecode { get; set; }
        public DateTime Month { get; set; }
        [Column("Amount", TypeName = "decimal(12,2)")]
        public decimal Amount { get; set; }
        public string Remarks { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        public int? CmdStatusId { get; set; }
        public int? HrStatusId { get; set; }
        public string CmdRemarks { get; set; }
        public string HrRemarks { get; set; }
    }
}
