// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class Tt_IncentiveAttachment
    {
        [StringLength(510)]
        public string FileName { get; set; }
        [StringLength(200)]
        public string FileType { get; set; }
        public long FileSizeBytes { get; set; }
        [StringLength(1000)]
        public string FilePath { get; set; }
    }
}
