// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class ufn_GetEmpHolidayCounts_ForMonthResult
    {
        public int? WeekdaysHolidayCount { get; set; }
        public int? FinalSatHolidayCount { get; set; }
    }
}
