// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class ufn_GetEmpAttendanceSnapshotResult
    {
        [StringLength(20)]
        public string Ecode { get; set; }
        [StringLength(10)]
        public string Location_Code { get; set; }
        [Column("Location Name")]
        [StringLength(255)]
        public string LocationName { get; set; }
        [Column("Employee Name")]
        [StringLength(50)]
        public string EmployeeName { get; set; }
        [StringLength(255)]
        public string designation { get; set; }
        [StringLength(255)]
        public string department { get; set; }
        [Column("Month-Year")]
        [StringLength(50)]
        public string MonthYear { get; set; }
        [Column("ttl bgt days", TypeName = "decimal(17,2)")]
        public decimal ttlbgtdays { get; set; }
        [Column("actualttl days", TypeName = "decimal(18,1)")]
        public decimal actualttldays { get; set; }
        [StringLength(50)]
        public string Machine { get; set; }
        [StringLength(50)]
        public string MANUAL { get; set; }
        [Column("actualweekly", TypeName = "decimal(17,2)")]
        public decimal actualweekly { get; set; }
        [Column("presentweeklyoff", TypeName = "decimal(17,2)")]
        public decimal presentweeklyoff { get; set; }
        public int HolidayOff { get; set; }
        [Column("paybledays", TypeName = "decimal(15,2)")]
        public decimal paybledays { get; set; }
        [Column("extradays", TypeName = "decimal(17,2)")]
        public decimal extradays { get; set; }
        [Column("Absent", TypeName = "decimal(17,2)")]
        public decimal Absent { get; set; }
        [Column("LWP", TypeName = "decimal(18,2)")]
        public decimal LWP { get; set; }
        [StringLength(11)]
        public string Status { get; set; }
        [Column("BasicSalary(Bud.)", TypeName = "decimal(18,2)")]
        public decimal BasicSalaryBud { get; set; }
        [Column("HRA(Bud.)", TypeName = "decimal(18,2)")]
        public decimal HRABud { get; set; }
        [Column("CCA(Bud.)", TypeName = "decimal(18,2)")]
        public decimal CCABud { get; set; }
        [Column("SpecialAllowance(Bud.)", TypeName = "decimal(18,2)")]
        public decimal SpecialAllowanceBud { get; set; }
        [Column("DA(Bud.)", TypeName = "decimal(18,2)")]
        public decimal DABud { get; set; }
        [Column("Reimbersment(Bud.)", TypeName = "decimal(18,2)")]
        public decimal ReimbersmentBud { get; set; }
        [Column("Fuel and Maintenance(Bud.)", TypeName = "decimal(18,2)")]
        public decimal FuelandMaintenanceBud { get; set; }
        [Column("Books and Periodicals(Bud.)", TypeName = "decimal(18,2)")]
        public decimal BooksandPeriodicalsBud { get; set; }
        [Column("Professional Attire(Bud.)", TypeName = "decimal(18,2)")]
        public decimal ProfessionalAttireBud { get; set; }
        [Column("Driver Wages(Bud.)", TypeName = "decimal(18,2)")]
        public decimal DriverWagesBud { get; set; }
        [Column("Mobile Bill(Bud.)", TypeName = "decimal(18,2)")]
        public decimal MobileBillBud { get; set; }
        [Column("Meal Voucher(Bud.)", TypeName = "decimal(18,2)")]
        public decimal MealVoucherBud { get; set; }
        [Column("Monthly Gross CTC(Bud.)", TypeName = "decimal(18,2)")]
        public decimal? MonthlyGrossCTCBud { get; set; }
        [Column("BasicSalary(Actual)", TypeName = "decimal(18,2)")]
        public decimal BasicSalaryActual { get; set; }
        [Column("HRA(Actual)", TypeName = "decimal(18,2)")]
        public decimal HRAActual { get; set; }
        [Column("CCA(Actual)", TypeName = "decimal(18,2)")]
        public decimal CCAActual { get; set; }
        [Column("SpecialAllowance(Actual)", TypeName = "decimal(18,2)")]
        public decimal SpecialAllowanceActual { get; set; }
        [Column("DA(Actual)", TypeName = "decimal(18,2)")]
        public decimal DAActual { get; set; }
        [StringLength(50)]
        public string ExtraDayAllowance { get; set; }
        [Column("Reimbersment(Actual)", TypeName = "decimal(18,2)")]
        public decimal ReimbersmentActual { get; set; }
        [Column("Fuel and Maintenance(Actual)", TypeName = "decimal(18,2)")]
        public decimal FuelandMaintenanceActual { get; set; }
        [Column("Books and Periodicals(Actual)", TypeName = "decimal(18,2)")]
        public decimal BooksandPeriodicalsActual { get; set; }
        [Column("Professional Attire(Actual)", TypeName = "decimal(18,2)")]
        public decimal ProfessionalAttireActual { get; set; }
        [Column("Driver Wages(Actual)", TypeName = "decimal(18,2)")]
        public decimal DriverWagesActual { get; set; }
        [Column("Mobile Bill(Actual)", TypeName = "decimal(18,2)")]
        public decimal MobileBillActual { get; set; }
        [Column("Meal Voucher(Actual)", TypeName = "decimal(18,2)")]
        public decimal MealVoucherActual { get; set; }
        [Column("PF(Employee)")]
        public decimal PFEmployee { get; set; }
        [Column("PF(Employeer)")]
        public decimal PFEmployeer { get; set; }
        [Column("PF(Total)")]
        [StringLength(100)]
        public string PFTotal { get; set; }
        [Column("ESIC(Employee)")]
        public decimal ESICEmployee { get; set; }
        [Column("ESIC(Employeer)")]
        public decimal ESICEmployeer { get; set; }
        [Column("ESIC(Total)")]
        [StringLength(100)]
        public string ESICTotal { get; set; }
        [StringLength(100)]
        public string TDS { get; set; }
        [StringLength(100)]
        public string PTax { get; set; }
        [StringLength(100)]
        public string Loan { get; set; }
        [StringLength(100)]
        public string CashShort { get; set; }
        [StringLength(100)]
        public string DieselDeduction { get; set; }
        [StringLength(100)]
        public string Penality { get; set; }
        [StringLength(100)]
        public string Lwf { get; set; }
        [Column("TotalDeductions", TypeName = "decimal(18,2)")]
        public decimal TotalDeductions { get; set; }
        [StringLength(50)]
        public string Incentive { get; set; }
        [StringLength(50)]
        public string ARREAR { get; set; }
        [Column("Overtime", TypeName = "decimal(18,2)")]
        public decimal Overtime { get; set; }
        [Column("Fooding_Allowance", TypeName = "decimal(18,2)")]
        public decimal Fooding_Allowance { get; set; }
        [Column("Mobile_Bill", TypeName = "decimal(18,2)")]
        public decimal Mobile_Bill { get; set; }
        [Column("Monthly Gross CTC(Actual)", TypeName = "decimal(18,2)")]
        public decimal MonthlyGrossCTCActual { get; set; }
        [Column("Monthly Gross CTC(Actual After Deduction AND AddONS)", TypeName = "decimal(18,2)")]
        public decimal MonthlyGrossCTCActualAfterDeductionANDAddONS { get; set; }
        [Column("Payble_Days", TypeName = "decimal(15,2)")]
        public decimal Payble_Days { get; set; }
        [Column("Leave-Used", TypeName = "decimal(5,2)")]
        public decimal LeaveUsed { get; set; }
        [Column("Opening EL", TypeName = "decimal(18,1)")]
        public decimal OpeningEL { get; set; }
        [Column("EarnedLeaveAcquired", TypeName = "decimal(10,2)")]
        public decimal EarnedLeaveAcquired { get; set; }
        [Column("EarnedLeaveUsed", TypeName = "decimal(10,2)")]
        public decimal EarnedLeaveUsed { get; set; }
        [Column("EarnedLeaveBalance", TypeName = "decimal(10,2)")]
        public decimal EarnedLeaveBalance { get; set; }
        [Column("Opening CL", TypeName = "decimal(18,1)")]
        public decimal OpeningCL { get; set; }
        [Column("CasualLeaveAcquired", TypeName = "decimal(10,2)")]
        public decimal CasualLeaveAcquired { get; set; }
        [Column("CasualLeaveUsed", TypeName = "decimal(10,2)")]
        public decimal CasualLeaveUsed { get; set; }
        [Column("CasualLeaveBalance", TypeName = "decimal(10,2)")]
        public decimal CasualLeaveBalance { get; set; }
        [Column("Opening CompoOff", TypeName = "decimal(18,1)")]
        public decimal OpeningCompoOff { get; set; }
        [Column("CompoOffAcquired", TypeName = "decimal(10,2)")]
        public decimal CompoOffAcquired { get; set; }
        [Column("CompoOffUsed", TypeName = "decimal(10,2)")]
        public decimal CompoOffUsed { get; set; }
        [Column("CompoOffBalance", TypeName = "decimal(10,2)")]
        public decimal CompoOffBalance { get; set; }
        [StringLength(50)]
        public string MONTH { get; set; }
        public int? BatchNo { get; set; }
        public DateTime RunAt { get; set; }
        public long ID { get; set; }
    }
}
