// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class ufn_StoreStateResult
    {
        [StringLength(10)]
        public string StCode { get; set; }
        public bool? IsChecked { get; set; }
        public bool? IsIndeterminate { get; set; }
        [StringLength(13)]
        public string State { get; set; }
    }
}
