// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class ufn_GetDesignationsResult
    {
        public int DesignationId { get; set; }
        [StringLength(255)]
        public string DesignationName { get; set; }
        public DateTime? CreatedOn { get; set; }
    }
}
