// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class UserTokenTable
{
    public int Id { get; set; }

    public string Ecode { get; set; }

    public string EmailAddress { get; set; }

    public int EmployeeId { get; set; }

    public string Role { get; set; }

    public string ReportHeadEcode { get; set; }

    public int? Reportheadid { get; set; }

    public string RefreshToken { get; set; }

    public DateTime? RefreshTokenExpiry { get; set; }
}