// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class usp_GetVendorEmployeesListByFilterResult
    {
        public long? EmployeeId { get; set; }
        [StringLength(50)]
        public string Ecode { get; set; }
        [StringLength(100)]
        public string FullName { get; set; }
        public DateTime? DOJ { get; set; }
        public bool? IsActive { get; set; }
        [StringLength(100)]
        public string DepartmentName { get; set; }
        [StringLength(100)]
        public string DesignationName { get; set; }
        [StringLength(200)]
        public string ContractorName { get; set; }
        [StringLength(100)]
        public string ShiftName { get; set; }
        public DateTime? ContractStartDate { get; set; }
        public DateTime? ContractEndDate { get; set; }
    }
}
