// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class usp_GetStoreRoutingStatusByLocaionIdResult
    {
        public int StoreRoutingMasterId { get; set; }
        [StringLength(200)]
        public string StagingName { get; set; }
        [StringLength(300)]
        public string RoutingName { get; set; }
        [StringLength(100)]
        public string BgtTimeline { get; set; }
        public int StagingSequence { get; set; }
        public int RoutingSequence { get; set; }
        public int? TransactionId { get; set; }
        public int? LocationId { get; set; }
        [StringLength(300)]
        public string Remarks { get; set; }
        public DateTime? ActionDate { get; set; }
        public int? ActionById { get; set; }
        [StringLength(2147483647)]
        public string Attachments { get; set; }
        [StringLength(9)]
        public string Status { get; set; }
    }
}
