// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class usp_GetLocationByRoleResult
    {
        [StringLength(10)]
        public string STCode { get; set; }
        [StringLength(255)]
        public string LocationName { get; set; }
        [StringLength(1000)]
        public string ZoneName { get; set; }
        [StringLength(100)]
        public string RegionName { get; set; }
        [StringLength(30)]
        public string ClusterName { get; set; }
        [StringLength(100)]
        public string StateName { get; set; }
        public bool? IsActive { get; set; }
        public bool? IsDeleted { get; set; }
        [StringLength(50)]
        public string OpeningDate { get; set; }
        public int LocationId { get; set; }
        public int? RoleId { get; set; }
        [StringLength(100)]
        public string RoleName { get; set; }
        [StringLength(100)]
        public string RoleValue { get; set; }
    }
}
