// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class usp_LoadContractorDetailsResult
    {
        [StringLength(200)]
        public string ContractorName { get; set; }
        [StringLength(50)]
        public string ContractorCode { get; set; }
        [StringLength(200)]
        public string ServiceCategory { get; set; }
        [StringLength(200)]
        public string NatureOfWork { get; set; }
        [StringLength(500)]
        public string RegisteredAddress { get; set; }
        [StringLength(500)]
        public string SiteAddress { get; set; }
        [StringLength(50)]
        public string PAN { get; set; }
        [StringLength(50)]
        public string GSTIN { get; set; }
        public bool? IsActive { get; set; }
        public int? EmployeeCount { get; set; }
    }
}
