// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class usp_IncentiveResult
    {
        public long IncentiveId { get; set; }
        [StringLength(50)]
        public string Ecode { get; set; }
        public DateTime Month { get; set; }
        [Column("Amount", TypeName = "decimal(12,2)")]
        public decimal Amount { get; set; }
        [StringLength(2147483647)]
        public string Remarks { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        public int StatusId { get; set; }
        [StringLength(50)]
        public string OverallStatusName { get; set; }
        public int? CmdStatusId { get; set; }
        [StringLength(50)]
        public string CmdStatusName { get; set; }
        public int? HrStatusId { get; set; }
        [StringLength(50)]
        public string HrStatusName { get; set; }
        [StringLength(2147483647)]
        public string CmdRemarks { get; set; }
        [StringLength(2147483647)]
        public string HrRemarks { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }
    }
}
