// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class usp_GetContractorDetailsByContractorCodeResult
    {
        [StringLength(7)]
        public string StatusMessage { get; set; }
        public long? ContractId { get; set; }
        [StringLength(200)]
        public string ContractorName { get; set; }
        [StringLength(100)]
        public string ContractorCode { get; set; }
        [StringLength(100)]
        public string ServiceCategory { get; set; }
        [StringLength(200)]
        public string NatureOfWork { get; set; }
        public DateTime? ContractStartDate { get; set; }
        public DateTime? ContractEndDate { get; set; }
        [StringLength(50)]
        public string ContractStatus { get; set; }
        [StringLength(500)]
        public string RegisteredAddress { get; set; }
        [StringLength(500)]
        public string SiteAddress { get; set; }
        [StringLength(200)]
        public string ContactPersonName { get; set; }
        [StringLength(50)]
        public string MobileNumber { get; set; }
        [StringLength(200)]
        public string EmailID { get; set; }
        [StringLength(50)]
        public string PAN { get; set; }
        [StringLength(50)]
        public string GSTIN { get; set; }
        [StringLength(100)]
        public string PFRegistrationNumber { get; set; }
        [StringLength(100)]
        public string ESICRegistrationNumber { get; set; }
        [StringLength(100)]
        public string LabourLicenseNumber { get; set; }
        [StringLength(200)]
        public string BankName { get; set; }
        [StringLength(200)]
        public string BranchName { get; set; }
        [StringLength(200)]
        public string AccountHolderName { get; set; }
        [StringLength(100)]
        public string AccountNumber { get; set; }
        [StringLength(50)]
        public string IFSCCode { get; set; }
        [StringLength(50)]
        public string AccountType { get; set; }
        [StringLength(50)]
        public string PaymentMode { get; set; }
        [StringLength(200)]
        public string BeneficiaryName { get; set; }
        public bool? GSTApplicability { get; set; }
        public bool? BankVerificationStatus { get; set; }
    }
}
