// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class usp_Location_UpdateGeoResult
    {
        public int LocationId { get; set; }
        [Column("StoreLong", TypeName = "decimal(9,6)")]
        public decimal? StoreLong { get; set; }
        [Column("StoreLat", TypeName = "decimal(9,6)")]
        public decimal? StoreLat { get; set; }
        [StringLength(255)]
        public string ADDRESS { get; set; }
        public int? AllowedRadiusMeters { get; set; }
        public bool IsGeofenceEnabled { get; set; }
    }
}
