// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class usp_GetEmployeeSeparationByIdResult
    {
        public int EmployeeSeprationId { get; set; }
        public long EmployeeId { get; set; }
        [StringLength(100)]
        public string FirstName { get; set; }
        [StringLength(100)]
        public string LastName { get; set; }
        [StringLength(201)]
        public string FullName { get; set; }
        public DateTime? JoinDate { get; set; }
        public int? DepartmentId { get; set; }
        [StringLength(255)]
        public string DepartmentName { get; set; }
        [StringLength(100)]
        public string ReportingHeadEcode { get; set; }
        [StringLength(201)]
        public string ReportingHeadName { get; set; }
        public DateTime? LastDay { get; set; }
        public int? NoticePeriod { get; set; }
        public int ResignationTypeId { get; set; }
        public DateTime ResignationDate { get; set; }
        [StringLength(255)]
        public string Remarks { get; set; }
        public bool? IsApprovedByManager { get; set; }
        public bool? IsApprovedByHR { get; set; }
        [StringLength(2147483647)]
        public string ManagerRemarks { get; set; }
        public bool? IsRevoked { get; set; }
        [Column("EarnedLeaveBalance", TypeName = "decimal(18,2)")]
        public decimal? EarnedLeaveBalance { get; set; }
    }
}
