// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class usp_GetEmployeeSeparationsResult
    {
        public int EmployeeSeprationId { get; set; }
        public long EmployeeId { get; set; }
        public DateTime? LastDay { get; set; }
        public int? NoticePeriod { get; set; }
        public int ResignationTypeId { get; set; }
        public DateTime ResignationDate { get; set; }
        [StringLength(255)]
        public string Remarks { get; set; }
        public bool? IsApprovedByManager { get; set; }
        public bool? IsApprovedByHR { get; set; }
        public bool? IsRevoked { get; set; }
        [StringLength(8)]
        public string ReportingHeadStatus { get; set; }
        [StringLength(8)]
        public string HRStatus { get; set; }
        [StringLength(8)]
        public string Status { get; set; }
        [Column("EarnedLeaveBalance", TypeName = "decimal(18,2)")]
        public decimal? EarnedLeaveBalance { get; set; }
    }
}
