// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class usp_Sync_tblLocation_FromLinkedServerResult
    {
        public int? InsertedEmployees { get; set; }
        public int? UpdatedEmployees { get; set; }
        public int? InsertedRoles { get; set; }
    }
}
