// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class usp_MonthWeekwiseAttendanceResult
    {
        [StringLength(4000)]
        public string Month { get; set; }
        public int? WeekRow { get; set; }
        public DateTime? WeekStart { get; set; }
        public DateTime? WeekEnd { get; set; }
        public int? WorkingDaysInRow { get; set; }
        public int? TotalAttendance { get; set; }
        public int? WeeklyOff { get; set; }
        [StringLength(10)]
        public string OffPolicy { get; set; }
        [StringLength(25)]
        public string RangeLabel { get; set; }
    }
}
