// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class usp_GetStoreRoutingMastersResult
    {
        public int Id { get; set; }
        public int StagingSequence { get; set; }
        [StringLength(200)]
        public string StagingName { get; set; }
        public int RoutingSequence { get; set; }
        [StringLength(300)]
        public string RoutingName { get; set; }
        [StringLength(100)]
        public string BgtTimeline { get; set; }
        public bool IsActive { get; set; }
        public DateTime CreatedDate { get; set; }
    }
}
