// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class usp_GetStoreRoutingStatusResult
    {
        public int StoreRoutingMasterId { get; set; }
        [StringLength(200)]
        public string StagingName { get; set; }
        [StringLength(300)]
        public string RoutingName { get; set; }
        [StringLength(100)]
        public string BgtTimeline { get; set; }
        public int? TransactionId { get; set; }
        public int? Remarks { get; set; }
        public int? ActionDate { get; set; }
        public int? ActionById { get; set; }
        public int? Attachment { get; set; }
    }
}
