// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class usp_GetMonthlyAttendanceSummary_WithStoreRules_Single_Dev1Result
    {
        public int Id { get; set; }
        [StringLength(20)]
        public string E_CODE { get; set; }
        public string MONTH { get; set; }
        [Column("MACHINE", TypeName = "decimal(9,2)")]
        public decimal? MACHINE { get; set; }
        [Column("MANUAL", TypeName = "decimal(9,2)")]
        public decimal? MANUAL { get; set; }
        [Column("GF", TypeName = "decimal(9,2)")]
        public decimal? GF { get; set; }
        [Column("TOTAL_PRESENT", TypeName = "decimal(9,2)")]
        public decimal? TOTAL_PRESENT { get; set; }
        [Column("NC_TOTAL_PRESENT", TypeName = "decimal(9,2)")]
        public decimal? NC_TOTAL_PRESENT { get; set; }
        [Column("PRESENT_ON_WEEKLYOFF", TypeName = "decimal(9,2)")]
        public decimal? PRESENT_ON_WEEKLYOFF { get; set; }
        public bool? IsActive { get; set; }
        public bool? IsDeleted { get; set; }
        public DateTime? CreatedOn { get; set; }
        public DateTime? UpdatedOn { get; set; }
        [StringLength(100)]
        public string CreatedBy { get; set; }
        [StringLength(100)]
        public string UpdatedBy { get; set; }
        [StringLength(10)]
        public string STCode { get; set; }
        [StringLength(255)]
        public string DesignationName { get; set; }
    }
}
