// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class usp_GetAttendanceRegularizationResult
    {
        [StringLength(20)]
        public string Ecode { get; set; }
        [StringLength(300)]
        public string EmpName { get; set; }
        [StringLength(10)]
        public string STCode { get; set; }
        [StringLength(255)]
        public string LocationName { get; set; }
        [StringLength(255)]
        public string DepartmentName { get; set; }
        [StringLength(255)]
        public string DesignationName { get; set; }
        public DateTime RequestDate { get; set; }
        [StringLength(500)]
        public string Reason { get; set; }
        [StringLength(20)]
        public string RM_ECODE { get; set; }
        [StringLength(300)]
        public string ReportManagerName { get; set; }
        public TimeSpan? PunchIn { get; set; }
        public TimeSpan? PunchOut { get; set; }
        [StringLength(50)]
        public string StatusName { get; set; }
        [StringLength(2147483647)]
        public string FileUrl { get; set; }
        public int? PunchTypeId { get; set; }
        [StringLength(20)]
        public string RequestTypeName { get; set; }
        [StringLength(2147483647)]
        public string EmployeeRemarks { get; set; }
        [StringLength(50)]
        public string ManagerStatus { get; set; }
        public DateTime? ManagerApprovalOn { get; set; }
        [StringLength(500)]
        public string ManagerRemarks { get; set; }
        [StringLength(50)]
        public string LpApprovalStatus { get; set; }
        public DateTime? LpApprovalOn { get; set; }
        [StringLength(500)]
        public string LpRemarks { get; set; }
    }
}
