// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class USP_SALARY_FINAL_STATUS_REPORTResult
    {
        [StringLength(20)]
        public string Ecode { get; set; }
        [StringLength(10)]
        public string Location_Code { get; set; }
        [StringLength(255)]
        public string LocationName { get; set; }
        [StringLength(50)]
        public string EmployeeName { get; set; }
        [Column("PayableSalary", TypeName = "decimal(18,2)")]
        public decimal PayableSalary { get; set; }
        [Column("GivenToBankAmount", TypeName = "decimal(38,2)")]
        public decimal GivenToBankAmount { get; set; }
        [Column("PaidByBankAmount", TypeName = "decimal(38,2)")]
        public decimal PaidByBankAmount { get; set; }
        [Column("PaidByCashAmount", TypeName = "decimal(38,2)")]
        public decimal PaidByCashAmount { get; set; }
        [Column("Difference", TypeName = "decimal(20,2)")]
        public decimal? Difference { get; set; }
        public int SalaryStatus { get; set; }
        public DateTime RunAt { get; set; }
    }
}
