// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class usp_GetEligibleEmployeesForSnapshotResult
    {
        [StringLength(20)]
        public string Ecode { get; set; }
        [StringLength(201)]
        public string EmployeeName { get; set; }
        [StringLength(10)]
        public string STCode { get; set; }
        [StringLength(255)]
        public string LocationName { get; set; }
        public bool? IsActive { get; set; }
        [StringLength(255)]
        public string DepartmentName { get; set; }
        [StringLength(255)]
        public string DesignationName { get; set; }
    }
}
