// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class usp_GetVendorByIdResult
    {
        public long VendorId { get; set; }
        [StringLength(200)]
        public string ContractorName { get; set; }
        [StringLength(100)]
        public string ContractorCode { get; set; }
        public DateTime? ContractStartDate { get; set; }
        public DateTime? ContractEndDate { get; set; }
        public int? ServiceCategoryId { get; set; }
        [StringLength(50)]
        public string ServiceCategoryName { get; set; }
        public int? ContarctStatusId { get; set; }
        [StringLength(250)]
        public string ContractName { get; set; }
    }
}
