// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class usp_GetVendorEmployeesByEcodeResult
    {
        public long EmployeeId { get; set; }
        [StringLength(20)]
        public string Ecode { get; set; }
        [Column("FULL NAME")]
        [StringLength(50)]
        public string FULLNAME { get; set; }
        [StringLength(100)]
        public string FirstName { get; set; }
        [StringLength(100)]
        public string MiddleName { get; set; }
        [StringLength(100)]
        public string LastName { get; set; }
        [Column("EMAIL ADDRESS")]
        [StringLength(150)]
        public string EMAILADDRESS { get; set; }
        [StringLength(2147483647)]
        public string MOBILE { get; set; }
        [Column("PRESENT ADDRESS")]
        [StringLength(500)]
        public string PRESENTADDRESS { get; set; }
        [Column("PRESENT ADDRESS PIN CODE")]
        [StringLength(10)]
        public string PRESENTADDRESSPINCODE { get; set; }
        public DateTime? DOB { get; set; }
        [StringLength(10)]
        public string GENDER { get; set; }
        [Column("UAN NO")]
        [StringLength(2147483647)]
        public string UANNO { get; set; }
        [Column("PAN NO")]
        [StringLength(15)]
        public string PANNO { get; set; }
        [Column("AADHAR NO")]
        [StringLength(20)]
        public string AADHARNO { get; set; }
        public bool? PFApplicable { get; set; }
        public bool? ESICApplicable { get; set; }
        public int? ShiftID { get; set; }
        [StringLength(50)]
        public string ShiftName { get; set; }
        [StringLength(100)]
        public string ESICNO { get; set; }
        [StringLength(50)]
        public string FatherName { get; set; }
        [Column("Husband Name")]
        [StringLength(100)]
        public string HusbandName { get; set; }
        [StringLength(100)]
        public string ContractorCode { get; set; }
        public int? DepartmentId { get; set; }
        [StringLength(255)]
        public string DepartmentName { get; set; }
        public int? DesignationId { get; set; }
        [StringLength(255)]
        public string DesignationName { get; set; }
        [StringLength(200)]
        public string ContractorName { get; set; }
        public int? LocationId { get; set; }
        [StringLength(255)]
        public string LocationName { get; set; }
        public bool? IsActive { get; set; }
        public DateTime? DOJ { get; set; }
        public DateTime? ContractStartDate { get; set; }
        public DateTime? ContractEndDate { get; set; }
        public decimal? BasicSalary { get; set; }
        public decimal? CCA { get; set; }
        public decimal? DA { get; set; }
        public decimal? ExtraAllowance { get; set; }
        public decimal? SpecialAllowance { get; set; }
        public decimal? HRA { get; set; }
        [Column("GROSS SALARY")]
        public decimal? GROSSSALARY { get; set; }
        public decimal? monthlyGrossCTC { get; set; }
        public decimal? annuallyNetCTC { get; set; }
    }
}
