// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class VendorContactType
    {
        [StringLength(600)]
        public string RegisteredAddress { get; set; }
        [StringLength(600)]
        public string SiteAddress { get; set; }
        [StringLength(400)]
        public string ContactPersonName { get; set; }
        public long? MobileNumber { get; set; }
        [StringLength(200)]
        public string Email { get; set; }
    }
}
