// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class VendorComplianceUpdateType
    {
        public long? VendorComplianceId { get; set; }
        [StringLength(40)]
        public string PAN { get; set; }
        [StringLength(40)]
        public string GSTIN { get; set; }
        [StringLength(200)]
        public string PFRegistrationNumber { get; set; }
        public long? ESICRegistrationNumber { get; set; }
        [StringLength(100)]
        public string LabourLicenseNumber { get; set; }
    }
}
