// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class VendorBankType
    {
        [StringLength(400)]
        public string BankName { get; set; }
        [StringLength(400)]
        public string BranchName { get; set; }
        [StringLength(400)]
        public string AccountHolderName { get; set; }
        public long? AccountNumber { get; set; }
        [StringLength(40)]
        public string IFSCCode { get; set; }
        [StringLength(100)]
        public string AccountType { get; set; }
        [StringLength(100)]
        public string PaymentMode { get; set; }
        [StringLength(400)]
        public string BeneficiaryName { get; set; }
        [StringLength(100)]
        public string GSTApplicability { get; set; }
        public bool? BankVerificationStatus { get; set; }
    }
}
