// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HRMSAPI.Data
{
    public partial class VendorEmployeeBulkTVP
    {
        [StringLength(400)]
        public string ContractorCode { get; set; }
        [StringLength(200)]
        public string FirstName { get; set; }
        [StringLength(200)]
        public string MiddleName { get; set; }
        [StringLength(200)]
        public string LastName { get; set; }
        [StringLength(100)]
        public string FatherName { get; set; }
        [StringLength(200)]
        public string Email { get; set; }
        [StringLength(40)]
        public string Mobile { get; set; }
        public int? DepartmentId { get; set; }
        public int? DesignationId { get; set; }
        public int? LocationId { get; set; }
        public DateTime? DOJ { get; set; }
        public DateTime? DOB { get; set; }
        [StringLength(20)]
        public string Gender { get; set; }
        [StringLength(100)]
        public string PANNo { get; set; }
        [StringLength(100)]
        public string AadharNo { get; set; }
        [StringLength(510)]
        public string PermanentAddress { get; set; }
        [StringLength(20)]
        public string PermanentAddressPinCode { get; set; }
        public int? ShiftId { get; set; }
        public DateTime? ContractStartDate { get; set; }
        public DateTime? ContractEndDate { get; set; }
        [StringLength(200)]
        public string HusbandName { get; set; }
    }
}
