// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class vw_AllCandidateDetail
{
    public string TITLE { get; set; }

    public string FIRST_NAME { get; set; }

    public string MIDDLE_NAME { get; set; }

    public string LAST_NAME { get; set; }

    public string HUSBAND_NAME { get; set; }

    public string FATHER_NAME { get; set; }

    public string MOTHER_NAME { get; set; }

    public string DESIGNATION { get; set; }

    public string LOCATION { get; set; }

    public DateTime? DOB { get; set; }

    public string GENDER { get; set; }

    public string DEPARTMENT { get; set; }

    public decimal GROSS_SALARY { get; set; }

    public string UAN_NO { get; set; }

    public string PAN_NO { get; set; }

    public string AADHAR_NO { get; set; }

    public string NAME_ON_AADHAR { get; set; }

    public string udf1 { get; set; }

    public string PLACE_OF_BIRTH { get; set; }

    public string PRESENT_ADDRESS { get; set; }

    public string PRESENT_ADDRESS_PIN_CODE { get; set; }

    public string PERMANENT_ADDRESS { get; set; }

    public string PERMANENT_ADDRESS_PIN_CODE { get; set; }

    public string EMP_CODE { get; set; }

    public string APPLICANT_CODE { get; set; }

    public string WEEKLY_OFF { get; set; }

    public string MARITIAL_STATUS { get; set; }

    public string MOBILE { get; set; }

    public string EMAIL_ADDRESS { get; set; }

    public string ISRELATIVEINCOMPANY { get; set; }

    public string NATIONALITY { get; set; }

    public string RELIGION { get; set; }

    public string BANK_NAME { get; set; }

    public string A_C_NO { get; set; }

    public string BANK_IFSC_CODE { get; set; }

    public string FAMILY_MEMBER_Name { get; set; }

    public string FAMILY_MEMBER_Relation { get; set; }

    public DateTime? FAMILY_MEMBER_DOB { get; set; }

    public string NameofCompany { get; set; }

    public string WORKLOCATION { get; set; }

    public string PositionHeld { get; set; }

    public DateTime From { get; set; }

    public DateTime To { get; set; }

    public string In_Hand_Salary { get; set; }

    public decimal LAST_CTC_ANNUAL_ { get; set; }

    public string HIGHEST_QUALIFICATION { get; set; }

    public string BENEFICIARY_ADDRESS { get; set; }

    public string PREV__EST_NO_ { get; set; }

    public string REFERENCE { get; set; }

    public string KRA { get; set; }

    public string KPI { get; set; }

    public string Ref_FullName { get; set; }

    public string Company_Designation { get; set; }

    public string Ref_Contact_Details { get; set; }

    public string Ref_Bussiness_Details { get; set; }

    public string IsActive { get; set; }

    public string IsDeleted { get; set; }

    public decimal TotalExperience { get; set; }

    public decimal SalaryExpectation { get; set; }

    public string AdditionalInfoApplicant { get; set; }

    public string Agreement { get; set; }

    public string IsApplicant { get; set; }

    public string IsApplicantApproved { get; set; }

    public string IsEvaluationAttachmentUploaded { get; set; }

    public string IsOfferLetterAttachmentUploaded { get; set; }

    public string IsInterviewVideoUploaded { get; set; }

    public string ReportHeadEcode { get; set; }

    public string DeclarationConfirmed { get; set; }

    public string Place { get; set; }

    public DateTime? DateOfFilling { get; set; }

    public string IsOtherAttachmentUploaded { get; set; }

    public string SkillType { get; set; }

    public string DifferentlyAbledRemarks { get; set; }

    public string DifferentlyAbledReason { get; set; }

    public string DifferentlyAbled { get; set; }
}