// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class vw_Bonus_Gratuity
{
    public string ECode { get; set; }

    public string Month { get; set; }

    public decimal? Gratuity { get; set; }

    public decimal? Bonus { get; set; }

    public decimal? BasicSalary_Bud__ { get; set; }

    public decimal? BasicSalary_Actual_ { get; set; }

    public decimal? Months { get; set; }

    public DateTime? DOJ { get; set; }

    public string DateOfLeft { get; set; }

    public decimal? Gross_with_Reimbursement_ { get; set; }

    public decimal? ActualGratuity { get; set; }

    public decimal? ActualBonus { get; set; }

    public string IsBonusApplicable { get; set; }
}