// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class vw_CandidateInterviewSchedule
{
    public string ApplicantId { get; set; }

    public string FIRST_NAME { get; set; }

    public string MIDDLE_NAME { get; set; }

    public string LAST_NAME { get; set; }

    public string StatusName { get; set; }

    public string DesignationName { get; set; }

    public string LocationName { get; set; }

    public DateTime InterviewDateTime { get; set; }

    public string InterviewMode { get; set; }

    public string Notes { get; set; }

    public string Interviewer { get; set; }

    public string InterviewerEcode { get; set; }

    public string InterviewLocation { get; set; }
}