// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class vw_CandidateStatusHistory
{
    public string APPLICANT_CODE { get; set; }

    public string ApplicantName { get; set; }

    public string OldStatusName { get; set; }

    public string NewStatusName { get; set; }

    public DateTime CreatedDate { get; set; }

    public string Ecode { get; set; }
}