// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class vw_DiffSalaryforBGTSEATMasterForSameGroup
{
    public string LOC_CODE { get; set; }

    public string DEPT_SNO { get; set; }

    public string DepartmentName { get; set; }

    public string DESG_SNO { get; set; }

    public string DesignationName { get; set; }

    public int? SeatBudget { get; set; }

    public string SalaryList { get; set; }
}