// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class vw_Emp_Attendance_Format
{
    public string Ecode { get; set; }

    public string Location_Code { get; set; }

    public string Location_Name { get; set; }

    public string Employee_Name { get; set; }

    public string designation { get; set; }

    public string department { get; set; }

    public string Month_Year { get; set; }

    public decimal ttl_bgt_days { get; set; }

    public decimal GF { get; set; }

    public decimal Actual_Machine_without_Penality_ { get; set; }

    public string Actual_Machine { get; set; }

    public string Regularise { get; set; }

    public decimal Present_Attendance { get; set; }

    public decimal Extra_Days { get; set; }

    public decimal Late_Penalty_Days { get; set; }

    public decimal WeekOffEarned { get; set; }

    public decimal Present_on_WeekOff { get; set; }

    public int HolidayOff { get; set; }

    public decimal paybledays { get; set; }

    public decimal Absent { get; set; }

    public decimal? LWP { get; set; }

    public decimal AdjustedDays { get; set; }

    public string Status { get; set; }

    public decimal BasicSalary_Bud__ { get; set; }

    public decimal HRA_Bud__ { get; set; }

    public decimal CCA_Bud__ { get; set; }

    public decimal SpecialAllowance_Bud__ { get; set; }

    public decimal DA_Bud__ { get; set; }

    public decimal Reimbersment_Bud__ { get; set; }

    public decimal Fuel_and_Maintenance_Bud__ { get; set; }

    public decimal Books_and_Periodicals_Bud__ { get; set; }

    public decimal Professional_Attire_Bud__ { get; set; }

    public decimal Driver_Wages_Bud__ { get; set; }

    public decimal Mobile_Bill_Bud__ { get; set; }

    public decimal Meal_Voucher_Bud__ { get; set; }

    public decimal? Monthly_Gross_CTC_Bud__ { get; set; }

    public decimal BasicSalary_Actual_ { get; set; }

    public decimal HRA_Actual_ { get; set; }

    public decimal CCA_Actual_ { get; set; }

    public decimal SpecialAllowance_Actual_ { get; set; }

    public decimal DA_Actual_ { get; set; }

    public string ExtraDayAllowance { get; set; }

    public decimal Reimbersment_Actual_ { get; set; }

    public decimal Fuel_and_Maintenance_Actual_ { get; set; }

    public decimal Books_and_Periodicals_Actual_ { get; set; }

    public decimal Professional_Attire_Actual_ { get; set; }

    public decimal Driver_Wages_Actual_ { get; set; }

    public decimal Mobile_Bill_Actual_ { get; set; }

    public decimal Meal_Voucher_Actual_ { get; set; }

    public decimal PF_Employee_ { get; set; }

    public decimal PF_Employeer_ { get; set; }

    public string PF_Total_ { get; set; }

    public decimal ESIC_Employee_ { get; set; }

    public decimal ESIC_Employeer_ { get; set; }

    public string ESIC_Total_ { get; set; }

    public string TDS { get; set; }

    public string PTax { get; set; }

    public string Loan { get; set; }

    public string CashShort { get; set; }

    public string DieselDeduction { get; set; }

    public string Penality { get; set; }

    public string Lwf { get; set; }

    public decimal TotalDeductions { get; set; }

    public string Incentive { get; set; }

    public string ARREAR { get; set; }

    public decimal Overtime { get; set; }

    public decimal Fooding_Allowance { get; set; }

    public decimal Mobile_Bill { get; set; }

    public decimal Monthly_Gross_CTC_Actual_ { get; set; }

    public decimal Monthly_Gross_CTC_Actual_After_Deduction_AND_AddONS_ { get; set; }

    public decimal Payble_Days { get; set; }

    public decimal Leave_Used { get; set; }

    public decimal Opening_EL { get; set; }

    public decimal EarnedLeaveAcquired { get; set; }

    public decimal EarnedLeaveUsed { get; set; }

    public decimal EarnedLeaveBalance { get; set; }

    public decimal Opening_CL { get; set; }

    public decimal CasualLeaveAcquired { get; set; }

    public decimal CasualLeaveUsed { get; set; }

    public decimal CasualLeaveBalance { get; set; }

    public decimal Opening_CompoOff { get; set; }

    public decimal CompoOffAcquired { get; set; }

    public decimal CompoOffUsed { get; set; }

    public decimal CompoOffBalance { get; set; }

    public string MONTH { get; set; }
}