// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class vw_FNF_AccountsList
{
    public long FNFId { get; set; }

    public long EmployeeId { get; set; }

    public string Ecode { get; set; }

    public string EmployeeName { get; set; }

    public DateTime? FNFDate { get; set; }

    public DateTime? DateOfLeaving { get; set; }

    public decimal? UnpaidSalaryAmount { get; set; }

    public decimal? Rate { get; set; }

    public int? Days { get; set; }

    public string SalaryMonth { get; set; }

    public decimal? Bonus { get; set; }

    public DateTime? BonusPeriodFrom { get; set; }

    public DateTime? BonusPeriodTill { get; set; }

    public decimal? Gratuity { get; set; }

    public string CalculatedAs { get; set; }

    public decimal? E_LeaveAmount { get; set; }

    public int? ELDays { get; set; }

    public decimal? NoticeSalary { get; set; }

    public decimal? OtherAddition1 { get; set; }

    public decimal? OtherAddition2 { get; set; }

    public decimal? OtherAddition3 { get; set; }

    public decimal? OtherAddition4 { get; set; }

    public decimal? LoanBalance { get; set; }

    public decimal? AdvanceBalance { get; set; }

    public decimal? OtherDeduction1 { get; set; }

    public decimal? OtherDeduction2 { get; set; }

    public decimal? OtherDeduction3 { get; set; }

    public decimal? OtherDeduction4 { get; set; }

    public decimal? TotalPayable { get; set; }

    public decimal? TDS { get; set; }

    public decimal? NetPayable { get; set; }

    public decimal? DepositOn { get; set; }

    public decimal? TotalAdditions { get; set; }

    public decimal? TotalDeductions { get; set; }

    public decimal? NetAmount { get; set; }

    public decimal? SendForPaymentAmount { get; set; }

    public decimal? AmountPaid { get; set; }

    public string PaymentStatus { get; set; }

    public string ChequeNo { get; set; }

    public DateTime? ChequeDate { get; set; }

    public string PaymentVoucherNo { get; set; }

    public string PaymentRemarks { get; set; }

    public string ResignationAttachment { get; set; }
}