// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class vw_InterviewFormDetail
{
    public string FIRST_NAME { get; set; }

    public string LAST_NAME { get; set; }

    public string PRESENT_ADDRESS { get; set; }

    public string MARITIAL_STATUS { get; set; }

    public string Place { get; set; }

    public string Location { get; set; }

    public bool? DeclarationConfirmed { get; set; }

    public DateTime? DateOfFilling { get; set; }

    public string Family_Member_Name { get; set; }

    public string FamilyRelation { get; set; }

    public string FamilyOccupation { get; set; }

    public string FamilyDependent { get; set; }

    public int? TotalIndustryExperience_yrs { get; set; }

    public int? TotalRetailExperience_yrs { get; set; }

    public int? Notice_Period { get; set; }

    public decimal? Last_CTC { get; set; }

    public decimal? Expected_CTC { get; set; }

    public string KRA { get; set; }

    public string KPI { get; set; }

    public string ReferenceFullName { get; set; }

    public string ReferenceCompanyDesignation { get; set; }

    public string ReferenceContactDetails { get; set; }

    public string ReferenceBusinessDetails { get; set; }
}