// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class vw_LeaveOpeningBalTable
{
    public int Id { get; set; }

    public string E_CODE { get; set; }

    public string MONTH { get; set; }

    public decimal? EL { get; set; }

    public decimal? CL { get; set; }

    public decimal? COMP_OFF { get; set; }

    public decimal? SL { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsDeleted { get; set; }

    public DateTime? CreatedOn { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public string CreatedBy { get; set; }

    public string UpdatedBy { get; set; }

    public decimal CompOffEarn { get; set; }
}