// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class vw_LeaveMaster_Download
{
    public string ECODE { get; set; }

    public string STCode { get; set; }

    public string LocationName { get; set; }

    public string FULL_NAME { get; set; }

    public string DepartmentName { get; set; }

    public string DesignationName { get; set; }

    public decimal? EarnedLeaveBalance { get; set; }

    public decimal? CasualLeaveBalance { get; set; }

    public string MONTH { get; set; }

    public string Year { get; set; }

    public decimal? Balance { get; set; }

    public decimal? Used { get; set; }

    public decimal? CompOffBalance { get; set; }

    public decimal? CompOff_CLS_Leave { get; set; }

    public decimal? CompOffAcquired { get; set; }

    public decimal? CompOffUsed { get; set; }

    public double? CL_Opening { get; set; }

    public decimal? CL_CLS_Leave { get; set; }

    public decimal? CasualLeaveAcquired { get; set; }

    public decimal? CasualLeaveUsed { get; set; }

    public double? EL_Opening { get; set; }

    public decimal? EL_CLS_Leave { get; set; }

    public decimal? EarnedLeaveAcquired { get; set; }

    public decimal? EarnedLeaveUsed { get; set; }

    public DateTime? LastCreditedMonth { get; set; }

    public DateTime? LastUpdatedOn { get; set; }

    public decimal? SickLeaveBalance { get; set; }

    public decimal? PaternityLeaveBalance { get; set; }

    public decimal? MaternityLeaveBalance { get; set; }

    public decimal? SickLeaveAcquired { get; set; }

    public decimal? SickLeaveUsed { get; set; }

    public decimal? PaternityLeaveAcquired { get; set; }

    public decimal? PaternityLeaveUsed { get; set; }

    public decimal? MaternityLeaveAcquired { get; set; }

    public decimal? MaternityLeaveUsed { get; set; }

    public decimal? TTL_CLS_Leave { get; set; }

    public decimal? TTL_OPN_Leave { get; set; }

    public decimal? TTL_EARN_Leave { get; set; }

    public decimal? TTL_AVAIL_Leave { get; set; }

    public long EmployeeLeaveBalanceId { get; set; }

    public string LocBasedECode { get; set; }

    public string GENDER { get; set; }

    public DateTime? JOINING_DATE { get; set; }

    public string MOBILE_NO_ { get; set; }

    public DateTime? LEAVING_DT { get; set; }

    public string STATUS { get; set; }

    public string BANK_NAME { get; set; }

    public string BANK_IFSC_CODE { get; set; }

    public string A_C_NO { get; set; }

    public string UAN_NO { get; set; }

    public string P_F__No_ { get; set; }

    public string ESICNO { get; set; }

    public string PAN_NO { get; set; }

    public string AADHAR_NO { get; set; }

    public bool? PFApplicable { get; set; }

    public bool? ESICApplicable { get; set; }

    public string F_P_F__Applicable_ { get; set; }

    public string O_T__Applicable_ { get; set; }

    public string P_Tax_Applicable_ { get; set; }

    public string Bonus_Applicable_ { get; set; }

    public string WK_OFF_PAY_APPLICABLE_ { get; set; }
}