// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class vw_Month_salary
{
    public string ecode { get; set; }

    public decimal? BasicSalary { get; set; }

    public decimal? HRA { get; set; }

    public decimal? CCA { get; set; }

    public decimal? SpecialAllowance { get; set; }

    public decimal? DA { get; set; }

    public decimal Reimbursement { get; set; }

    public string PF { get; set; }

    public string ESIC { get; set; }

    public decimal? MonthlyGrossCTC { get; set; }

    public string Month { get; set; }

    public decimal? Extra_Day_Allowance { get; set; }

    public string Incentive { get; set; }

    public string Arrears { get; set; }
}