// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class vw_PfMaster
{
    public string ECODE { get; set; }

    public string STCode { get; set; }

    public string LocationName { get; set; }

    public string FULL_NAME { get; set; }

    public string DepartmentName { get; set; }

    public string DesignationName { get; set; }

    public string Month { get; set; }

    public string Year { get; set; }

    public decimal? EmpPF { get; set; }

    public decimal? EmprPF { get; set; }
}