// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class vw_RegRequest1
{
    public string STcode { get; set; }

    public string St_NAME { get; set; }

    public int? ZONE { get; set; }

    public string E_CODE { get; set; }

    public string employee_NAME { get; set; }

    public string department { get; set; }

    public DateTime DATE { get; set; }

    public TimeSpan? Punch_In { get; set; }

    public TimeSpan? Punch_Out { get; set; }

    public string File_URL { get; set; }

    public string EMP__RAISED_REQUEST { get; set; }

    public string manager_Approve { get; set; }

    public string audit_lp__Approve { get; set; }
}