// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class vw_RBACHierarchy
{
    public int RoleId { get; set; }

    public string RoleName { get; set; }

    public int ModuleRefId { get; set; }

    public string ModuleName { get; set; }

    public bool? ModuleStatus { get; set; }

    public int ModuleId { get; set; }

    public int? SubModuleRefId { get; set; }

    public string SubModuleName { get; set; }

    public bool? SubModuleStatus { get; set; }

    public int SubModuleId { get; set; }

    public int? ActionRefId { get; set; }

    public string ActionName { get; set; }

    public bool? ActionStatus { get; set; }

    public int ActionId { get; set; }

    public int? ActionFurtherPartRefId { get; set; }

    public string ActionFurtherPartName { get; set; }

    public bool? FurtherPartStatus { get; set; }

    public int ActionFurtherPartId { get; set; }
}