// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class vw_RegRequest2
{
    public string Ecode { get; set; }

    public string FULL_NAME { get; set; }

    public string STCode { get; set; }

    public string DepartmentName { get; set; }

    public string DesignationName { get; set; }

    public DateTime RequestDate { get; set; }

    public string Reason { get; set; }

    public string StatusName { get; set; }

    public string Manager_Ecode { get; set; }

    public string Manager_Full_Name { get; set; }

    public TimeSpan? PunchIn { get; set; }

    public TimeSpan? PunchOut { get; set; }

    public string Remarks { get; set; }

    public string FileUrl { get; set; }

    public string EmployeeRemarks { get; set; }

    public string Manager_Status { get; set; }

    public DateTime? ManagerApprovalOn { get; set; }

    public string ManagerRemarks { get; set; }

    public string LP_Status { get; set; }

    public DateTime? LpApprovalOn { get; set; }

    public string LpRemarks { get; set; }
}