// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class vw_Salary_Format_Amit
{
    public string LOC_CD { get; set; }

    public string LOCATION { get; set; }

    public string LocBasedECode { get; set; }

    public string E_CODE { get; set; }

    public string NAME { get; set; }

    public string GENDER { get; set; }

    public DateTime? JOINING_DATE { get; set; }

    public string MOBILE_NO_ { get; set; }

    public DateTime? LEAVING_DT { get; set; }

    public string DEPARTMENT { get; set; }

    public string DESIGNATION { get; set; }

    public string STATUS { get; set; }

    public string BANK_NAME { get; set; }

    public string BANK_IFSC_CODE { get; set; }

    public string A_C_NO { get; set; }

    public string UAN_NO { get; set; }

    public string P_F__No_ { get; set; }

    public string ESICNO { get; set; }

    public string PAN_NO { get; set; }

    public string AADHAR_NO { get; set; }

    public string PFApplicable { get; set; }

    public string ESICApplicable { get; set; }

    public string F_P_F__Applicable_ { get; set; }

    public string O_T__Applicable_ { get; set; }

    public string P_Tax_Applicable_ { get; set; }

    public string Bonus_Applicable_ { get; set; }

    public string WK_OFF_PAY_APPLICABLE_ { get; set; }

    public decimal ACT_PRESENT_MTH_DAYS { get; set; }

    public string MANUAL_DAYS { get; set; }

    public int HolidayOff { get; set; }

    public decimal PAYABLE_DAYS { get; set; }

    public decimal GROSS_SALARY_PAYABLE { get; set; }

    public decimal NET_SALARY_PAYABLE { get; set; }

    public string SALARY_HOLD_Y_N { get; set; }

    public string SALARY_HOLD_REASON { get; set; }

    public string SALARY_SENT_TO_BANK { get; set; }

    public string SALARY_SENT_TO_BANK_DT { get; set; }

    public string BANK_PAYMENT_VAL { get; set; }

    public string PAID_IN_CASH { get; set; }

    public string PAID_IN_CASH_DT { get; set; }

    public string FINAL_STATUS__PAID_DUE_ { get; set; }

    public string REMARKS { get; set; }

    public string MINIMUM_WAGES { get; set; }

    public string Basic_Salary_Rate { get; set; }

    public string H_R_A__Rate { get; set; }

    public string D_A__RATE { get; set; }

    public string C_C_A__Rate { get; set; }

    public string SPECIAL_ALLOWANCE_RATE { get; set; }

    public decimal REIMB_RATE { get; set; }

    public decimal Fuel_and_Maintenance { get; set; }

    public decimal Books_and_Periodicals { get; set; }

    public decimal Professional_Attire { get; set; }

    public decimal Driver_Wages { get; set; }

    public decimal Mobile_Bill_ { get; set; }

    public decimal Meal_Voucher { get; set; }

    public string GROSS_SALARY_RATE { get; set; }

    public decimal BASIC_SALARY { get; set; }

    public decimal H_R_A_ { get; set; }

    public decimal D_A { get; set; }

    public decimal C_C_A_ { get; set; }

    public decimal SPECIAL_ALLOWANCE { get; set; }

    public decimal Fuel_and_Maintenance__REIMB_ { get; set; }

    public decimal Books_and_Periodicals__REIMB_ { get; set; }

    public decimal Professional_Attire__REIMB_ { get; set; }

    public decimal Driver_Wages__REIMB_ { get; set; }

    public decimal Mobile_Bill__REIMB_ { get; set; }

    public decimal Meal_Voucher__REIMB_ { get; set; }

    public decimal GROSS_EARNING { get; set; }

    public string OT__AMT { get; set; }

    public string INCENTIVE_AMT { get; set; }

    public decimal FOODING_ALL { get; set; }

    public decimal MOBILE_BILL { get; set; }

    public string ARRERS { get; set; }

    public decimal Overtime { get; set; }

    public string EXTRA_DAYS_ALLOWANCE { get; set; }

    public decimal FINAL_Gross_EARNING__Actual_After_Deduction_AND_AddONS_ { get; set; }

    public decimal REIMB { get; set; }

    public decimal? GROSS_EARNING__W_O_REIM_ { get; set; }

    public decimal TOTAL_DEDUCTION { get; set; }

    public decimal PF { get; set; }

    public decimal ESI { get; set; }

    public string TDS { get; set; }

    public string P_TAX { get; set; }

    public string CASH_SHORT { get; set; }

    public string DIESEL { get; set; }

    public string PENALTY { get; set; }

    public string LOAN { get; set; }

    public string MONTHLY_ADVANCE { get; set; }

    public decimal PF__EMPLOYER_ { get; set; }

    public decimal ESIC__EMPLOYER_ { get; set; }

    public string LEAVE_OP_BAL { get; set; }

    public string LEAVE_CLS_BAL { get; set; }

    public string LEAVE_EARN_THIS_MTH { get; set; }

    public string LEAVE_AVAILED { get; set; }

    public decimal EL_LEAVE_OP_BAL { get; set; }

    public decimal EL_LEAVE_CLS_BAL { get; set; }

    public decimal EL_LEAVE_EARN { get; set; }

    public decimal EL_LEAVE_AVAILED { get; set; }

    public decimal CL_LEAVE_OP_BAL { get; set; }

    public decimal CL_LEAVE_CLS_BAL { get; set; }

    public decimal CL_LEAVE_EARN { get; set; }

    public decimal CL_LEAVE_AVAILED { get; set; }

    public decimal CO_LEAVE_OP_BAL { get; set; }

    public decimal CO_LEAVE_CLS_BAL { get; set; }

    public decimal CO_LEAVE_EARN { get; set; }

    public decimal CO_LEAVE_AVAILED { get; set; }

    public string SL_LEAVE_OP_BAL { get; set; }

    public string SL_LEAVE_CLS_BAL { get; set; }

    public string SL_LEAVE_EARN { get; set; }

    public string SL_LEAVE_AVAILED { get; set; }

    public string BONUS_B_F_FROM_LAST_MTH { get; set; }

    public string BONUS_EARNED { get; set; }

    public string BONUS_C_F_FROM_NEXT_MTH { get; set; }

    public string GRATUITY_B_F_FROM_LAST_MTH { get; set; }

    public string GRATUITY_EARNED { get; set; }

    public string GRATUITY_C_F_FROM_NEXT_MTH { get; set; }

    public decimal ATTENDENCE { get; set; }

    public string MACHINE_ATTENDENCE { get; set; }

    public string MANUAL_PRESENT { get; set; }

    public string BGT_DAYS_WKL_OF { get; set; }

    public decimal ACT_DAYS_WK_OFF__WO_LEAVE_ { get; set; }

    public string HLD { get; set; }

    public string POW { get; set; }

    public decimal? GROSS_PAYABLE_DAYS__INI___W_O_LEAVE_ { get; set; }

    public decimal TOTAL_LEAVE_AVAILED { get; set; }

    public decimal EL_LEAVE_AVAILED_ { get; set; }

    public decimal CL_LEAVE_AVAILED_ { get; set; }

    public decimal CO_LEAVE_AVAILED_ { get; set; }

    public string SL_LEAVE_AVAILED_ { get; set; }

    public decimal PAYABLE_DAYS_ { get; set; }

    public decimal ABSENT { get; set; }

    public decimal EXTRA_DAY_CNT { get; set; }

    public string Month { get; set; }
}