// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class vw_salarystructure
{
    public string ecode { get; set; }

    public decimal? BasicSalary { get; set; }

    public decimal? HRA { get; set; }

    public decimal? CCA { get; set; }

    public decimal? SpecialAllowance { get; set; }

    public decimal? DA { get; set; }

    public decimal Reimbersment { get; set; }

    public decimal Fuel_and_Maintainence { get; set; }

    public decimal Books_and_Periodicals { get; set; }

    public decimal Professional_Attire { get; set; }

    public decimal Driver_Wages { get; set; }

    public decimal MOBILE_BIll { get; set; }

    public decimal Meal_Voucher { get; set; }

    public decimal? monthlyGrossCTC { get; set; }
}