// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class vw_tblLocation_UPC
{
    public int LocationId { get; set; }

    public string STCode { get; set; }

    public string LocationName { get; set; }

    public int? StateId { get; set; }

    public DateTime? CreatedOn { get; set; }

    public int? LocationCategoryId { get; set; }

    public int? ZoneId { get; set; }

    public int? RegionId { get; set; }

    public int? ClusterId { get; set; }

    public bool? IsActive { get; set; }

    public decimal? StoreLong { get; set; }

    public decimal? StoreLat { get; set; }

    public int? AllowedRadiusMeters { get; set; }

    public bool? IsDeleted { get; set; }

    public string OpeningDate { get; set; }

    public bool? IsAllowOvertimePayment { get; set; }

    public string ADDRESS { get; set; }

    public string LocationType { get; set; }

    public int? StateIdForMinWage { get; set; }
}