// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMSAPI.Data;

public partial class vw_TotalDeduction
{
    public string ECODE { get; set; }

    public string STCode { get; set; }

    public string LocationName { get; set; }

    public string FULL_NAME { get; set; }

    public string DepartmentName { get; set; }

    public string DesignationName { get; set; }

    public string MONTH { get; set; }

    public string Year { get; set; }

    public decimal? PF { get; set; }

    public decimal? ESIC { get; set; }

    public decimal? TDS { get; set; }

    public decimal? PTax { get; set; }

    public decimal? Loan { get; set; }

    public decimal? CashShort { get; set; }

    public decimal? DieselDeduction { get; set; }

    public decimal? Penality { get; set; }

    public decimal? Lwf { get; set; }

    public decimal? TotalDeductions { get; set; }
}