using System.Numerics;

public class EmployeeSalarySlip
{
    public string? ECode { get; set; }
    public long EmployeeId { get; set; }
    public string EmployeeName { get; set; }
    public string Designation { get; set; }
    public DateTime? DateofJoining { get; set; }
    public string LocationName { get; set; }
    public string Department { get; set; }
    public string BankAccountNo { get; set; }
    public string PAN_NO { get; set; }
    public string BankName { get; set; }
    public string NoofDays { get; set; }
    public string IfscCode { get; set; }
    public string UniversalAccountNumber { get; set; }
    public string EsicNo { get; set; }
    public decimal? BasicSalary { get; set; }
    public decimal? BasicSalaryBud { get; set; }
    public decimal? CCA { get; set; }
    public decimal? CCABud { get; set; }
    public decimal? DA { get; set; }
    public decimal? DABud { get; set; }
    public decimal? HRA { get; set; }
    public decimal? HRABud { get; set; }
    public string? Incentive { get; set; }
    public decimal? SpecialAllowance { get; set; }
    public decimal? SpecialAllowanceBud { get; set; }
    public decimal? ExtraAllowance { get; set; }
    public decimal? GrossEarningsCTCRef { get; set; }
    public decimal? GrossEarningsAmount { get; set; }
    public decimal? GrossNetPay { get; set; }
    public decimal? EPF { get; set; }
    public decimal? ESIC { get; set; }
    public string? TDS { get; set; }
    public string? PTax { get; set; }
    public string? Loan { get; set; }
    public string? CashShort { get; set; }
    public string? DieselDeduction { get; set; }
    public string? Penality { get; set; }
    public string? Lwf { get; set; }
    public decimal? Fuel_and_Maintenance { get; set; }
    public decimal? Books_and_Periodicals { get; set; }
    public decimal? Professional_Attire { get; set; }
    public decimal? Driver_Wages { get; set; }
    public decimal? Mobile_Bill { get; set; }
    public decimal? Meal_Voucher { get; set; }
    public decimal? GrossEarnings { get; set; }
    public decimal? GrossDeduction { get; set; }
    public decimal? FinalGrossEarnings_Netpay { get; set; }
    public decimal? FinalGrossEarnings_Netpay_rem { get; set; }
    public decimal? EC_PF { get; set; }
    public decimal? EC_EPS { get; set; }
    public decimal? ERC_PF { get; set; }
    public string E_VPF { get; set; }
    public decimal? Payble_Days { get; set; }
    public decimal? EarnedLeaveBalance { get; set; }
    public decimal? EarnedLeaveUsed { get; set; }
    public decimal? CasualLeaveBalance { get; set; }
    public decimal? CasualLeaveUsed { get; set; }
    public decimal? CompoOffBalance { get; set; }
    public decimal? CompoOffUsed { get; set; }

  
    public string MONTH { get; set; }
    public string? PF_Number { get; set; }
    
}

public class EmployeeSalarySlipDto
{
    public string? Ecode { get; set; }
    public string? Location_Code { get; set; }
    public string? LocationName { get; set; }
    public string? EmployeeName { get; set; }
    public string? Designation { get; set; }
    public string? Department { get; set; }
    public decimal? TtlBgtDays { get; set; }
    public decimal? ActualTtlDays { get; set; }
    public decimal? ActualWeekly { get; set; }
    public decimal? PresentWeeklyOff { get; set; }
    public decimal? PaybleDays { get; set; }
    public decimal? ExtraDays { get; set; }
    public decimal? Absent { get; set; }
    public decimal? BasicSalaryBud { get; set; }
    public decimal? HRABud { get; set; }
    public decimal? CCABud { get; set; }
    public decimal? SpecialAllowanceBud { get; set; }
    public decimal? DABud { get; set; }
    public decimal? ReimbersmentBud { get; set; }
    public decimal? FuelAndMaintenanceBud { get; set; }
    public decimal? BooksAndPeriodicalsBud { get; set; }
    public decimal? ProfessionalAttireBud { get; set; }
    public decimal? DriverWagesBud { get; set; }
    public decimal? MobileBillBud { get; set; }
    public decimal? MealVoucherBud { get; set; }
    public decimal? MonthlyGrossCTCBud { get; set; }
    public decimal? BasicSalaryActual { get; set; }
    public decimal? HRAActual { get; set; }
    public decimal? CCAActual { get; set; }
    public decimal? SpecialAllowanceActual { get; set; }
    public decimal? DAActual { get; set; }
    public string? ExtraDayAllowance { get; set; }
    public decimal? ReimbersmentActual { get; set; }
    public decimal? FuelAndMaintenanceActual { get; set; }
    public decimal? BooksAndPeriodicalsActual { get; set; }
    public decimal? ProfessionalAttireActual { get; set; }
    public decimal? DriverWagesActual { get; set; }
    public decimal? MobileBillActual { get; set; }
    public decimal? MealVoucherActual { get; set; }
    public decimal? PFEmployee { get; set; }
    public decimal? PFEmployeer { get; set; }
    public string? PFTotal { get; set; }
    public decimal? ESICEmployee { get; set; }
    public decimal? ESICEmployeer { get; set; }
    public string? ESICTotal { get; set; }
    public string? TDS { get; set; }
    public string? PTax { get; set; }
    public string? Loan { get; set; }
    public string? CashShort { get; set; }
    public string? DieselDeduction { get; set; }
    public string? Penality { get; set; }
    public string? Lwf { get; set; }
    public decimal? MonthlyGrossCTCActual { get; set; }
    public decimal? MonthlyGrossCTCActualAfterDeduction { get; set; }
    public decimal? Payble_Days { get; set; }
    public decimal? LeaveUsed { get; set; }
    public decimal? OpeningEL { get; set; }
    public decimal? EarnedLeaveAcquired { get; set; }
    public decimal? EarnedLeaveUsed { get; set; }
    public decimal? EarnedLeaveBalance { get; set; }
    public decimal? OpeningCL { get; set; }
    public decimal? CasualLeaveAcquired { get; set; }
    public decimal? CasualLeaveUsed { get; set; }
    public decimal? CasualLeaveBalance { get; set; }
    public decimal? OpeningCompoOff { get; set; }
    public decimal? CompoOffAcquired { get; set; }
    public decimal? CompoOffUsed { get; set; }
    public decimal? CompoOffBalance { get; set; }
    public string? MonthYear { get; set; }
}
